<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-02-27">
<meta name="description" content="What happens when you zoom in on satellite imagery? How do you convert a 30m DEM to 10m resolution? Resampling changes raster resolution, while interpolation estimates values at unmeasured locations. This model derives nearest neighbor, bilinear, and bicubic methods, showing when each is appropriate.">

<title>Raster Resampling and Interpolation – Computational Geography</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-734cb40618f438257b19a1e532635a32.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script>
  (function () {
    document.documentElement.dataset.theme = 'light';
    document.documentElement.dataset.brand = 'wayward';
    try {
      localStorage.removeItem('theme');
    } catch (err) {
      void err;
    }
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-math tag-hash-viz">


<header id="title-block-header">
<h1 class="title"><span class="chapter-title">Raster Resampling and Interpolation</span></h1>
<p class="subtitle">Changing grid resolution and filling missing values</p>

<p class="date">2026-02-27</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#before-you-start" id="toc-before-you-start">Before You Start</a></li>
  <li><a href="#the-question" id="toc-the-question">1. The Question</a></li>
  <li><a href="#the-conceptual-model" id="toc-the-conceptual-model">2. The Conceptual Model</a>
  <ul>
  <li><a href="#the-resampling-problem" id="toc-the-resampling-problem">The Resampling Problem</a></li>
  <li><a href="#three-classical-methods" id="toc-three-classical-methods">Three Classical Methods</a></li>
  </ul></li>
  <li><a href="#building-the-mathematical-model" id="toc-building-the-mathematical-model">3. Building the Mathematical Model</a>
  <ul>
  <li><a href="#grid-coordinates" id="toc-grid-coordinates">Grid Coordinates</a></li>
  <li><a href="#nearest-neighbor" id="toc-nearest-neighbor">Nearest Neighbor</a></li>
  <li><a href="#bilinear-interpolation" id="toc-bilinear-interpolation">Bilinear Interpolation</a></li>
  <li><a href="#bicubic-interpolation" id="toc-bicubic-interpolation">Bicubic Interpolation</a></li>
  </ul></li>
  <li><a href="#worked-example-by-hand" id="toc-worked-example-by-hand">4. Worked Example by Hand</a>
  <ul>
  <li><a href="#solution" id="toc-solution">Solution</a></li>
  </ul></li>
  <li><a href="#computational-implementation" id="toc-computational-implementation">5. Computational Implementation</a></li>
  <li><a href="#interpretation" id="toc-interpretation">6. Interpretation</a>
  <ul>
  <li><a href="#when-to-use-each-method" id="toc-when-to-use-each-method">When to Use Each Method</a></li>
  <li><a href="#aliasing-in-downsampling" id="toc-aliasing-in-downsampling">Aliasing in Downsampling</a></li>
  <li><a href="#reprojection" id="toc-reprojection">Reprojection</a></li>
  </ul></li>
  <li><a href="#what-could-go-wrong" id="toc-what-could-go-wrong">7. What Could Go Wrong?</a>
  <ul>
  <li><a href="#overshoot-in-bicubic" id="toc-overshoot-in-bicubic">Overshoot in Bicubic</a></li>
  <li><a href="#edge-effects" id="toc-edge-effects">Edge Effects</a></li>
  <li><a href="#assuming-regular-grid" id="toc-assuming-regular-grid">Assuming Regular Grid</a></li>
  <li><a href="#excessive-smoothing" id="toc-excessive-smoothing">Excessive Smoothing</a></li>
  </ul></li>
  <li><a href="#extension-advanced-interpolation" id="toc-extension-advanced-interpolation">8. Extension: Advanced Interpolation</a>
  <ul>
  <li><a href="#inverse-distance-weighting-idw" id="toc-inverse-distance-weighting-idw">Inverse Distance Weighting (IDW)</a></li>
  <li><a href="#kriging" id="toc-kriging">Kriging</a></li>
  <li><a href="#thin-plate-splines" id="toc-thin-plate-splines">Thin Plate Splines</a></li>
  </ul></li>
  <li><a href="#math-refresher-linear-interpolation" id="toc-math-refresher-linear-interpolation">9. Math Refresher: Linear Interpolation</a>
  <ul>
  <li><a href="#d-case" id="toc-d-case">1D Case</a></li>
  <li><a href="#d-extension-bilinear" id="toc-d-extension-bilinear">2D Extension (Bilinear)</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary">Summary</a></li>
  </ul>
</nav>
<h2 id="before-you-start" class="anchored">Before You Start</h2>
<p><strong>You should know</strong><br>
That raster data stores values on a grid, and that not every new grid position lines up with an old one.</p>
<p><strong>You will learn</strong><br>
How nearest-neighbour, bilinear, and bicubic resampling estimate new raster values, and why method choice matters analytically as well as visually.</p>
<p><strong>Why this matters</strong><br>
Whenever rasters from different sensors, scales, or projections need to work together, resampling decisions shape the result.</p>
<p><strong>If this gets hard, focus on…</strong><br>
The practical question: when you need a value at a new pixel centre, which nearby old values should influence it?</p>
<p>When the European Space Agency launched Sentinel-2 in 2015, it offered something Landsat users had never had: 10-metre resolution imagery in the visible and near-infrared bands, freely available every five days at any point on Earth. Research groups that had built workflows around Landsat’s 30-metre pixels immediately faced a practical problem: their existing DEMs, land-cover maps, and ancillary datasets were at 30 metres. To combine them with Sentinel-2 data, someone had to resample something — either the Sentinel image to a coarser grid or the existing datasets to a finer one. The choice of resampling method matters more than most users realise: nearest-neighbour resampling is fast and preserves discrete class boundaries, but produces blocky artefacts in continuous data; bilinear interpolation is smooth but blurs edges and can create fractional class values from categorical data.</p>
<p>Resampling — changing the grid spacing of a raster — is one of the most common operations in spatial data processing, and it is unavoidable whenever data from different sources must be combined in a common grid. It is also a more mathematically interesting problem than it appears. Estimating the value at a new grid position from surrounding known values is an interpolation problem; the method chosen controls how smooth or sharp the result is, whether edges are preserved or blurred, and how well the output honours the values at original sample points. Nearest-neighbour, bilinear, and bicubic methods represent a progression of polynomial order with corresponding trade-offs in smoothness, accuracy, and computational cost. This model derives each method from first principles and shows when each is appropriate.</p>
<h2 id="the-question" class="anchored">1. The Question</h2>
<p>How do you convert a 30-meter resolution satellite image to 10-meter resolution?</p>
<p><strong>Resampling</strong> changes the grid spacing of raster data: - <strong>Upsampling (zoom in):</strong> Fewer pixels → more pixels (decrease cell size) - <strong>Downsampling (zoom out):</strong> More pixels → fewer pixels (increase cell size) - <strong>Reprojection:</strong> Change coordinate system (requires resampling)</p>
<p><strong>Interpolation</strong> estimates values between measured points: - <strong>DEM creation:</strong> Points from LiDAR → continuous elevation surface - <strong>Climate mapping:</strong> Weather stations → temperature grid - <strong>Missing data:</strong> Cloud gaps in satellite imagery → fill with neighbors</p>
<p>The mathematical question: Given values at known grid positions, how do we estimate values at new positions?</p>
<p><strong>Trade-offs:</strong> - <strong>Speed vs.&nbsp;quality:</strong> Fast methods produce blocky results - <strong>Smoothness vs.&nbsp;fidelity:</strong> Smooth methods may blur sharp features - <strong>Artifacts:</strong> Poor methods create visual or analytical problems</p>
<hr>
<h2 id="the-conceptual-model" class="anchored">2. The Conceptual Model</h2>
<h3 id="the-resampling-problem" class="anchored">The Resampling Problem</h3>
<p><strong>Input raster:</strong> Grid with cell size <span class="math inline">\Delta x_1</span>, values <span class="math inline">z_{i,j}</span></p>
<p><strong>Output raster:</strong> New grid with cell size <span class="math inline">\Delta x_2</span></p>
<p><strong>Challenge:</strong> Output pixel centers don’t align with input pixels.</p>
<p><strong>Example:</strong> Convert 30m DEM to 10m DEM - Input: 100×100 grid (30m cells) - Output: 300×300 grid (10m cells) - Must estimate elevation at 90,000 new positions from 10,000 known values</p>
<h3 id="three-classical-methods" class="anchored">Three Classical Methods</h3>
<p><strong>1. Nearest Neighbor</strong></p>
<p>Use value from closest input pixel.</p>
<p><span class="math display">z_{\text{new}}(x, y) = z_{i,j} \text{ where } (i,j) = \text{nearest to } (x,y)</span></p>
<p><strong>Pros:</strong> Fast, preserves original values (good for categorical data)<br>
<strong>Cons:</strong> Blocky appearance, discontinuous</p>
<p><strong>2. Bilinear Interpolation</strong></p>
<p>Weighted average of 4 nearest pixels.</p>
<p><span class="math display">z(x, y) = (1-u)(1-v)z_{0,0} + u(1-v)z_{1,0} + (1-u)vz_{0,1} + uvz_{1,1}</span></p>
<p>Where <span class="math inline">u, v</span> are fractional positions within cell.</p>
<p><strong>Pros:</strong> Smooth, continuous<br>
<strong>Cons:</strong> Blurs edges, creates new values not in original data</p>
<p><strong>3. Bicubic Interpolation</strong></p>
<p>Weighted average of 16 nearest pixels using cubic polynomials.</p>
<p><strong>Pros:</strong> Very smooth, preserves gradients<br>
<strong>Cons:</strong> Slower, can overshoot (create values outside original range)</p>
<figure class="cg-ill">
<div class="cg-ill__frame" data-markdown="1">
<div class="cg-ill__eyebrow">
Resampling Comparison
</div>
<h3 class="cg-ill__title anchored">
Method Choice Changes What You See
</h3>
<p class="cg-ill__lede">
All three methods fill the same finer grid, but they preserve different things: exact classes, smooth transitions, or even smoother gradients with some risk of overshoot.
</p>
<div class="cg-ill__resample">
<div class="cg-ill__pixel-card">
<div class="cg-ill__label">
Nearest neighbour
</div>
<h4 class="anchored">
Exact But Blocky
</h4>
<div class="cg-ill__pixels cg-ill__pixels--fine cg-ill__pixels--nearest">
<p><span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span></p>
</div>
<p>
Best when every original class value must stay unchanged.
</p>
</div>
<div class="cg-ill__pixel-card">
<div class="cg-ill__label">
Bilinear
</div>
<h4 class="anchored">
Smoother Transition
</h4>
<div class="cg-ill__pixels cg-ill__pixels--fine cg-ill__pixels--bilinear">
<p><span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span></p>
</div>
<p>
Good for continuous surfaces where gentle blending is acceptable.
</p>
</div>
<div class="cg-ill__pixel-card">
<div class="cg-ill__label">
Bicubic
</div>
<h4 class="anchored">
Smoothest, Most Interpretive
</h4>
<div class="cg-ill__pixels cg-ill__pixels--fine cg-ill__pixels--bicubic">
<p><span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span> <span></span><span></span><span></span><span></span><span></span><span></span></p>
</div>
<p>
Often looks best, but may invent values outside the local range.
</p>
</div>
</div>
</div>
<figcaption>
Nearest neighbour preserves original cells, bilinear blends four neighbours, and bicubic uses a wider neighbourhood to create an even smoother surface.
</figcaption>
</figure>
<figure class="cg-ill">
<div class="cg-ill__frame" data-markdown="1">
<div class="cg-ill__eyebrow">
Grid Transfer
</div>
<h3 class="cg-ill__title anchored">
Resampling Is A Question About New Pixel Centres
</h3>
<p class="cg-ill__lede">
The important move is not “make the image bigger.” It is “for each new pixel centre, decide which old values should matter most.”
</p>
<div class="cg-ill__flow">
<div class="cg-ill__flow-step">
<div class="cg-ill__label">
1
</div>
<h4 class="anchored">
Start With The Old Grid
</h4>
<p>
Known values live at old pixel centres on the original raster.
</p>
</div>
<div class="cg-ill__flow-step">
<div class="cg-ill__label">
2
</div>
<h4 class="anchored">
Lay Down The New Grid
</h4>
<p>
New cells usually do not line up exactly with the old ones.
</p>
</div>
<div class="cg-ill__flow-step">
<div class="cg-ill__label">
3
</div>
<h4 class="anchored">
Pick A Neighborhood Rule
</h4>
<p>
Nearest neighbour uses one cell, bilinear uses four, bicubic uses a wider local patch.
</p>
</div>
<div class="cg-ill__flow-step">
<div class="cg-ill__label">
4
</div>
<h4 class="anchored">
Write The New Value
</h4>
<p>
The output raster stores a new estimate at each new pixel centre.
</p>
</div>
</div>
<svg viewbox="0 0 760 250" role="img" aria-label="Illustration of raster resampling from a coarse grid to a finer grid with one query point drawing from neighboring source cells.">
</svg><p><rect x="28" y="36" width="220" height="160" rx="16" fill="#f4f7fb" stroke="#dbe3ee"> <text x="94" y="62" font-size="20" fill="#1e3a5f">old grid</text> <g stroke="#94a3b8" stroke-width="2"> <line x1="68" y1="86" x2="68" y2="174"><line x1="112" y1="86" x2="112" y2="174"><line x1="156" y1="86" x2="156" y2="174"><line x1="200" y1="86" x2="200" y2="174"> <line x1="68" y1="86" x2="200" y2="86"><line x1="68" y1="130" x2="200" y2="130"><line x1="68" y1="174" x2="200" y2="174"> </line></line></line></line></line></line></line></g> <rect x="112" y="86" width="44" height="44" fill="#bfdbfe" stroke="#60a5fa" stroke-width="3"></rect></rect></p>
<p><path d="M270 116 L330 116" stroke="#64748b" stroke-width="4" marker-end="url(#resample-arrow)"> <text x="274" y="102" font-size="15" fill="#475569">query new centres</text></path></p>
<p><rect x="352" y="36" width="220" height="160" rx="16" fill="#f6fbf8" stroke="#d5e7dc"> <text x="414" y="62" font-size="20" fill="#14532d">new grid</text> <g stroke="#cbd5e1" stroke-width="1.5"> <line x1="384" y1="86" x2="384" y2="186"><line x1="412" y1="86" x2="412" y2="186"><line x1="440" y1="86" x2="440" y2="186"><line x1="468" y1="86" x2="468" y2="186"><line x1="496" y1="86" x2="496" y2="186"><line x1="524" y1="86" x2="524" y2="186"> <line x1="384" y1="86" x2="524" y2="86"><line x1="384" y1="106" x2="524" y2="106"><line x1="384" y1="126" x2="524" y2="126"><line x1="384" y1="146" x2="524" y2="146"><line x1="384" y1="166" x2="524" y2="166"><line x1="384" y1="186" x2="524" y2="186"> </line></line></line></line></line></line></line></line></line></line></line></line></g> <circle cx="454" cy="136" r="7" fill="#dc2626"> <rect x="426" y="106" width="56" height="40" fill="none" stroke="#0f766e" stroke-width="3" stroke-dasharray="6 5"> <text x="390" y="210" font-size="15" fill="#475569">new pixel centre pulls from nearby old values</text></rect></circle></rect></p>
<p><rect x="594" y="52" width="136" height="128" rx="16" fill="#fff8ef" stroke="#f2ddbe"> <text x="626" y="80" font-size="18" fill="#92400e">methods</text> <text x="614" y="108" font-size="15" fill="#475569">nearest: 1 cell</text> <text x="614" y="132" font-size="15" fill="#475569">bilinear: 4 cells</text> <text x="614" y="156" font-size="15" fill="#475569">bicubic: wider patch</text></rect></p>
<defs> <marker id="resample-arrow" markerwidth="8" markerheight="8" refx="6" refy="4" orient="auto"> <path d="M0,0 L8,4 L0,8 z" fill="#64748b"> </path></marker> </defs>

</div>
<figcaption>
Resampling works by laying a new grid over the old one and estimating values at the new pixel centres from a chosen neighborhood rule.
</figcaption>
</figure>
<hr>
<h2 id="building-the-mathematical-model" class="anchored">3. Building the Mathematical Model</h2>
<h3 id="grid-coordinates" class="anchored">Grid Coordinates</h3>
<p><strong>Input pixel <span class="math inline">(i, j)</span> with value <span class="math inline">z_{i,j}</span></strong></p>
<p><strong>Pixel center in world coordinates:</strong></p>
<p><span class="math display">x = x_0 + i \cdot \Delta x</span> <span class="math display">y = y_0 - j \cdot \Delta y</span></p>
<p>(Note: <span class="math inline">y</span> decreases with row index—image convention)</p>
<p><strong>Query point</strong> <span class="math inline">(x_q, y_q)</span>: Where do we want to estimate <span class="math inline">z</span>?</p>
<p><strong>Find containing cell:</strong></p>
<p><span class="math display">i_q = \lfloor (x_q - x_0) / \Delta x \rfloor</span> <span class="math display">j_q = \lfloor (y_q - y_0) / \Delta y \rfloor</span></p>
<p><strong>Fractional position within cell:</strong></p>
<p><span class="math display">u = \frac{x_q - x_0}{\Delta x} - i_q</span> <span class="math display">v = \frac{y_q - y_0}{\Delta y} - j_q</span></p>
<p>Where <span class="math inline">0 \leq u, v &lt; 1</span>.</p>
<h3 id="nearest-neighbor" class="anchored">Nearest Neighbor</h3>
<p><strong>Algorithm:</strong></p>
<pre><code>i_nearest = round((xq - x0) / dx)
j_nearest = round((yq - y0) / dy)
z_interp = z[i_nearest, j_nearest]</code></pre>
<p><strong>Equivalent:</strong> Round <span class="math inline">u, v</span> to 0 or 1.</p>
<p><strong>Decision boundary:</strong> Each output pixel assigned to nearest input pixel.</p>
<p><strong>Result:</strong> Piecewise constant (stair-step appearance).</p>
<h3 id="bilinear-interpolation" class="anchored">Bilinear Interpolation</h3>
<p><strong>Four corners of cell:</strong></p>
<ul>
<li><span class="math inline">z_{0,0} = z[i_q, j_q]</span> (bottom-left)</li>
<li><span class="math inline">z_{1,0} = z[i_q+1, j_q]</span> (bottom-right)</li>
<li><span class="math inline">z_{0,1} = z[i_q, j_q+1]</span> (top-left)</li>
<li><span class="math inline">z_{1,1} = z[i_q+1, j_q+1]</span> (top-right)</li>
</ul>
<p><strong>Linear interpolation in x:</strong></p>
<p><span class="math display">z_0 = (1-u)z_{0,0} + u z_{1,0}</span> (bottom edge) <span class="math display">z_1 = (1-u)z_{0,1} + u z_{1,1}</span> (top edge)</p>
<p><strong>Linear interpolation in y:</strong></p>
<p><span class="math display">z(u, v) = (1-v)z_0 + v z_1</span></p>
<p><strong>Expanded form:</strong></p>
<p><span class="math display">z = (1-u)(1-v)z_{0,0} + u(1-v)z_{1,0} + (1-u)v z_{0,1} + uv z_{1,1}</span></p>
<p><strong>Weights sum to 1:</strong></p>
<p><span class="math inline">(1-u)(1-v) + u(1-v) + (1-u)v + uv = 1</span> ✓</p>
<p><strong>Properties:</strong> - Continuous (no jumps) - <span class="math inline">C^0</span> continuous (values match, derivatives don’t) - Exact at grid points: <span class="math inline">z(0,0) = z_{0,0}</span>, etc.</p>
<h3 id="bicubic-interpolation" class="anchored">Bicubic Interpolation</h3>
<p><strong>Uses 16 pixels</strong> (4×4 neighborhood centered on query point).</p>
<p><strong>Cubic convolution kernel:</strong></p>
<p><span class="math display">w(x) = \begin{cases}
(a+2)|x|^3 - (a+3)|x|^2 + 1 &amp; \text{if } |x| \leq 1 \\
a|x|^3 - 5a|x|^2 + 8a|x| - 4a &amp; \text{if } 1 &lt; |x| &lt; 2 \\
0 &amp; \text{if } |x| \geq 2
\end{cases}</span></p>
<p>Where <span class="math inline">a = -0.5</span> (standard choice) or <span class="math inline">a = -0.75</span> (sharper).</p>
<p><strong>Interpolation:</strong></p>
<p><span class="math display">z(u, v) = \sum_{m=0}^{3} \sum_{n=0}^{3} z_{m-1, n-1} \cdot w(m - u) \cdot w(n - v)</span></p>
<p><strong>Properties:</strong> - <span class="math inline">C^1</span> continuous (smooth derivatives) - Preserves local shape better than bilinear - Can overshoot (produce values &lt; min or &gt; max of neighbors)</p>
<hr>
<h2 id="worked-example-by-hand" class="anchored">4. Worked Example by Hand</h2>
<p><strong>Problem:</strong> Resample this 2×2 elevation grid to find elevation at <span class="math inline">(1.3, 0.7)</span> using bilinear interpolation.</p>
<p><strong>Input grid (1m cells):</strong></p>
<pre><code>       x=0   x=1   x=2
y=0    100   110
y=1    105   120</code></pre>
<p>Grid origin at <span class="math inline">(0, 0)</span>, cell size = 1m.</p>
<p><strong>Query point:</strong> <span class="math inline">(x_q, y_q) = (1.3, 0.7)</span></p>
<h3 id="solution" class="anchored">Solution</h3>
<p><strong>Step 1: Find containing cell</strong></p>
<p><span class="math display">i_q = \lfloor 1.3 / 1 \rfloor = 1</span> <span class="math display">j_q = \lfloor 0.7 / 1 \rfloor = 0</span></p>
<p>Cell corners at: <span class="math inline">(1,0)</span>, <span class="math inline">(2,0)</span>, <span class="math inline">(1,1)</span>, <span class="math inline">(2,1)</span></p>
<p><strong>Step 2: Fractional position</strong></p>
<p><span class="math display">u = 1.3 - 1 = 0.3</span> <span class="math display">v = 0.7 - 0 = 0.7</span></p>
<p><strong>Step 3: Get corner values</strong></p>
<ul>
<li><span class="math inline">z_{0,0} = z[1,0] = 110</span> (bottom-left of cell)</li>
<li><span class="math inline">z_{1,0} = z[2,0] = ?</span> (missing—assume 115 for example)</li>
<li><span class="math inline">z_{0,1} = z[1,1] = 120</span> (top-left)</li>
<li><span class="math inline">z_{1,1} = z[2,1] = ?</span> (assume 125)</li>
</ul>
<p>Actually, our grid only goes to <span class="math inline">x=1</span>. Let me recalculate with correct bounds.</p>
<p><strong>Corrected:</strong> Query <span class="math inline">(1.3, 0.7)</span> is outside grid. Let’s use <span class="math inline">(0.3, 0.7)</span> instead.</p>
<p><strong>Step 1 (corrected):</strong></p>
<p><span class="math display">i_q = \lfloor 0.3 / 1 \rfloor = 0</span> <span class="math display">j_q = \lfloor 0.7 / 1 \rfloor = 0</span></p>
<p><strong>Step 2:</strong></p>
<p><span class="math display">u = 0.3 - 0 = 0.3</span> <span class="math display">v = 0.7 - 0 = 0.7</span></p>
<p><strong>Step 3: Corner values</strong></p>
<ul>
<li><span class="math inline">z_{0,0} = z[0,0] = 100</span></li>
<li><span class="math inline">z_{1,0} = z[1,0] = 110</span></li>
<li><span class="math inline">z_{0,1} = z[0,1] = 105</span></li>
<li><span class="math inline">z_{1,1} = z[1,1] = 120</span></li>
</ul>
<p><strong>Step 4: Bilinear formula</strong></p>
<p><span class="math display">z = (1-0.3)(1-0.7) \cdot 100 + (0.3)(1-0.7) \cdot 110</span> <span class="math display">\quad + (1-0.3)(0.7) \cdot 105 + (0.3)(0.7) \cdot 120</span></p>
<p><span class="math display">= 0.7 \times 0.3 \times 100 + 0.3 \times 0.3 \times 110</span> <span class="math display">\quad + 0.7 \times 0.7 \times 105 + 0.3 \times 0.7 \times 120</span></p>
<p><span class="math display">= 21 + 9.9 + 51.45 + 25.2 = 107.55 \text{ m}</span></p>
<p><strong>Verification:</strong> - Nearest to <span class="math inline">(0,1)</span> at 105m (weight 0.49) - Also weighted toward 110 and 120 - Result 107.55 is reasonable weighted average</p>
<hr>
<h2 id="computational-implementation" class="anchored">5. Computational Implementation</h2>
<p>Below is an interactive resampling demonstration.</p>
<div class="viz-container" id="resample-viz">
<div class="controls">
<label>
Method:
<select id="interp-method">
<option value="nearest">Nearest Neighbor</option>
<option value="bilinear" selected="">Bilinear</option>
<option value="bicubic">Bicubic</option>
</select>
</label>
<label>
Output resolution:
<input type="range" id="resolution-slider" min="5" max="30" step="5" value="10">
<span id="resolution-value">10</span>×
</label>
<label>
Show input grid:
<input type="checkbox" id="show-input" checked="">
</label>
<div class="resample-info">
<p><strong>Input cells:</strong> 5×5 = 25</p>
<p><strong>Output cells:</strong> <span id="output-cells">--</span></p>
<p><strong>Sampling ratio:</strong> <span id="sample-ratio">--</span>×</p>
</div>
</div>
<div id="resample-canvas-container">
<canvas id="resample-canvas" width="600" height="300" style="border: 1px solid #ddd;"></canvas>
</div>
</div>

<script type="module">
(function() {
const canvas = document.getElementById('resample-canvas');
const ctx = canvas.getContext('2d');
  
let method = 'bilinear';
let outputRes = 10;
let showInput = true;
  
// Create simple 5x5 input grid with elevation pattern
const inputSize = 5;
const inputData = [];
for (let j = 0; j < inputSize; j++) {
const row = [];
for (let i = 0; i < inputSize; i++) {
// Create smooth elevation pattern
const cx = 2, cy = 2;
const dist = Math.sqrt((i - cx) ** 2 + (j - cy) ** 2);
const elev = 100 + 50 * Math.exp(-dist / 2);
row.push(elev);
}
inputData.push(row);
}
  
function nearestNeighbor(data, x, y) {
const i = Math.round(x);
const j = Math.round(y);
if (i < 0 || i >= data[0].length || j < 0 || j >= data.length) {
return 100; // Default
}
return data[j][i];
}
  
function bilinear(data, x, y) {
const i = Math.floor(x);
const j = Math.floor(y);
const u = x - i;
const v = y - j;
    
if (i < 0 || i >= data[0].length - 1 || j < 0 || j >= data.length - 1) {
return nearestNeighbor(data, x, y);
}
    
const z00 = data[j][i];
const z10 = data[j][i + 1];
const z01 = data[j + 1][i];
const z11 = data[j + 1][i + 1];
    
return (1 - u) * (1 - v) * z00 +
u * (1 - v) * z10 +
(1 - u) * v * z01 +
u * v * z11;
}
  
function cubicKernel(x, a = -0.5) {
const ax = Math.abs(x);
if (ax <= 1) {
return (a + 2) * ax ** 3 - (a + 3) * ax ** 2 + 1;
} else if (ax < 2) {
return a * ax ** 3 - 5 * a * ax ** 2 + 8 * a * ax - 4 * a;
}
return 0;
}
  
function bicubic(data, x, y) {
const i = Math.floor(x);
const j = Math.floor(y);
const u = x - i;
const v = y - j;
    
let sum = 0;
for (let m = 0; m < 4; m++) {
for (let n = 0; n < 4; n++) {
const ii = i + m - 1;
const jj = j + n - 1;
        
if (ii >= 0 && ii < data[0].length && jj >= 0 && jj < data.length) {
const w = cubicKernel(m - u) * cubicKernel(n - v);
sum += data[jj][ii] * w;
}
}
}
    
return sum;
}
  
function resample(data, method, outputSize) {
const inputHeight = data.length;
const inputWidth = data[0].length;
const scaleX = (inputWidth - 1) / (outputSize - 1);
const scaleY = (inputHeight - 1) / (outputSize - 1);
    
const output = [];
for (let j = 0; j < outputSize; j++) {
const row = [];
for (let i = 0; i < outputSize; i++) {
const x = i * scaleX;
const y = j * scaleY;
        
let value;
if (method === 'nearest') {
value = nearestNeighbor(data, x, y);
} else if (method === 'bilinear') {
value = bilinear(data, x, y);
} else {
value = bicubic(data, x, y);
}
        
row.push(value);
}
output.push(row);
}
    
return output;
}
  
function drawRaster(data, x, y, width, height, label) {
const cellWidth = width / data[0].length;
const cellHeight = height / data.length;
    
// Find min/max for color scale
let min = Infinity, max = -Infinity;
for (let row of data) {
for (let val of row) {
min = Math.min(min, val);
max = Math.max(max, val);
}
}
    
// Draw cells
for (let j = 0; j < data.length; j++) {
for (let i = 0; i < data[0].length; i++) {
const value = data[j][i];
const normalized = (value - min) / (max - min);
        
// Color scale: blue (low) to red (high)
const r = Math.floor(255 * normalized);
const g = Math.floor(100 * (1 - Math.abs(normalized - 0.5) * 2));
const b = Math.floor(255 * (1 - normalized));
        
ctx.fillStyle = `rgb(${r}, ${g}, ${b})`;
ctx.fillRect(
x + i * cellWidth,
y + j * cellHeight,
cellWidth,
cellHeight
);
}
}
    
// Draw grid if input
if (showInput && label === 'Input') {
ctx.strokeStyle = '#FFF';
ctx.lineWidth = 1;
for (let i = 0; i <= data[0].length; i++) {
ctx.beginPath();
ctx.moveTo(x + i * cellWidth, y);
ctx.lineTo(x + i * cellWidth, y + height);
ctx.stroke();
}
for (let j = 0; j <= data.length; j++) {
ctx.beginPath();
ctx.moveTo(x, y + j * cellHeight);
ctx.lineTo(x + width, y + j * cellHeight);
ctx.stroke();
}
}
    
// Label
ctx.fillStyle = '#2C3E50';
ctx.font = 'bold 14px sans-serif';
ctx.fillText(label, x + 5, y + 20);
}
  
function render() {
ctx.clearRect(0, 0, canvas.width, canvas.height);
    
const outputData = resample(inputData, method, outputRes);
    
// Draw input
drawRaster(inputData, 20, 20, 250, 250, 'Input (5×5)');
    
// Draw output
drawRaster(outputData, 320, 20, 250, 250, `Output (${outputRes}×${outputRes})`);
    
// Update stats
document.getElementById('output-cells').textContent = outputRes * outputRes;
document.getElementById('sample-ratio').textContent = 
((outputRes * outputRes) / 25).toFixed(1);
}
  
document.getElementById('interp-method').addEventListener('change', (e) => {
method = e.target.value;
render();
});
  
document.getElementById('resolution-slider').addEventListener('input', (e) => {
outputRes = parseInt(e.target.value);
document.getElementById('resolution-value').textContent = outputRes;
render();
});
  
document.getElementById('show-input').addEventListener('change', (e) => {
showInput = e.target.checked;
render();
});
  
render();
})();
</script>
<p><strong>Try this:</strong> - <strong>Nearest neighbor:</strong> Blocky, stair-step appearance (preserves exact values) - <strong>Bilinear:</strong> Smooth, continuous (but blurs the peak) - <strong>Bicubic:</strong> Very smooth (may overshoot slightly) - <strong>Increase resolution:</strong> More output pixels reveal interpolation differences - <strong>Color scale:</strong> Blue = low elevation, Red = high elevation - Notice: Nearest neighbor preserves sharp gradients, bilinear smooths them</p>
<p><strong>Key insight:</strong> Method choice depends on data type—categorical (land cover) needs nearest neighbor, continuous (elevation) benefits from bilinear/bicubic.</p>
<hr>
<h2 id="interpretation" class="anchored">6. Interpretation</h2>
<h3 id="when-to-use-each-method" class="anchored">When to Use Each Method</h3>
<p><strong>Nearest Neighbor:</strong> - <strong>Categorical data:</strong> Land cover, soil types, zoning codes - <strong>Preserving exact values:</strong> Don’t want interpolated values (e.g., “class 2.3”) - <strong>Speed critical:</strong> Fastest method - <strong>Example:</strong> Reproject land cover map—don’t create new land cover classes</p>
<p><strong>Bilinear:</strong> - <strong>Continuous data:</strong> Elevation, temperature, NDVI - <strong>General purpose:</strong> Good balance of speed and quality - <strong>Moderate smoothing acceptable:</strong> Slight blur is OK - <strong>Example:</strong> Resize satellite imagery for display</p>
<p><strong>Bicubic:</strong> - <strong>High-quality visualization:</strong> Print maps, publications - <strong>Preserving gradients:</strong> Slope/aspect calculation from DEM - <strong>Smooth interpolation needed:</strong> Climate surfaces, bathymetry - <strong>Example:</strong> Upsample DEM for detailed terrain visualization</p>
<h3 id="aliasing-in-downsampling" class="anchored">Aliasing in Downsampling</h3>
<p><strong>Problem:</strong> Downsampling without filtering causes <strong>aliasing</strong> (high-frequency artifacts).</p>
<p><strong>Example:</strong> 100m DEM → 1000m DEM by sampling every 10th pixel - Misses peaks/valleys between sampled points - Creates artificial patterns</p>
<p><strong>Solution:</strong> <strong>Average</strong> all input pixels that fall within output pixel (anti-aliasing filter).</p>
<pre><code>For each output pixel:
    Find all input pixels within its extent
    z_output = mean(z_input)</code></pre>
<p>This is <strong>area-weighted averaging</strong>, not interpolation.</p>
<h3 id="reprojection" class="anchored">Reprojection</h3>
<p><strong>Changing coordinate systems</strong> requires resampling:</p>
<pre><code>1. Create output grid in new projection
2. For each output pixel:
    a. Transform pixel center to input projection
    b. Interpolate value from input grid
    c. Assign to output pixel</code></pre>
<p><strong>Challenge:</strong> Output pixel may correspond to irregular shape in input space.</p>
<p><strong>Common practice:</strong> Use bilinear for most data, nearest neighbor for categorical.</p>
<hr>
<h2 id="what-could-go-wrong" class="anchored">7. What Could Go Wrong?</h2>
<h3 id="overshoot-in-bicubic" class="anchored">Overshoot in Bicubic</h3>
<p><strong>Bicubic can create values outside input range.</strong></p>
<p><strong>Example:</strong> - Input range: [0, 255] (8-bit image) - Bicubic output: Values like -5 or 270</p>
<p><strong>Problem:</strong> Invalid for physical quantities (negative reflectance, temperatures &gt; known max)</p>
<p><strong>Solution:</strong> Clamp output to valid range: <code>value = max(min_valid, min(max_valid, value))</code></p>
<h3 id="edge-effects" class="anchored">Edge Effects</h3>
<p><strong>Near grid boundaries:</strong> Insufficient neighbors for bilinear/bicubic.</p>
<p><strong>Options:</strong> 1. <strong>Fallback to nearest neighbor</strong> at edges 2. <strong>Pad with replicated edge values</strong> 3. <strong>Assume zeros</strong> beyond boundary 4. <strong>Reflect</strong> boundary (mirror)</p>
<p><strong>Choice depends on data semantics.</strong></p>
<h3 id="assuming-regular-grid" class="anchored">Assuming Regular Grid</h3>
<p><strong>Many interpolation methods assume:</strong> - Rectangular grid - Uniform spacing - Aligned with axes</p>
<p><strong>Real data may be:</strong> - Irregular point clouds (LiDAR) - Rotated grids - Variable resolution</p>
<p><strong>Solution:</strong> Use <strong>scattered data interpolation</strong> (IDW, kriging) or triangulation.</p>
<h3 id="excessive-smoothing" class="anchored">Excessive Smoothing</h3>
<p><strong>Bilinear/bicubic blur sharp features.</strong></p>
<p><strong>Problem for:</strong> - Coastlines (land/water boundary) - Faults (abrupt elevation change) - Roads (linear features)</p>
<p><strong>Solution:</strong> - Use nearest neighbor for boundaries - Edge-preserving filters - Or accept smoothing as necessary artifact</p>
<hr>
<h2 id="extension-advanced-interpolation" class="anchored">8. Extension: Advanced Interpolation</h2>
<h3 id="inverse-distance-weighting-idw" class="anchored">Inverse Distance Weighting (IDW)</h3>
<p><strong>For irregular point data:</strong></p>
<p><span class="math display">z(x, y) = \frac{\sum_i w_i z_i}{\sum_i w_i}</span></p>
<p>Where:</p>
<p><span class="math display">w_i = \frac{1}{d_i^p}</span></p>
<p><span class="math inline">d_i</span> = distance from <span class="math inline">(x,y)</span> to point <span class="math inline">i</span><br>
<span class="math inline">p</span> = power parameter (typically 2)</p>
<p><strong>Nearby points</strong> have more influence (high weight).</p>
<h3 id="kriging" class="anchored">Kriging</h3>
<p><strong>Geostatistical interpolation</strong> using spatial covariance.</p>
<p><strong>Steps:</strong> 1. Fit <strong>variogram</strong> (model of spatial correlation vs.&nbsp;distance) 2. Solve system of equations for weights 3. Compute weighted sum (optimal in least-squares sense)</p>
<p><strong>Advantage:</strong> Provides uncertainty estimates.</p>
<p><strong>Disadvantage:</strong> Computationally expensive, requires expertise.</p>
<h3 id="thin-plate-splines" class="anchored">Thin Plate Splines</h3>
<p><strong>Minimizes bending energy</strong> (creates smoothest surface).</p>
<p><strong>Used for:</strong> - Climate data interpolation - Surface fitting with constraints - Morphing between shapes</p>
<p><strong>Disadvantage:</strong> Global method (slow for large datasets).</p>
<hr>
<h2 id="math-refresher-linear-interpolation" class="anchored">9. Math Refresher: Linear Interpolation</h2>
<h3 id="d-case" class="anchored">1D Case</h3>
<p><strong>Points:</strong> <span class="math inline">(x_0, y_0)</span> and <span class="math inline">(x_1, y_1)</span></p>
<p><strong>Interpolate at <span class="math inline">x</span>:</strong></p>
<p><span class="math display">y = y_0 + \frac{x - x_0}{x_1 - x_0}(y_1 - y_0)</span></p>
<p><strong>Equivalent form:</strong></p>
<p><span class="math display">y = (1 - t) y_0 + t y_1</span></p>
<p>Where <span class="math inline">t = \frac{x - x_0}{x_1 - x_0}</span> is normalized position.</p>
<p><strong>Properties:</strong> - Linear in <span class="math inline">x</span> - Exact at endpoints: <span class="math inline">y(x_0) = y_0</span>, <span class="math inline">y(x_1) = y_1</span> - <span class="math inline">t = 0</span> → <span class="math inline">y = y_0</span>; <span class="math inline">t = 1</span> → <span class="math inline">y = y_1</span></p>
<h3 id="d-extension-bilinear" class="anchored">2D Extension (Bilinear)</h3>
<p><strong>Apply linear interpolation twice:</strong></p>
<ol type="1">
<li>Interpolate along x at <span class="math inline">y_0</span>: get <span class="math inline">f(x, y_0)</span></li>
<li>Interpolate along x at <span class="math inline">y_1</span>: get <span class="math inline">f(x, y_1)</span></li>
<li>Interpolate between these along y: get <span class="math inline">f(x, y)</span></li>
</ol>
<p><strong>Result:</strong> Bilinear = product of two linear interpolations.</p>
<p><strong>Not</strong> the same as 2D linear (plane through 3 points)—bilinear is a <strong>hyperbolic paraboloid</strong> (saddle shape).</p>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<ul>
<li><strong>Resampling</strong> changes grid resolution (upsampling or downsampling)</li>
<li><strong>Interpolation</strong> estimates values at new positions from known values</li>
<li><strong>Nearest neighbor:</strong> Fast, preserves values, blocky (use for categorical data)</li>
<li><strong>Bilinear:</strong> Smooth, continuous, general-purpose (use for continuous data)</li>
<li><strong>Bicubic:</strong> Very smooth, preserves gradients, can overshoot (use for high-quality)</li>
<li><strong>Downsampling needs filtering</strong> to avoid aliasing (average, don’t just sample)</li>
<li><strong>Reprojection</strong> requires resampling (transform coordinates, then interpolate)</li>
<li><strong>Challenges:</strong> Edge effects, overshoot, excessive smoothing</li>
<li><strong>Advanced methods:</strong> IDW, kriging, splines for irregular data</li>
<li>Interpolation is weighted averaging where weights depend on distance/position</li>
</ul>


<footer class="wayward-footer">
  <div class="wayward-footer__inner">
    <div class="wayward-footer__brand">
      <div class="wayward-footer__logo">WaywardHouse<span>.</span></div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wayward-footer__group" aria-labelledby="footer-reading">
      <h2 id="footer-reading" class="anchored">Reading</h2>
      <a href="https://wayward.house/articles/">Articles</a>
      <a href="https://wayward.house/learn/">Library</a>
      <a href="https://wayward.house/archive.html">Archive</a>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-site">
      <h2 id="footer-site" class="anchored">Site</h2>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
      <a href="https://wayward.house/about.html">About</a>
      <a href="https://wayward.house/contact.html">Contact</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-resources">
      <h2 id="footer-resources" class="anchored">Resources</h2>
      <a href="https://wayward.house/topics/">All Topics</a>
      <a href="https://wayward.house/privacy.html">Privacy Policy</a>
      <a href="https://wayward.house/terms.html">Terms of Use</a>
    </nav>
  </div>
</footer>

<script type="module" src="../assets/dist/main.js"></script>
<script type="module" src="../assets/js/core.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>