<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-05">
<meta name="description" content="A boreal wildfire in northern Alberta may burn for weeks and consume millions of tonnes of organic matter — releasing carbon as CO₂, CO, CH₄, and pyrogenic black carbon simultaneously. Unlike fossil fuel combustion, biomass burning releases carbon that was recently drawn from the atmosphere by photosynthesis. Whether this makes it “carbon neutral” depends on the fire return interval and the fate of the pyrogenic carbon fraction. This article derives the modified combustion efficiency, partitions the carbon among all pyrogenic products, calculates prescribed burn emissions, and examines the conditions under which fire is or is not carbon neutral.">

<title>Biomass Burning and Pyrogenic Carbon – WaywardHouse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<link href="../../assets/images/logo.webp" rel="icon">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-html-640605f58ae58ee79329c070719e555b.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>
<script>
  (function () {
    var s = localStorage.getItem('theme');
    var dark = s !== null ? s === 'dark' : false;
    document.documentElement.dataset.theme = dark ? 'dark' : 'light';
    document.documentElement.dataset.brand = 'wayward';
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-math tag-hash-viz">


<header id="title-block-header">
<h1 class="title">Biomass Burning and Pyrogenic Carbon</h1>
<p class="subtitle">Combustion completeness, pyrogenic carbon partition, and fire carbon neutrality</p>

<p class="date">2026-03-05</p>
</header>


<p>On May 3, 2016, a wildfire ignited southwest of Fort McMurray, Alberta. Over the following two weeks it burned 590,000 hectares, releasing an estimated 570 million tonnes of CO₂ — more than the annual emissions of the entire United Kingdom. Yet this carbon had been drawn from the atmosphere over the preceding decades by boreal forest photosynthesis. In the long view, fire is part of the boreal carbon cycle, not an addition to it. Whether any particular fire represents a net carbon source depends on factors that span centuries: How much carbon was burned? How much char was produced and how long will it persist? When will the forest regrow to re-absorb the released carbon?</p>
<p>This article provides the tools to answer these questions quantitatively.</p>
<hr>
<h2 id="the-question">1. The Question</h2>
<p>How do we partition the carbon in burned biomass among CO₂, CO, CH₄, and char? What controls the efficiency of combustion in wildfires versus prescribed burns? Under what conditions is biomass burning carbon neutral?</p>
<hr>
<h2 id="the-conceptual-model">2. The Conceptual Model</h2>
<p>Biomass burning is chemically similar to fossil fuel combustion, but the carbon source is biogenic — recently fixed from the atmosphere — rather than geological. The fire chemistry determines how the carbon is partitioned: most goes to CO₂, but a significant fraction goes to CO (toxic, short atmospheric lifetime), CH₄ (potent greenhouse gas), and <strong>pyrogenic black carbon</strong> (BC/char) — a recalcitrant form of carbon that persists in soils for centuries to millennia.</p>
<p>The carbon neutrality question is a mass balance over time: if fire carbon is eventually replaced by regrowth, the system is neutral over the regrowth period. If the fire return interval is shorter than the regrowth period, or if the burned area converts to a different land cover, the system is a net source.</p>
<hr>
<h2 id="building-the-mathematical-model">3. Building the Mathematical Model</h2>
<h3 id="fuel-load-and-area-burned">3.1 Fuel Load and Area Burned</h3>
<p>Total carbon available for combustion:</p>
<p><span class="math display">M_C = A \times \beta \times f_C</span></p>
<p>where: - <span class="math inline">A</span> = area burned (ha or m²) - <span class="math inline">\beta</span> = fuel load (kg dry mass m⁻², or t dry mass ha⁻¹) - <span class="math inline">f_C</span> = carbon fraction of dry biomass (≈ 0.45–0.50 for most vegetation)</p>
<p>Typical fuel loads:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Biome</th>
<th>Surface fuel (t ha⁻¹)</th>
<th>Total available (t ha⁻¹)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Boreal forest (mature)</td>
<td>15–40</td>
<td>40–150 (includes duff/peat)</td>
</tr>
<tr class="even">
<td>Temperate grassland</td>
<td>2–6</td>
<td>2–6</td>
</tr>
<tr class="odd">
<td>Tropical savanna</td>
<td>3–8</td>
<td>3–8</td>
</tr>
<tr class="even">
<td>Mediterranean shrubland</td>
<td>5–20</td>
<td>5–20</td>
</tr>
<tr class="odd">
<td>Tropical deforestation</td>
<td>100–400</td>
<td>100–400</td>
</tr>
</tbody>
</table>
<p><strong>Combustion completeness</strong> <span class="math inline">\phi</span>: the fraction of available fuel that actually burns. Not all fuel in the fire perimeter is consumed — moisture, fuel arrangement, and fire intensity determine what burns.</p>
<p><span class="math display">M_C^{\text{burned}} = A \times \beta \times f_C \times \phi</span></p>
<p><span class="math inline">\phi</span> ranges from 0.1–0.3 for damp grassland to 0.9–0.98 for intense crown fires and tropical deforestation burns.</p>
<h3 id="modified-combustion-efficiency-mce">3.2 Modified Combustion Efficiency (MCE)</h3>
<p>The <strong>modified combustion efficiency</strong> measures how completely the burned carbon is oxidised to CO₂ (rather than CO):</p>
<p><span class="math display">\text{MCE} = \frac{\Delta[\text{CO}_2]}{\Delta[\text{CO}_2] + \Delta[\text{CO}]}</span></p>
<p>where <span class="math inline">\Delta</span> denotes the concentration enhancement above background in the fire plume. MCE is measured by airborne or ground-based sampling in smoke plumes.</p>
<p>MCE ranges from ~0.75 (smouldering peat fires, very incomplete) to ~0.98 (flaming grassland fires). Typical values:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Fire type</th>
<th>MCE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Flaming tropical forest</td>
<td>0.94–0.97</td>
</tr>
<tr class="even">
<td>Flaming savanna</td>
<td>0.94–0.96</td>
</tr>
<tr class="odd">
<td>Prescribed burn (flaming)</td>
<td>0.92–0.95</td>
</tr>
<tr class="even">
<td>Boreal forest (mixed)</td>
<td>0.90–0.94</td>
</tr>
<tr class="odd">
<td>Smouldering peat</td>
<td>0.75–0.85</td>
</tr>
</tbody>
</table>
<p><strong>Relationship to combustion efficiency <span class="math inline">\eta</span>:</strong> MCE accounts only for the CO₂/CO partition; it does not include CH₄ or other species. Numerically, MCE ≈ <span class="math inline">\eta_{\text{CO}_2}/(\eta_{\text{CO}_2} + \eta_{\text{CO}})</span>.</p>
<h3 id="pyrogenic-carbon-partition">3.3 Pyrogenic Carbon Partition</h3>
<p>The burned carbon <span class="math inline">M_C^{\text{burned}}</span> is distributed among four fate categories:</p>
<p><span class="math display">M_C^{\text{burned}} = M_C^{\text{CO}_2} + M_C^{\text{CO}} + M_C^{\text{CH}_4} + M_C^{\text{NMHC}} + M_C^{\text{BC}}</span></p>
<p>Expressing as fractions of burned carbon:</p>
<p><span class="math inline">&amp;#36;1 = \alpha_{\text{CO}_2} + \alpha_{\text{CO}} + \alpha_{\text{CH}_4} + \alpha_{\text{NMHC}} + \alpha_{\text{BC}}</span>$</p>
<p><strong>Emission factors relative to CO₂ (molar ratios, from plume measurements):</strong></p>
<p>Emission ratios ER = <span class="math inline">\Delta X / \Delta\text{CO}_2</span> (mol/mol). Converting to mass fractions using molecular weights:</p>
<p>For CO: <span class="math inline">\alpha_{\text{CO}} = \text{ER}_{\text{CO}} \times \frac{M_{\text{CO}}}{M_{\text{CO}_2}} \times \frac{M_C^{\text{CO}}}{M_C^{\text{CO}_2}}</span></p>
<p>In practice, emission factors (EF) are tabulated in g per kg dry matter burned, derived from plume measurements. Typical values for boreal forest fire:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Species</th>
<th>EF (g/kg dry matter)</th>
<th>Equivalent <span class="math inline">\alpha</span> fraction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CO₂</td>
<td>1630</td>
<td>0.89 (as C)</td>
</tr>
<tr class="even">
<td>CO</td>
<td>127</td>
<td>0.065</td>
</tr>
<tr class="odd">
<td>CH₄</td>
<td>5.8</td>
<td>0.004</td>
</tr>
<tr class="even">
<td>NMHC</td>
<td>8.4</td>
<td>0.005</td>
</tr>
<tr class="odd">
<td>BC</td>
<td>0.56</td>
<td>0.0003</td>
</tr>
<tr class="even">
<td>OC</td>
<td>9.1</td>
<td>0.006</td>
</tr>
</tbody>
</table>
<p>The <strong>pyrogenic black carbon fraction</strong> <span class="math inline">\alpha_{\text{BC}} \approx 0.01</span>–0.03 of burned carbon — small in mass but climatically and biogeochemically significant because of its millennial persistence.</p>
<h3 id="emissions-calculation">3.4 Emissions Calculation</h3>
<p>Total CO₂ from a fire:</p>
<p><span class="math display">E_{\text{CO}_2} = A \times \beta \times \phi \times \text{EF}_{\text{CO}_2} \times 10^{-3}</span></p>
<p>where <span class="math inline">\text{EF}_{\text{CO}_2}</span> is in g/kg and the factor $10^{-3}$ converts g to kg. In practice, emission factors are often expressed in t CO₂ per ha:</p>
<p><span class="math display">E_{\text{CO}_2} = A \times \beta \times \phi \times f_C \times \alpha_{\text{CO}_2} \times \frac{44}{12}</span></p>
<p><strong>CH₄ CO₂-equivalent:</strong></p>
<p><span class="math display">E_{\text{CH}_4,\,\text{CO}_2\text{-eq}} = A \times \beta \times \phi \times f_C \times \alpha_{\text{CH}_4} \times \frac{16}{12} \times \text{GWP}_{\text{CH}_4}</span></p>
<h3 id="fire-carbon-neutrality">3.5 Fire Carbon Neutrality</h3>
<p>Biomass burning releases carbon that was recently absorbed from the atmosphere. Whether the fire represents a permanent CO₂ source depends on the ecosystem carbon dynamics:</p>
<p><strong>Case 1 — Carbon-neutral fire:</strong> If the burned area regrows to the same carbon stock within the fire return interval <span class="math inline">T_r</span>, the long-term net flux is zero. This requires: - Sufficient time for regrowth: <span class="math inline">T_r \gg T_{\text{regrowth}}</span> - No land use change following the fire</p>
<p><strong>Regrowth timescale <span class="math inline">T_{\text{regrowth}}</span>:</strong> The time for forest biomass to recover to pre-fire levels follows a logistic-like curve. For boreal forests, full recovery requires 80–150 years; for temperate forests, 50–80 years; for tropical forests, 20–40 years (if allowed to recover). If the mean fire return interval equals the recovery time, the long-term carbon balance is zero.</p>
<p><strong>Case 2 — Net source:</strong> If <span class="math inline">T_r &lt; T_{\text{regrowth}}</span>: the system is not fully recovered before the next fire — net carbon is lost to the atmosphere over time.</p>
<p><strong>Formal analysis:</strong> Consider a forest that holds equilibrium carbon stock <span class="math inline">C_0</span> (t C ha⁻¹). After a fire releasing fraction <span class="math inline">\phi</span> of the carbon, regrowth follows:</p>
<p><span class="math display">C(t) = C_0\left[1 - \phi e^{-t/\tau}\right]</span></p>
<p>where <span class="math inline">\tau</span> is the regrowth time constant. The mean carbon stock over a fire return interval <span class="math inline">T_r</span> is:</p>
<p><span class="math display">\bar{C} = C_0\left[1 - \frac{\phi\tau}{T_r}(1 - e^{-T_r/\tau})\right]</span></p>
<p>For <span class="math inline">T_r \gg \tau</span>: <span class="math inline">\bar{C} \to C_0</span> — carbon neutral. For <span class="math inline">T_r \ll \tau</span>: <span class="math inline">\bar{C} \to C_0(1-\phi)</span> — persistent reduction.</p>
<p><strong>Pyrogenic carbon exception:</strong> The BC/char fraction (<span class="math inline">\alpha_{\text{BC}}</span>) is not re-released in subsequent fires on century timescales — it accumulates in soil with a mean residence time of 500–5,000 years. Over long timescales, repeated fires may actually <strong>increase</strong> soil BC stocks while reducing aboveground carbon stocks.</p>
<hr>
<h2 id="worked-example-by-hand">4. Worked Example by Hand</h2>
<p><strong>Setting:</strong> Prescribed burn in boreal forest, Saskatchewan. Area = 2,000 ha. Surface fuel load = 12 t ha⁻¹ dry matter. Combustion completeness <span class="math inline">\phi = 0.80</span>. MCE = 0.93. <span class="math inline">f_C = 0.47</span>.</p>
<p><strong>Step 1: Total carbon input</strong></p>
<p><span class="math display">M_C = 2000 \times 12 \times 0.47 = 11,280 \text{ t C}</span></p>
<p><strong>Step 2: Carbon burned</strong></p>
<p><span class="math display">M_C^{\text{burned}} = 11,280 \times 0.80 = 9,024 \text{ t C}</span></p>
<p><strong>Step 3: CO₂ emission</strong> (using EF = 1,630 g/kg dry matter for boreal forest):</p>
<p><span class="math display">E_{\text{CO}_2} = 2000 \times 12 \times 0.80 \times 1630 \times 10^{-6} = 31,296 \text{ t CO}_2</span></p>
<p><strong>Cross-check via stoichiometry</strong> (<span class="math inline">\alpha_{\text{CO}_2} = 0.89</span> as C fraction, MCE correction): <span class="math display">E_{\text{CO}_2} = 9,024 \times 0.89 \times 3.667 = 29,448 \text{ t CO}_2 \quad \checkmark</span></p>
<p>(Small difference from MCE approximation vs.&nbsp;EF table — both approaches yield the same order of magnitude.)</p>
<p><strong>Step 4: CH₄ emission</strong> (EF = 5.8 g/kg):</p>
<p><span class="math display">E_{\text{CH}_4} = 2000 \times 12 \times 0.80 \times 5.8 \times 10^{-6} = 111.4 \text{ t CH}_4 \times 30 = 3,342 \text{ t CO}_2\text{-eq}</span></p>
<p><strong>Step 5: Total CO₂-eq</strong></p>
<p><span class="math display">E_{\text{total}} \approx 31,296 + 3,342 = 34,638 \text{ t CO}_2\text{-eq}</span></p>
<p><strong>Carbon neutrality check:</strong> Boreal forest NPP ≈ 2 t C ha⁻¹ yr⁻¹. Time to re-sequester $9,024$ t C:</p>
<p><span class="math display">t_{\text{reseq}} = \frac{9,024}{2000 \times 2} = 2.3 \text{ years} \quad \text{(for surface fuels)}</span></p>
<p>For the full ecosystem recovery (including soil carbon): 50–100 years. Prescribed fire every 10–20 years = carbon-neutral at the surface fuel level.</p>
<hr>
<h2 id="computational-implementation">5. Computational Implementation</h2>
<pre><code>function fire_emissions(area_ha, fuel_load_t_ha, phi, f_C, MCE,
                        EF_CO2=1630, EF_CO=127, EF_CH4=5.8,
                        EF_BC=0.56, GWP_CH4=30):
    # area_ha: burned area (ha)
    # fuel_load_t_ha: dry matter fuel load (t ha^-1)
    # phi: combustion completeness (0-1)
    # EF_X: emission factor (g / kg dry matter burned)
    dm_burned = area_ha * fuel_load_t_ha * phi * 1000  # kg
    CO2  = dm_burned * EF_CO2 / 1e6   # t CO2
    CO   = dm_burned * EF_CO  / 1e6   # t CO
    CH4  = dm_burned * EF_CH4 / 1e6   # t CH4
    BC   = dm_burned * EF_BC  / 1e6   # t BC
    CO2eq = CO2 + CH4 * GWP_CH4
    return {'CO2': CO2, 'CO': CO, 'CH4': CH4, 'BC': BC, 'CO2eq': CO2eq}

function carbon_neutrality_timescale(C_burned, NPP_t_C_ha, area_ha):
    return C_burned / (NPP_t_C_ha * area_ha)  # years</code></pre>
<pre class="{pyodide}"><code>def fire_emissions(area_ha, fuel_t_ha, phi, f_C=0.47, MCE=0.93,
                   EF_CO2=1630, EF_CO=127, EF_CH4=5.8, EF_BC=0.56, GWP_CH4=30):
    dm_burned_kg = area_ha * fuel_t_ha * phi * 1000  # kg dry matter
    result = {
        'Area (ha)': area_ha,
        'DM burned (t)': dm_burned_kg/1000,
        'C burned (t)': dm_burned_kg/1000 * f_C,
        'CO2 (t)': dm_burned_kg * EF_CO2 / 1e6,
        'CO (t)': dm_burned_kg * EF_CO / 1e6,
        'CH4 (t)': dm_burned_kg * EF_CH4 / 1e6,
        'BC (t)': dm_burned_kg * EF_BC / 1e6,
    }
    result['CO2eq (t)'] = result['CO2 (t)'] + result['CH4 (t)'] * GWP_CH4
    return result

scenarios = {
    'Boreal wildfire (100,000 ha)':  (100000, 20, 0.75),
    'Prescribed burn (2,000 ha)':    (2000,   12, 0.80),
    'Tropical deforestation (5 ha)': (5,      200, 0.90),
    'Grassland fire (10,000 ha)':    (10000,  4,  0.85),
}

print(f"{'Scenario':&lt;35} {'CO2 (kt)':&gt;10} {'CH4 (t)':&gt;9} {'BC (t)':&gt;8} {'CO2eq (kt)':&gt;12}")
print("-"*77)
for name, (area, fuel, phi) in scenarios.items():
    e = fire_emissions(area, fuel, phi)
    print(f"{name:&lt;35} {e['CO2 (t)']/1000:&gt;10.1f} {e['CH4 (t)']:&gt;9.0f} "
          f"{e['BC (t)']:&gt;8.1f} {e['CO2eq (t)']/1000:&gt;12.1f}")

# MCE sensitivity
print("\nMCE sensitivity — CO2 vs CO partition (boreal wildfire, 100 kt C burned):")
print(f"{'MCE':&gt;6} {'CO2 (t)':&gt;10} {'CO (t)':&gt;10} {'CO2/(CO2+CO)':&gt;14}")
for MCE in [0.75, 0.80, 0.85, 0.90, 0.93, 0.96, 0.99]:
    C_burned = 100_000  # t C
    C_CO2 = C_burned * MCE
    C_CO  = C_burned * (1 - MCE) * 0.8  # ~80% of non-CO2 goes to CO
    m_CO2 = C_CO2 * 44/12
    m_CO  = C_CO * 28/12
    check_MCE = m_CO2 / (m_CO2 + m_CO) if (m_CO2+m_CO) &gt; 0 else 0
    print(f"{MCE:&gt;6.2f} {m_CO2:&gt;10,.0f} {m_CO:&gt;10,.0f} {check_MCE:&gt;14.3f}")</code></pre>
<hr>
<h2 id="visualization">6. Visualization</h2>
<div data-viz="echarts" style="height:420px" data-options="{
  &quot;title&quot;: {&quot;text&quot;: &quot;Pyrogenic Carbon Partition by Fire Type (%  of burned carbon by fate)&quot;, &quot;textStyle&quot;: {&quot;fontSize&quot;: 14}},
  &quot;tooltip&quot;: {&quot;trigger&quot;: &quot;axis&quot;, &quot;axisPointer&quot;: {&quot;type&quot;: &quot;shadow&quot;}},
  &quot;legend&quot;: {&quot;data&quot;: [&quot;CO₂&quot;,&quot;CO&quot;,&quot;CH₄&quot;,&quot;NMHC + other&quot;,&quot;BC/char&quot;], &quot;bottom&quot;: 0},
  &quot;xAxis&quot;: {&quot;type&quot;: &quot;category&quot;,
    &quot;data&quot;: [&quot;Tropical forest&quot;, &quot;Savanna&quot;, &quot;Boreal forest&quot;, &quot;Prescribed burn&quot;, &quot;Smouldering peat&quot;]},
  &quot;yAxis&quot;: {&quot;name&quot;: &quot;% of burned carbon&quot;, &quot;nameLocation&quot;: &quot;middle&quot;, &quot;nameGap&quot;: 45, &quot;max&quot;: 100},
  &quot;series&quot;: [
    {&quot;name&quot;: &quot;CO₂&quot;,        &quot;type&quot;: &quot;bar&quot;, &quot;stack&quot;: &quot;total&quot;, &quot;itemStyle&quot;: {&quot;color&quot;: &quot;#B71C1C&quot;}, &quot;data&quot;: [92.5,91.5,88.0,86.0,70.0]},
    {&quot;name&quot;: &quot;CO&quot;,         &quot;type&quot;: &quot;bar&quot;, &quot;stack&quot;: &quot;total&quot;, &quot;itemStyle&quot;: {&quot;color&quot;: &quot;#F57F17&quot;}, &quot;data&quot;: [4.0, 5.5, 7.5, 9.0, 20.0]},
    {&quot;name&quot;: &quot;CH₄&quot;,        &quot;type&quot;: &quot;bar&quot;, &quot;stack&quot;: &quot;total&quot;, &quot;itemStyle&quot;: {&quot;color&quot;: &quot;#F9A825&quot;}, &quot;data&quot;: [0.8, 0.8, 1.2, 1.5, 4.5]},
    {&quot;name&quot;: &quot;NMHC + other&quot;,&quot;type&quot;:&quot;bar&quot;, &quot;stack&quot;: &quot;total&quot;, &quot;itemStyle&quot;: {&quot;color&quot;: &quot;#90A4AE&quot;}, &quot;data&quot;: [2.2, 1.7, 2.3, 2.5, 4.5]},
    {&quot;name&quot;: &quot;BC/char&quot;,    &quot;type&quot;: &quot;bar&quot;, &quot;stack&quot;: &quot;total&quot;, &quot;itemStyle&quot;: {&quot;color&quot;: &quot;#212121&quot;}, &quot;data&quot;: [0.5, 0.5, 1.0, 1.0, 1.0]}
  ]
}">

</div>
<p>CO₂ dominates in flaming combustion (&gt;88%); CO rises sharply as combustion efficiency falls (smouldering peat reaches 20% CO). The BC/char fraction (~0.5–1%) appears small but represents a persistent soil carbon addition — one of the few cases where fire may contribute to long-term carbon storage.</p>
<hr>
<h2 id="interpretation">7. Interpretation</h2>
<p>The MCE is the single most diagnostic quantity for a fire’s atmospheric chemistry: high MCE = predominantly flaming combustion = mostly CO₂ + heat; low MCE = smouldering = significant CO, CH₄, and organic aerosol. From a climate perspective, a smouldering peat fire in the Hudson Bay Lowlands (low MCE, slow peat regrowth over centuries) is far more concerning than a flaming grassland fire in southern Alberta (high MCE, annual grass regrowth).</p>
<p>The carbon neutrality analysis reveals that boreal wildfires are neutral over forest-length timescales (80–150 years) only if fire return intervals remain longer than regrowth times. Under climate warming, if fire return intervals shorten (more frequent fires) while regrowth rates remain unchanged, the boreal forest transitions from a long-term carbon reservoir to a net source — a positive feedback on atmospheric CO₂.</p>
<hr>
<h2 id="what-could-go-wrong">8. What Could Go Wrong?</h2>
<p><strong>Double-counting in national inventories.</strong> If a country reports both biomass burning emissions (under Agriculture, Forestry and Land Use, AFOLU) and forest carbon stock changes, the same carbon may be counted twice. IPCC guidelines prevent this by treating biomass burning as a stock-change event: the emission appears in the AFOLU sector, and the regrowth appears as a negative emission (sink) in subsequent years. Separate-sector accounting without coordination leads to double-counting or gap-missing.</p>
<p><strong>Peat fires are not carbon neutral on any practical timescale.</strong> The analysis above applies to aboveground biomass. Peat is fossilised organic carbon accumulated over thousands of years; a peat fire releases this ancient carbon in weeks. Peat fires in Indonesia, Russia, and Canada are treated as long-term carbon sources in all accounting frameworks. The combustion completeness for deep peat can be 50–90% by mass, releasing enormous quantities of CO₂ and CO from ecosystem carbon pools that will not recover for millennia.</p>
<p><strong>Emission factors depend strongly on fire type.</strong> The EF values (1,630 g CO₂/kg for boreal forest) are averages from plume measurements; individual fires range from 1,200 to 2,000 g/kg depending on fuel composition, moisture content, and fire intensity. Applying a single EF to a heterogeneous burned area introduces ±20% uncertainty in emission estimates — much larger than the analytical precision of the stoichiometric calculations.</p>
<hr>
<h2 id="summary">9. Summary</h2>
<p>Total CO₂ from biomass burning: <span class="math inline">E_{\text{CO}_2} = A \times \beta \times \phi \times \text{EF}_{\text{CO}_2}</span>, where <span class="math inline">\text{EF}_{\text{CO}_2} \approx 1,600</span>–1,800 g/kg dry matter for forest fires. MCE = <span class="math inline">\Delta[\text{CO}_2]/(\Delta[\text{CO}_2] + \Delta[\text{CO}])</span> measures flaming vs.&nbsp;smouldering dominance; values from 0.75 (peat) to 0.98 (flaming grassland).</p>
<p>Carbon is partitioned among CO₂ (~88–93%), CO (~5–8%), CH₄ (~1–2%), and BC/char (~0.5–1%) for typical forest fires. The BC fraction has millennial persistence; CO and CH₄ are eventually oxidised to CO₂.</p>
<p>Fire carbon neutrality requires <span class="math inline">T_r &gt; T_{\text{regrowth}}</span>. For boreal forests (regrowth ~80–150 years) with historical fire return intervals of 100–200 years, the balance is approximately neutral. Shortening fire return intervals under climate warming, or peat combustion, shifts the balance toward a persistent source.</p>
<hr>
<h2 id="math-refresher">Math Refresher</h2>
<p><strong>Conservation of mass in a partition.</strong> When carbon exits a fire as multiple products, the fractions must sum to exactly one: <span class="math inline">\alpha_{\text{CO}_2} + \alpha_{\text{CO}} + \alpha_{\text{CH}_4} + \alpha_{\text{NMHC}} + \alpha_{\text{BC}} = 1</span>. This is a mass balance — carbon atoms cannot be created or destroyed. Fractions are expressed as mass of carbon in each product per mass of carbon burned (not mass of product per mass of fuel). The conversion requires the 44/12, 28/12, 16/12 molecular weight ratios from Article AM1. MCE is a special case: it partitions only between CO₂ and CO, ignoring all other products — so MCE slightly overestimates the true fraction of carbon going to CO₂ by treating the CO₂+CO denominator as the total.</p>


<footer class="wayward-footer">
  <div class="wayward-footer__inner">
    <div class="wayward-footer__brand">
      <div class="wayward-footer__logo">WaywardHouse<span>.</span></div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wayward-footer__group" aria-labelledby="footer-reading">
      <h2 id="footer-reading">Reading</h2>
      <a href="../../articles/">Articles</a>
      <a href="../../learn/">Library</a>
      <a href="../../learn/computational-geography/core/">↳ Comp Geo Book</a>
      <a href="../../archive.html">Archive</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-site">
      <h2 id="footer-site">Site</h2>
      <a href="../../start-here.html">Start Here</a>
      <a href="../../about.html">About</a>
      <a href="../../contact.html">Contact</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-resources">
      <h2 id="footer-resources">Resources</h2>
      <a href="../../topics/">All Topics</a>
      <a href="../../privacy.html">Privacy Policy</a>
      <a href="../../terms.html">Terms of Use</a>
    </nav>
  </div>
</footer>

<script type="module" src="../../assets/dist/main.js"></script>
<script type="module" src="../../assets/js/core.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wayward\.house");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>