<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-02-27">
<meta name="description" content="When does vegetation green-up each spring? Is there a long-term trend in productivity? How does drought affect growing seasons? Time series analysis of satellite data decomposes observations into trend, seasonality, and noise, enabling phenology extraction, anomaly detection, and climate change assessment. This model derives harmonic analysis, implements smoothing filters, and extracts phenological metrics.">

<title>Time Series Analysis of Satellite Data – WaywardHouse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<link href="../../assets/images/logo.webp" rel="icon">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-html-640605f58ae58ee79329c070719e555b.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>
<script>
  (function () {
    var s = localStorage.getItem('theme');
    var dark = s !== null ? s === 'dark' : false;
    document.documentElement.dataset.theme = dark ? 'dark' : 'light';
    document.documentElement.dataset.brand = 'wayward';
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-math tag-hash-viz">


<header id="title-block-header">
<h1 class="title">Time Series Analysis of Satellite Data</h1>
<p class="subtitle">Extracting trends, seasonality, and phenology from multi-temporal imagery</p>

<p class="date">2026-02-27</p>
</header>


<p>Landsat 5, launched in 1984 and operational until 2013, accumulated 29 years of continuous Earth observation — 2.5 million scenes, one every 16 days at 30-metre resolution. For any specific location, that record is a time series: a sequence of NDVI or reflectance values sampled through almost three decades of seasons, droughts, fires, floods, and land-use changes. This is a remarkable scientific resource. It means that for a forest stand in Saskatchewan, or a wetland on the Mackenzie Delta, or a cropping district in southern Alberta, we can reconstruct the detailed seasonal and interannual trajectory of vegetation greenness since the mid-1980s. Embedded in that trajectory are signals of browning during the 2002 drought, accelerated green-up as spring arrives earlier, and the distinctive dip-and-recovery signature of a bark beetle outbreak.</p>
<p>Time series analysis of satellite data extracts those signals from what is otherwise a noisy record of spectral reflectance. The key decomposition separates a time series into trend (long-term directional change), seasonality (annual cycle), and residual (anomalies and noise). The seasonal component — the dominant signal for most vegetated surfaces — can be modelled as a sum of sinusoids fitted by Fourier decomposition, enabling precise extraction of phenological metrics: the date of green-up, the peak NDVI, the date of senescence, and the integrated annual productivity. The trend component, once seasonality is removed, reveals whether long-term vegetation conditions are improving or declining. This model derives the decomposition framework, implements harmonic regression, and extracts phenological metrics from MODIS time series data.</p>
<h2 id="the-question">1. The Question</h2>
<p>How has the growing season changed over the past 20 years?</p>
<p><strong>Time series analysis</strong> examines sequences of observations through time:</p>
<p><strong>Satellite time series:</strong> - MODIS: 500m, 16-day composites, 2000-present - Landsat: 30m, 16-day revisit, 1984-present - Sentinel-2: 10m, 5-day revisit, 2015-present</p>
<p><strong>Applications:</strong> - <strong>Phenology:</strong> Timing of green-up, peak, senescence - <strong>Productivity trends:</strong> Is vegetation increasing or decreasing? - <strong>Drought detection:</strong> NDVI anomalies below normal - <strong>Crop monitoring:</strong> Within-season growth patterns - <strong>Climate change:</strong> Lengthening/shortening growing seasons - <strong>Forest health:</strong> Detecting gradual decline vs.&nbsp;abrupt disturbance</p>
<p>The mathematical question: Given a noisy time series of NDVI values, how do we separate: 1. <strong>Trend:</strong> Long-term change 2. <strong>Seasonality:</strong> Repeating annual cycle 3. <strong>Noise:</strong> Random variation and clouds</p>
<hr>
<h2 id="the-conceptual-model">2. The Conceptual Model</h2>
<h3 id="time-series-components">Time Series Components</h3>
<p><strong>Additive model:</strong></p>
<p><span class="math display">y(t) = T(t) + S(t) + \varepsilon(t)</span></p>
<p>Where: - <span class="math inline">y(t)</span> = observed value at time <span class="math inline">t</span> - <span class="math inline">T(t)</span> = trend component - <span class="math inline">S(t)</span> = seasonal component - <span class="math inline">\varepsilon(t)</span> = noise/residual</p>
<p><strong>Example - NDVI time series:</strong> - <strong>Trend:</strong> Gradual greening (+0.001 NDVI/year) - <strong>Seasonal:</strong> Spring green-up, summer peak, autumn senescence - <strong>Noise:</strong> Clouds, atmospheric effects, sensor variations</p>
<h3 id="phenological-metrics">Phenological Metrics</h3>
<p><strong>Key dates in annual cycle:</strong></p>
<ol type="1">
<li><strong>Start of Season (SOS):</strong> When NDVI crosses threshold (spring green-up)</li>
<li><strong>Peak of Season (POS):</strong> Maximum NDVI (summer)</li>
<li><strong>End of Season (EOS):</strong> When NDVI falls below threshold (senescence)</li>
<li><strong>Growing Season Length (GSL):</strong> EOS - SOS</li>
</ol>
<p><strong>Amplitude:</strong> Difference between peak and minimum NDVI</p>
<p><strong>Integrated NDVI:</strong> Area under curve (proportional to productivity)</p>
<h3 id="harmonic-analysis">Harmonic Analysis</h3>
<p><strong>Model seasonal cycle with sine/cosine:</strong></p>
<p><span class="math display">S(t) = A \sin(2\pi t / P + \phi)</span></p>
<p>Where: - <span class="math inline">A</span> = amplitude - <span class="math inline">P</span> = period (365 days) - <span class="math inline">\phi</span> = phase (timing of peak)</p>
<p><strong>Multiple harmonics</strong> capture complex seasonal patterns:</p>
<p><span class="math display">S(t) = \sum_{k=1}^{n} \left[a_k \cos(2\pi k t / P) + b_k \sin(2\pi k t / P)\right]</span></p>
<p><strong>k=1:</strong> Annual cycle<br>
<strong>k=2:</strong> Bi-annual (two peaks per year)<br>
<strong>k=3:</strong> Tri-annual, etc.</p>
<hr>
<h2 id="building-the-mathematical-model">3. Building the Mathematical Model</h2>
<h3 id="moving-average-smoothing">Moving Average Smoothing</h3>
<p><strong>Simple moving average (window size <span class="math inline">w</span>):</strong></p>
<p><span class="math display">\hat{y}_t = \frac{1}{w} \sum_{i=t-w/2}^{t+w/2} y_i</span></p>
<p><strong>Reduces noise</strong> but blurs edges.</p>
<p><strong>Typical:</strong> <span class="math inline">w = 3</span> (adjacent observations)</p>
<h3 id="savitzky-golay-filter">Savitzky-Golay Filter</h3>
<p><strong>Fits polynomial</strong> to local window, evaluates at center.</p>
<p><strong>Preserves peaks better</strong> than moving average.</p>
<p><strong>Algorithm:</strong> For each point, fit polynomial of degree <span class="math inline">d</span> to <span class="math inline">w</span> neighbors, use fitted value.</p>
<p><strong>Typical:</strong> <span class="math inline">w = 5</span>, <span class="math inline">d = 2</span> (quadratic)</p>
<h3 id="trend-extraction">Trend Extraction</h3>
<p><strong>Linear trend:</strong></p>
<p><span class="math display">T(t) = \beta_0 + \beta_1 t</span></p>
<p><strong>Fit via least squares:</strong></p>
<p><span class="math display">\beta_1 = \frac{\sum (t_i - \bar{t})(y_i - \bar{y})}{\sum (t_i - \bar{t})^2}</span></p>
<p><span class="math display">\beta_0 = \bar{y} - \beta_1 \bar{t}</span></p>
<p><strong>Interpretation:</strong> - <span class="math inline">\beta_1 &gt; 0</span>: Increasing trend (greening) - <span class="math inline">\beta_1 &lt; 0</span>: Decreasing trend (browning) - <span class="math inline">\beta_1 = 0</span>: No trend</p>
<p><strong>Mann-Kendall test:</strong> Non-parametric trend significance test.</p>
<h3 id="harmonic-regression">Harmonic Regression</h3>
<p><strong>Fit annual cycle:</strong></p>
<p><span class="math display">y(t) = \beta_0 + a_1\cos(\omega t) + b_1\sin(\omega t) + \varepsilon(t)</span></p>
<p>Where <span class="math inline">\omega = 2\pi / 365</span> (radians/day).</p>
<p><strong>Amplitude:</strong></p>
<p><span class="math display">A = \sqrt{a_1^2 + b_1^2}</span></p>
<p><strong>Phase (peak timing):</strong></p>
<p><span class="math display">\phi = \arctan(b_1 / a_1)</span></p>
<p><strong>Day of year for peak:</strong></p>
<p><span class="math display">\text{DOY}_{\text{peak}} = \phi \times \frac{365}{2\pi}</span></p>
<p><strong>Add trend:</strong></p>
<p><span class="math display">y(t) = \beta_0 + \beta_1 t + a_1\cos(\omega t) + b_1\sin(\omega t)</span></p>
<h3 id="phenology-extraction">Phenology Extraction</h3>
<p><strong>Threshold method:</strong></p>
<p><strong>Start of Season:</strong> First day when <span class="math inline">\text{NDVI} &gt; T_{\text{green}}</span></p>
<p><strong>End of Season:</strong> Last day when <span class="math inline">\text{NDVI} &gt; T_{\text{green}}</span></p>
<p><strong>Typical threshold:</strong> <span class="math inline">T_{\text{green}} = 0.3</span> or <span class="math inline">T_{\text{green}} = \text{NDVI}_{\min} + 0.2(\text{NDVI}_{\max} - \text{NDVI}_{\min})</span></p>
<p><strong>Derivative method:</strong></p>
<p><strong>SOS:</strong> Maximum rate of increase</p>
<p><span class="math display">\frac{d\text{NDVI}}{dt} = \max</span></p>
<p><strong>EOS:</strong> Maximum rate of decrease</p>
<p><span class="math display">\frac{d\text{NDVI}}{dt} = \min</span></p>
<hr>
<h2 id="worked-example-by-hand">4. Worked Example by Hand</h2>
<p><strong>Problem:</strong> Extract phenology from simplified annual NDVI time series.</p>
<p><strong>Monthly NDVI values (2023):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Month</th>
<th>DOY</th>
<th>NDVI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Jan</td>
<td>15</td>
<td>0.25</td>
</tr>
<tr class="even">
<td>Feb</td>
<td>45</td>
<td>0.28</td>
</tr>
<tr class="odd">
<td>Mar</td>
<td>75</td>
<td>0.35</td>
</tr>
<tr class="even">
<td>Apr</td>
<td>105</td>
<td>0.50</td>
</tr>
<tr class="odd">
<td>May</td>
<td>135</td>
<td>0.68</td>
</tr>
<tr class="even">
<td>Jun</td>
<td>165</td>
<td>0.75</td>
</tr>
<tr class="odd">
<td>Jul</td>
<td>195</td>
<td>0.72</td>
</tr>
<tr class="even">
<td>Aug</td>
<td>225</td>
<td>0.65</td>
</tr>
<tr class="odd">
<td>Sep</td>
<td>255</td>
<td>0.50</td>
</tr>
<tr class="even">
<td>Oct</td>
<td>285</td>
<td>0.35</td>
</tr>
<tr class="odd">
<td>Nov</td>
<td>315</td>
<td>0.28</td>
</tr>
<tr class="even">
<td>Dec</td>
<td>345</td>
<td>0.25</td>
</tr>
</tbody>
</table>
<p>Find: SOS, POS, EOS, GSL using threshold <span class="math inline">T = 0.4</span></p>
<h3 id="solution">Solution</h3>
<p><strong>Step 1: Find Start of Season</strong></p>
<p>First month when NDVI &gt; 0.4: - Jan: 0.25 &lt; 0.4 - Feb: 0.28 &lt; 0.4 - Mar: 0.35 &lt; 0.4 - Apr: 0.50 &gt; 0.4 ✓</p>
<p><strong>SOS ≈ DOY 105 (mid-April)</strong></p>
<p><strong>Step 2: Find Peak of Season</strong></p>
<p>Maximum NDVI: - Max = 0.75 in June</p>
<p><strong>POS = DOY 165 (mid-June)</strong></p>
<p><strong>Step 3: Find End of Season</strong></p>
<p>Last month when NDVI &gt; 0.4: - Sep: 0.50 &gt; 0.4 ✓ - Oct: 0.35 &lt; 0.4</p>
<p><strong>EOS ≈ DOY 255 (mid-September)</strong></p>
<p><strong>Step 4: Growing Season Length</strong></p>
<p><span class="math display">\text{GSL} = \text{EOS} - \text{SOS} = 255 - 105 = 150 \text{ days}</span></p>
<p><strong>Step 5: Integrated NDVI (productivity)</strong></p>
<p><strong>Trapezoidal integration</strong> (approximate area under curve):</p>
<p><span class="math display">\int \text{NDVI} \, dt \approx \sum_{i=1}^{n-1} \frac{\text{NDVI}_i + \text{NDVI}_{i+1}}{2} \times \Delta t</span></p>
<p><span class="math display">\approx \frac{0.25+0.28}{2}\times30 + \frac{0.28+0.35}{2}\times30 + \cdots</span></p>
<p><span class="math display">\approx 30 \times (0.265 + 0.315 + 0.425 + 0.590 + 0.715 + 0.735 + 0.685 + 0.575 + 0.425 + 0.315 + 0.265)</span></p>
<p><span class="math display">\approx 30 \times 5.31 = 159.3 \text{ NDVI-days}</span></p>
<p><strong>Summary:</strong> - SOS: DOY 105 - POS: DOY 165<br>
- EOS: DOY 255 - GSL: 150 days - Integrated NDVI: ~159 (productivity proxy)</p>
<hr>
<h2 id="computational-implementation">5. Computational Implementation</h2>
<p>Below is an interactive time series analyzer.</p>
<div id="timeseries-viz" class="viz-container">
<div class="controls">
<pre><code>&lt;label&gt;
  Location type:
  &lt;select id="location-type"&gt;
    &lt;option value="temperate" selected&gt;Temperate Forest&lt;/option&gt;
    &lt;option value="grassland"&gt;Grassland&lt;/option&gt;
    &lt;option value="tropical"&gt;Tropical (Evergreen)&lt;/option&gt;
    &lt;option value="cropland"&gt;Cropland (Double-crop)&lt;/option&gt;
  &lt;/select&gt;
&lt;/label&gt;
&lt;label&gt;
  Show components:
  &lt;input type="checkbox" id="show-trend" checked&gt; Trend
  &lt;input type="checkbox" id="show-seasonal" checked&gt; Seasonal
  &lt;input type="checkbox" id="show-smoothed"&gt; Smoothed
&lt;/label&gt;
&lt;label&gt;
  Phenology threshold:
  &lt;input type="range" id="pheno-threshold" min="0.2" max="0.6" step="0.05" value="0.4"&gt;
  &lt;span id="pheno-threshold-val"&gt;0.40&lt;/span&gt;
&lt;/label&gt;
&lt;div class="timeseries-info"&gt;
  &lt;p&gt;&lt;strong&gt;Start of Season:&lt;/strong&gt; &lt;span id="sos-doy"&gt;--&lt;/span&gt;&lt;/p&gt;
  &lt;p&gt;&lt;strong&gt;Peak of Season:&lt;/strong&gt; &lt;span id="pos-doy"&gt;--&lt;/span&gt;&lt;/p&gt;
  &lt;p&gt;&lt;strong&gt;End of Season:&lt;/strong&gt; &lt;span id="eos-doy"&gt;--&lt;/span&gt;&lt;/p&gt;
  &lt;p&gt;&lt;strong&gt;Growing Season Length:&lt;/strong&gt; &lt;span id="gsl-days"&gt;--&lt;/span&gt; days&lt;/p&gt;
  &lt;p&gt;&lt;strong&gt;Trend:&lt;/strong&gt; &lt;span id="trend-value"&gt;--&lt;/span&gt; NDVI/year&lt;/p&gt;
&lt;/div&gt;</code></pre>
</div>
<div id="timeseries-canvas-container">
<pre><code>&lt;canvas id="timeseries-canvas" width="700" height="400" style="border: 1px solid #ddd;"&gt;&lt;/canvas&gt;</code></pre>
</div>
</div>
<script type="module">
await new Promise(resolve => {
  const checkECharts = () => {
    if (typeof echarts !== 'undefined') resolve();
    else setTimeout(checkECharts, 50);
  };
  checkECharts();
});

(function() {
  const chart = echarts.init(document.getElementById('timeseries-canvas'));
  
  let locationType = 'temperate';
  let showTrend = true;
  let showSeasonal = true;
  let showSmoothed = false;
  let phenoThreshold = 0.4;
  
  function generateTimeSeries(type, years = 3) {
    const data = [];
    const doy = [];
    
    for (let year = 0; year < years; year++) {
      for (let day = 1; day <= 365; day += 16) { // 16-day composites
        const t = year * 365 + day;
        const yearFrac = (day / 365);
        
        let seasonal, trend, noise, amplitude, phase;
        
        if (type === 'temperate') {
          // Single peak, strong seasonality
          amplitude = 0.35;
          phase = 0.4; // Peak in summer
          trend = 0.0005 * t / 365; // Slight greening
          seasonal = amplitude * Math.sin(2 * Math.PI * yearFrac + phase);
          noise = (Math.random() - 0.5) * 0.05;
          
        } else if (type === 'grassland') {
          // Single peak, moderate amplitude
          amplitude = 0.25;
          phase = 0.3;
          trend = -0.0002 * t / 365; // Slight browning
          seasonal = amplitude * Math.sin(2 * Math.PI * yearFrac + phase);
          noise = (Math.random() - 0.5) * 0.08;
          
        } else if (type === 'tropical') {
          // Evergreen, minimal seasonality
          amplitude = 0.08;
          phase = 0;
          trend = 0;
          seasonal = amplitude * Math.sin(2 * Math.PI * yearFrac + phase);
          noise = (Math.random() - 0.5) * 0.03;
          
        } else { // cropland
          // Double-crop, two peaks per year
          amplitude = 0.30;
          phase = 0.2;
          trend = 0.0003 * t / 365;
          seasonal = amplitude * (Math.sin(2 * Math.PI * yearFrac + phase) + 
                                  0.5 * Math.sin(4 * Math.PI * yearFrac + 0.5));
          noise = (Math.random() - 0.5) * 0.06;
        }
        
        const baseline = 0.45;
        const ndvi = baseline + trend + seasonal + noise;
        
        data.push({
          t: t,
          doy: day,
          year: year,
          ndvi: Math.max(0, Math.min(1, ndvi)),
          trend: baseline + trend,
          seasonal: seasonal,
          noise: noise
        });
        doy.push(day);
      }
    }
    
    return data;
  }
  
  function extractPhenology(data, threshold) {
    // Use last complete year
    const lastYear = Math.max(...data.map(d => d.year));
    const yearData = data.filter(d => d.year === lastYear);
    
    if (yearData.length === 0) return null;
    
    // Find SOS (first crossing above threshold)
    let sos = null;
    for (let i = 0; i < yearData.length; i++) {
      if (yearData[i].ndvi > threshold) {
        sos = yearData[i].doy;
        break;
      }
    }
    
    // Find POS (maximum NDVI)
    let maxNDVI = -Infinity;
    let pos = null;
    for (let d of yearData) {
      if (d.ndvi > maxNDVI) {
        maxNDVI = d.ndvi;
        pos = d.doy;
      }
    }
    
    // Find EOS (last crossing above threshold)
    let eos = null;
    for (let i = yearData.length - 1; i >= 0; i--) {
      if (yearData[i].ndvi > threshold) {
        eos = yearData[i].doy;
        break;
      }
    }
    
    const gsl = (sos && eos) ? (eos - sos) : null;
    
    return {sos, pos, eos, gsl};
  }
  
  function computeTrend(data) {
    const n = data.length;
    const meanT = data.reduce((s, d) => s + d.t, 0) / n;
    const meanY = data.reduce((s, d) => s + d.ndvi, 0) / n;
    
    let num = 0, den = 0;
    for (let d of data) {
      num += (d.t - meanT) * (d.ndvi - meanY);
      den += (d.t - meanT) ** 2;
    }
    
    const slope = num / den;
    // Convert to NDVI/year
    const slopePerYear = slope * 365;
    
    return slopePerYear;
  }
  
  function movingAverage(data, window = 3) {
    const smoothed = [];
    const half = Math.floor(window / 2);
    
    for (let i = 0; i < data.length; i++) {
      let sum = 0, count = 0;
      for (let j = Math.max(0, i - half); j <= Math.min(data.length - 1, i + half); j++) {
        sum += data[j].ndvi;
        count++;
      }
      smoothed.push(sum / count);
    }
    
    return smoothed;
  }
  
  function render() {
    const data = generateTimeSeries(locationType, 3);
    const smoothed = movingAverage(data, 3);
    
    const pheno = extractPhenology(data, phenoThreshold);
    const trendSlope = computeTrend(data);
    
    // Update display
    document.getElementById('sos-doy').textContent = pheno.sos || '--';
    document.getElementById('pos-doy').textContent = pheno.pos || '--';
    document.getElementById('eos-doy').textContent = pheno.eos || '--';
    document.getElementById('gsl-days').textContent = pheno.gsl || '--';
    document.getElementById('trend-value').textContent = trendSlope.toFixed(4);
    
    // Prepare series
    const series = [];
    
    // Observed NDVI
    series.push({
      name: 'Observed NDVI',
      type: 'scatter',
      data: data.map(d => [d.t, d.ndvi]),
      symbolSize: 4,
      itemStyle: {color: '#95A5A6'}
    });
    
    if (showSmoothed) {
      series.push({
        name: 'Smoothed',
        type: 'line',
        data: data.map((d, i) => [d.t, smoothed[i]]),
        lineStyle: {color: '#3498DB', width: 2},
        showSymbol: false
      });
    }
    
    if (showTrend) {
      series.push({
        name: 'Trend',
        type: 'line',
        data: data.map(d => [d.t, d.trend]),
        lineStyle: {color: '#E74C3C', width: 2, type: 'dashed'},
        showSymbol: false
      });
    }
    
    if (showSeasonal) {
      series.push({
        name: 'Seasonal Component',
        type: 'line',
        data: data.map(d => [d.t, d.trend + d.seasonal]),
        lineStyle: {color: '#2ECC71', width: 2},
        showSymbol: false
      });
    }
    
    // Threshold line
    series.push({
      name: 'Phenology Threshold',
      type: 'line',
      data: [[0, phenoThreshold], [data[data.length-1].t, phenoThreshold]],
      lineStyle: {color: '#F39C12', width: 1, type: 'dotted'},
      showSymbol: false
    });
    
    // Mark phenology points (last year)
    if (pheno.sos) {
      const lastYear = Math.max(...data.map(d => d.year));
      const sosPoint = data.find(d => d.year === lastYear && d.doy >= pheno.sos);
      const posPoint = data.find(d => d.year === lastYear && d.doy >= pheno.pos);
      const eosPoint = data.find(d => d.year === lastYear && d.doy >= pheno.eos);
      
      if (sosPoint) {
        series.push({
          name: 'SOS',
          type: 'scatter',
          data: [[sosPoint.t, sosPoint.ndvi]],
          symbolSize: 10,
          itemStyle: {color: '#27AE60'},
          label: {show: true, formatter: 'SOS', position: 'top'}
        });
      }
      
      if (posPoint) {
        series.push({
          name: 'POS',
          type: 'scatter',
          data: [[posPoint.t, posPoint.ndvi]],
          symbolSize: 10,
          itemStyle: {color: '#8E44AD'},
          label: {show: true, formatter: 'POS', position: 'top'}
        });
      }
      
      if (eosPoint) {
        series.push({
          name: 'EOS',
          type: 'scatter',
          data: [[eosPoint.t, eosPoint.ndvi]],
          symbolSize: 10,
          itemStyle: {color: '#E67E22'},
          label: {show: true, formatter: 'EOS', position: 'top'}
        });
      }
    }
    
    const option = {
      title: {
        text: `NDVI Time Series (${locationType})`,
        left: 'center'
      },
      tooltip: {
        trigger: 'axis',
        axisPointer: {type: 'cross'}
      },
      legend: {
        data: series.map(s => s.name),
        top: 30,
        type: 'scroll'
      },
      grid: {
        left: 80,
        right: 40,
        top: 80,
        bottom: 60
      },
      xAxis: {
        type: 'value',
        name: 'Days from start',
        nameLocation: 'middle',
        nameGap: 30
      },
      yAxis: {
        type: 'value',
        name: 'NDVI',
        nameLocation: 'middle',
        nameGap: 50,
        min: 0,
        max: 1
      },
      series: series
    };
    
    chart.setOption(option, true);
  }
  
  document.getElementById('location-type').addEventListener('change', (e) => {
    locationType = e.target.value;
    render();
  });
  
  document.getElementById('show-trend').addEventListener('change', (e) => {
    showTrend = e.target.checked;
    render();
  });
  
  document.getElementById('show-seasonal').addEventListener('change', (e) => {
    showSeasonal = e.target.checked;
    render();
  });
  
  document.getElementById('show-smoothed').addEventListener('change', (e) => {
    showSmoothed = e.target.checked;
    render();
  });
  
  document.getElementById('pheno-threshold').addEventListener('input', (e) => {
    phenoThreshold = parseFloat(e.target.value);
    document.getElementById('pheno-threshold-val').textContent = phenoThreshold.toFixed(2);
    render();
  });
  
  render();
  
  window.addEventListener('resize', () => chart.resize());
})();
</script>
<p><strong>Try this:</strong> - <strong>Temperate forest:</strong> Strong seasonal cycle, single peak - <strong>Grassland:</strong> Similar but smaller amplitude - <strong>Tropical evergreen:</strong> Minimal seasonality (always green) - <strong>Cropland:</strong> Double-crop pattern (two peaks per year!) - <strong>Show trend:</strong> Red dashed line (long-term change) - <strong>Show seasonal:</strong> Green line (trend + seasonality) - <strong>Show smoothed:</strong> Blue line (noise reduced) - <strong>Adjust threshold:</strong> Changes SOS/EOS detection - <strong>Phenology markers:</strong> Green (SOS), Purple (POS), Orange (EOS)</p>
<p><strong>Key insight:</strong> Time series decomposition separates long-term trends from seasonal cycles, enabling climate change detection and phenology monitoring!</p>
<hr>
<h2 id="interpretation">6. Interpretation</h2>
<h3 id="climate-change-signals">Climate Change Signals</h3>
<p><strong>Global greening trend:</strong> - NDVI increased ~0.001-0.002/year (1982-2015) - Reasons: CO₂ fertilization, warmer temperatures, longer growing seasons - Arctic: Strongest greening (shrub expansion)</p>
<p><strong>Growing season extension:</strong> - SOS earlier (1-2 weeks in 40 years) - EOS later (1 week) - Net: +10-20 days GSL in northern latitudes</p>
<h3 id="drought-monitoring">Drought Monitoring</h3>
<p><strong>NDVI anomaly:</strong></p>
<p><span class="math display">A(t) = \text{NDVI}(t) - \text{NDVI}_{\text{climatology}}(t)</span></p>
<p>Where climatology = long-term average for that time of year.</p>
<p><strong>Negative anomaly</strong> = drought stress</p>
<p><strong>Example:</strong> 2012 US drought - NDVI anomaly &lt; -0.15 across Corn Belt - Early warning of crop failure</p>
<h3 id="agricultural-phenology">Agricultural Phenology</h3>
<p><strong>Crop calendars from satellites:</strong> - SOS = planting date - POS = peak vegetative growth - EOS = harvest date</p>
<p><strong>Applications:</strong> - Yield forecasting (early prediction) - Insurance claims (verify timing) - Double-cropping detection</p>
<hr>
<h2 id="what-could-go-wrong">7. What Could Go Wrong?</h2>
<h3 id="cloud-contamination">Cloud Contamination</h3>
<p><strong>Clouds reduce NDVI</strong> (appear as low values).</p>
<p><strong>Spurious phenology:</strong> - Cloudy spring → delayed SOS (false) - Need cloud masking</p>
<p><strong>Solutions:</strong> - Composite images (maximum NDVI in period) - Cloud screening (quality flags) - Gap-filling interpolation</p>
<h3 id="missing-data">Missing Data</h3>
<p><strong>Landsat:</strong> 16-day repeat but clouds may leave gaps.</p>
<p><strong>Irregular time series</strong> → difficult to analyze.</p>
<p><strong>Solutions:</strong> - Interpolation (linear, spline) - Harmonic fitting (smooth through gaps) - Data fusion (combine Landsat + Sentinel)</p>
<h3 id="sensor-drift">Sensor Drift</h3>
<p><strong>Long-term sensors</strong> (AVHRR, MODIS) degrade over time.</p>
<p><strong>Calibration drift</strong> → false trend.</p>
<p><strong>Solution:</strong> - Cross-calibration between sensors - Atmospheric correction updates - Use surface reflectance products</p>
<h3 id="mixed-land-cover">Mixed Land Cover</h3>
<p><strong>Pixel contains multiple types</strong> (e.g., 50% forest, 50% grass).</p>
<p><strong>Phenology represents blend</strong> → hard to interpret.</p>
<p><strong>Solution:</strong> - Use finer resolution - Classify first, then analyze per class - Sub-pixel unmixing</p>
<hr>
<h2 id="extension-timesat">8. Extension: TIMESAT</h2>
<p><strong>Software package</strong> for time series processing.</p>
<p><strong>Functions:</strong> - Gap-filling (interpolation) - Smoothing (Savitzky-Golay, asymmetric Gaussian) - Phenology extraction (multiple methods) - Visualization</p>
<p><strong>Three fitting methods:</strong> 1. <strong>Asymmetric Gaussian:</strong> Separate rise/fall curves 2. <strong>Double logistic:</strong> S-curves for green-up/senescence 3. <strong>Savitzky-Golay filter:</strong> Polynomial smoothing</p>
<p><strong>Outputs:</strong> - Start/end of season - Length of season - Base/peak/amplitude - Small/large integrals (productivity metrics)</p>
<p><strong>Widely used</strong> in operational phenology monitoring.</p>
<hr>
<h2 id="math-refresher-fourier-series">9. Math Refresher: Fourier Series</h2>
<h3 id="periodic-function-decomposition">Periodic Function Decomposition</h3>
<p><strong>Any periodic function</strong> with period <span class="math inline">P</span> can be represented as:</p>
<p><span class="math display">f(t) = a_0 + \sum_{k=1}^{\infty} \left[a_k\cos(k\omega t) + b_k\sin(k\omega t)\right]</span></p>
<p>Where <span class="math inline">\omega = 2\pi / P</span> (fundamental frequency).</p>
<p><strong>Coefficients:</strong></p>
<p><span class="math display">a_0 = \frac{1}{P}\int_0^P f(t)\,dt</span></p>
<p><span class="math display">a_k = \frac{2}{P}\int_0^P f(t)\cos(k\omega t)\,dt</span></p>
<p><span class="math display">b_k = \frac{2}{P}\int_0^P f(t)\sin(k\omega t)\,dt</span></p>
<h3 id="application-to-ndvi">Application to NDVI</h3>
<p><strong>For annual cycle (<span class="math inline">P = 365</span> days):</strong></p>
<p><strong>First harmonic (k=1):</strong> Annual component</p>
<p><strong>Second harmonic (k=2):</strong> Bi-annual (captures double-cropping)</p>
<p><strong>Typically:</strong> 1-3 harmonics sufficient for most vegetation.</p>
<p><strong>Amplitude of harmonic k:</strong></p>
<p><span class="math display">A_k = \sqrt{a_k^2 + b_k^2}</span></p>
<p><strong>Phase (timing of peak):</strong></p>
<p><span class="math display">\phi_k = \arctan(b_k / a_k)</span></p>
<hr>
<h2 id="summary">Summary</h2>
<ul>
<li><strong>Time series analysis</strong> decomposes observations into trend, seasonality, and noise</li>
<li><strong>Phenological metrics:</strong> Start of season (SOS), peak (POS), end (EOS), growing season length (GSL)</li>
<li><strong>Harmonic analysis:</strong> Models seasonality using sine/cosine functions</li>
<li><strong>Trend extraction:</strong> Linear regression to detect long-term change</li>
<li><strong>Smoothing filters:</strong> Moving average or Savitzky-Golay to reduce noise</li>
<li><strong>Applications:</strong> Climate change detection, drought monitoring, crop calendars, forest health</li>
<li><strong>Challenges:</strong> Clouds, missing data, sensor drift, mixed pixels</li>
<li><strong>TIMESAT:</strong> Standard software for operational phenology extraction</li>
<li><strong>Global observations:</strong> Growing season lengthening, Arctic greening, NDVI anomalies indicate drought</li>
<li>Critical for understanding vegetation dynamics and climate change impacts</li>
</ul>
<hr>


<footer class="wayward-footer">
  <div class="wayward-footer__inner">
    <div class="wayward-footer__brand">
      <div class="wayward-footer__logo">WaywardHouse<span>.</span></div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wayward-footer__group" aria-labelledby="footer-reading">
      <h2 id="footer-reading">Reading</h2>
      <a href="../../articles/">Articles</a>
      <a href="../../learn/">Library</a>
      <a href="../../learn/computational-geography/core/">↳ Comp Geo Book</a>
      <a href="../../archive.html">Archive</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-site">
      <h2 id="footer-site">Site</h2>
      <a href="../../start-here.html">Start Here</a>
      <a href="../../about.html">About</a>
      <a href="../../contact.html">Contact</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-resources">
      <h2 id="footer-resources">Resources</h2>
      <a href="../../topics/">All Topics</a>
      <a href="../../privacy.html">Privacy Policy</a>
      <a href="../../terms.html">Terms of Use</a>
    </nav>
  </div>
</footer>

<script type="module" src="../../assets/dist/main.js"></script>
<script type="module" src="../../assets/js/core.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wayward\.house");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>