<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-02-27">
<meta name="description" content="What minerals compose this rock? What chemicals are in these plants? Hyperspectral imaging captures hundreds of narrow spectral bands, enabling material identification through spectral signatures. This model derives absorption feature analysis, implements spectral unmixing algorithms, and shows how to map minerals, vegetation biochemistry, and water quality from hyperspectral data.">

<title>Hyperspectral Imaging – Computational Geography</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-734cb40618f438257b19a1e532635a32.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script>
  (function () {
    document.documentElement.dataset.theme = 'light';
    document.documentElement.dataset.brand = 'wayward';
    try {
      localStorage.removeItem('theme');
    } catch (err) {
      void err;
    }
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-math tag-hash-viz">


<header id="title-block-header">
<h1 class="title"><span class="chapter-title">Hyperspectral Imaging</span></h1>
<p class="subtitle">Hundreds of spectral bands reveal material composition and biochemical properties</p>

<p class="date">2026-02-27</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#before-you-start" id="toc-before-you-start">Before You Start</a></li>
  <li><a href="#the-question" id="toc-the-question">1. The Question</a></li>
  <li><a href="#the-conceptual-model" id="toc-the-conceptual-model">2. The Conceptual Model</a>
  <ul>
  <li><a href="#spectral-signatures" id="toc-spectral-signatures">Spectral Signatures</a></li>
  <li><a href="#spectral-libraries" id="toc-spectral-libraries">Spectral Libraries</a></li>
  <li><a href="#imaging-spectrometer" id="toc-imaging-spectrometer">Imaging Spectrometer</a></li>
  </ul></li>
  <li><a href="#building-the-mathematical-model" id="toc-building-the-mathematical-model">3. Building the Mathematical Model</a>
  <ul>
  <li><a href="#spectral-unmixing" id="toc-spectral-unmixing">Spectral Unmixing</a></li>
  <li><a href="#absorption-feature-depth" id="toc-absorption-feature-depth">Absorption Feature Depth</a></li>
  <li><a href="#spectral-angle-mapper-sam" id="toc-spectral-angle-mapper-sam">Spectral Angle Mapper (SAM)</a></li>
  <li><a href="#principal-component-analysis-pca" id="toc-principal-component-analysis-pca">Principal Component Analysis (PCA)</a></li>
  </ul></li>
  <li><a href="#worked-example-by-hand" id="toc-worked-example-by-hand">4. Worked Example by Hand</a>
  <ul>
  <li><a href="#solution" id="toc-solution">Solution</a></li>
  </ul></li>
  <li><a href="#computational-implementation" id="toc-computational-implementation">5. Computational Implementation</a></li>
  <li><a href="#interpretation" id="toc-interpretation">6. Interpretation</a>
  <ul>
  <li><a href="#mineral-mapping" id="toc-mineral-mapping">Mineral Mapping</a></li>
  <li><a href="#precision-agriculture" id="toc-precision-agriculture">Precision Agriculture</a></li>
  <li><a href="#water-quality" id="toc-water-quality">Water Quality</a></li>
  </ul></li>
  <li><a href="#what-could-go-wrong" id="toc-what-could-go-wrong">7. What Could Go Wrong?</a>
  <ul>
  <li><a href="#atmospheric-interference" id="toc-atmospheric-interference">Atmospheric Interference</a></li>
  <li><a href="#endmember-variability" id="toc-endmember-variability">Endmember Variability</a></li>
  <li><a href="#dimensionality-curse" id="toc-dimensionality-curse">Dimensionality Curse</a></li>
  <li><a href="#non-linear-mixing" id="toc-non-linear-mixing">Non-Linear Mixing</a></li>
  </ul></li>
  <li><a href="#extension-derivative-spectroscopy" id="toc-extension-derivative-spectroscopy">8. Extension: Derivative Spectroscopy</a></li>
  <li><a href="#math-refresher-vector-spaces-and-similarity" id="toc-math-refresher-vector-spaces-and-similarity">9. Math Refresher: Vector Spaces and Similarity</a>
  <ul>
  <li><a href="#dot-product" id="toc-dot-product">Dot Product</a></li>
  <li><a href="#cosine-similarity" id="toc-cosine-similarity">Cosine Similarity</a></li>
  <li><a href="#euclidean-distance" id="toc-euclidean-distance">Euclidean Distance</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary">Summary</a></li>
  </ul>
</nav>
<p>In the late 1990s, NASA’s Jet Propulsion Laboratory began flying the AVIRIS spectrometer over the Cuprite mining district of Nevada — a classic hydrothermal alteration zone with exposures of alunite, kaolinite, buddingtonite, and other minerals that are spectroscopically distinctive but visually similar. The 224-band images produced by AVIRIS, covering wavelengths from 400 to 2500 nm in 10 nm increments, could distinguish these minerals from aircraft altitude as clearly as a field geologist with a spectrometer could distinguish them in hand sample. Exploration geologists took note. Within a decade, hyperspectral survey had become a standard tool for regional mineral mapping, capable of covering thousands of square kilometres in a few days at a fraction of the cost of ground survey.</p>
<p>A standard satellite or aircraft sensor might capture 4 to 12 spectral bands. Hyperspectral imaging captures 100 to 400 narrow bands, sampling reflected sunlight essentially continuously from the visible through the shortwave infrared. The result is not a colour image but a spectrum for every pixel — a spectral fingerprint that encodes the chemical composition of the surface. Different minerals have different absorption features at characteristic wavelengths: the iron oxide hematite absorbs at 490 nm; kaolinite shows absorption doublets at 1400 and 2200 nm; water absorbs at 1400 and 1900 nm. These features can be identified by comparing pixel spectra to reference libraries, or extracted using spectral unmixing — the algebraic decomposition of each pixel spectrum into fractional contributions from end-member spectra. This model derives the spectral signature physics, implements absorption feature analysis, and shows how linear unmixing maps sub-pixel composition across a scene.</p>
<h2 id="before-you-start" class="anchored">Before You Start</h2>
<p>This chapter introduces a lot of spectral language, but the central idea is simple: each pixel contains a spectrum, and that spectrum carries chemical information. When we unmix a pixel, we are asking what combination of known spectral end-members could plausibly have produced the measured signal.</p>
<h2 id="the-question" class="anchored">1. The Question</h2>
<p>Can we identify minerals from orbit using reflected sunlight?</p>
<p><strong>Hyperspectral imaging</strong> captures continuous spectra across hundreds of narrow bands.</p>
<p><strong>Comparison:</strong></p>
<p><strong>Multispectral (Landsat, Sentinel-2):</strong> - 8-12 broad bands - Band width: 50-200 nm - Coarse spectral sampling</p>
<p><strong>Hyperspectral (AVIRIS, EnMAP, PRISMA):</strong> - 100-400+ narrow bands - Band width: 5-10 nm - Fine spectral sampling - Continuous spectrum 400-2500 nm</p>
<p><strong>Key advantage:</strong></p>
<p>Narrow bands capture diagnostic absorption features that reveal: - Mineral composition (geology) - Vegetation biochemistry (chlorophyll, water, nitrogen) - Water quality (sediment, algae, dissolved organic matter) - Urban materials (roof types, pavement)</p>
<p><strong>Applications:</strong> - Mineral exploration (ore deposits) - Precision agriculture (crop health, nutrient status) - Environmental monitoring (water quality, invasive species) - Geological mapping (lithology discrimination)</p>
<hr>
<h2 id="the-conceptual-model" class="anchored">2. The Conceptual Model</h2>
<h3 id="spectral-signatures" class="anchored">Spectral Signatures</h3>
<p><strong>Reflectance spectrum:</strong></p>
<p><span class="math display">\rho(\lambda) = \frac{L_{\uparrow}(\lambda)}{L_{\downarrow}(\lambda)}</span></p>
<p>Where: - <span class="math inline">\rho(\lambda)</span> = spectral reflectance (0-1) - <span class="math inline">\lambda</span> = wavelength (nm) - <span class="math inline">L_{\uparrow}</span> = upwelling radiance - <span class="math inline">L_{\downarrow}</span> = downwelling irradiance</p>
<p><strong>Absorption features:</strong></p>
<p>Materials absorb specific wavelengths due to: - Electronic transitions (UV-visible, 400-700 nm) - Vibrational overtones (near-infrared, 700-1300 nm) - Molecular vibrations (shortwave infrared, 1300-2500 nm)</p>
<p><strong>Example - vegetation:</strong> - 680 nm: Chlorophyll absorption (red) - 750-900 nm: High reflectance (near-infrared plateau) - 1400, 1900 nm: Water absorption - 2200 nm: Cellulose/lignin absorption</p>
<p><strong>Example - minerals:</strong> - Iron oxides: Absorption 400-700 nm - Hydroxyl minerals (clays): 1400, 2200 nm - Carbonates: 2300-2350 nm</p>
<h3 id="spectral-libraries" class="anchored">Spectral Libraries</h3>
<p><strong>Reference spectra</strong> measured in laboratory:</p>
<p><strong>USGS Spectral Library:</strong> - 1400+ materials - Minerals, rocks, soils - Vegetation, water - Measured at high resolution</p>
<p><strong>Use:</strong> Compare image spectra to library for identification</p>
<h3 id="imaging-spectrometer" class="anchored">Imaging Spectrometer</h3>
<p><strong>Data structure:</strong></p>
<p><strong>Hyperspectral cube:</strong> - x dimension: spatial (pixels across) - y dimension: spatial (pixels down) - z dimension: spectral (wavelengths)</p>
<p><strong>Data volume:</strong></p>
<p>1000 × 1000 pixels × 200 bands = 200 million values</p>
<p><strong>Each pixel = complete spectrum</strong> (hundreds of measurements)</p>
<figure class="cg-ill">
<div class="cg-ill__frame" data-markdown="1">
<div class="cg-ill__eyebrow">
Hyperspectral Structure
</div>
<h3 class="cg-ill__title anchored">
A Hyperspectral Image Is A Cube Of Spectra, Not Just A Picture
</h3>
<p class="cg-ill__lede">
The key object in hyperspectral remote sensing is the cube: two spatial dimensions plus one spectral dimension. Every pixel carries a full reflectance curve that can be compared with materials in a spectral library.
</p>
<div class="cg-ill__grid cg-ill__grid--2">
<div class="cg-ill__card">
<svg viewbox="0 0 560 300" role="img" aria-label="Hyperspectral data cube with one selected pixel linked to a reflectance spectrum">
<rect x="0" y="0" width="560" height="300" rx="22" fill="#eef3f8"></rect> <polygon points="110,82 278,82 336,126 168,126" fill="#d6e0ea" stroke="#72879a" stroke-width="3"></polygon> <polygon points="110,82 168,126 168,246 110,204" fill="#c7d4e0" stroke="#72879a" stroke-width="3"></polygon> <polygon points="168,126 336,126 336,246 168,246" fill="#e6edf4" stroke="#72879a" stroke-width="3"></polygon> <line x1="206" y1="126" x2="206" y2="246" stroke="#b1c0ce" stroke-width="2"></line> <line x1="244" y1="126" x2="244" y2="246" stroke="#b1c0ce" stroke-width="2"></line> <line x1="282" y1="126" x2="282" y2="246" stroke="#b1c0ce" stroke-width="2"></line> <line x1="168" y1="156" x2="336" y2="156" stroke="#b1c0ce" stroke-width="2"></line> <line x1="168" y1="186" x2="336" y2="186" stroke="#b1c0ce" stroke-width="2"></line> <line x1="168" y1="216" x2="336" y2="216" stroke="#b1c0ce" stroke-width="2"></line> <line x1="148" y1="108" x2="206" y2="152" stroke="#b1c0ce" stroke-width="2"></line> <line x1="186" y1="108" x2="244" y2="152" stroke="#b1c0ce" stroke-width="2"></line> <line x1="224" y1="108" x2="282" y2="152" stroke="#b1c0ce" stroke-width="2"></line> <rect x="236" y="178" width="38" height="38" fill="#f4d35e" stroke="#9f7530" stroke-width="3"></rect> <text x="94" y="70" font-size="17" fill="#30495c" font-weight="700">x</text> <text x="146" y="256" font-size="17" fill="#30495c" font-weight="700">y</text> <text x="346" y="120" font-size="17" fill="#30495c" font-weight="700">wavelength</text> <line x1="274" y1="194" x2="420" y2="194" stroke="#a64b2a" stroke-width="5" stroke-dasharray="8 7"></line> <polygon points="420,194 406,186 406,202" fill="#a64b2a"></polygon> <rect x="424" y="108" width="96" height="126" rx="14" fill="#ffffff" stroke="#8aa0b3" stroke-width="3"></rect> <line x1="438" y1="218" x2="508" y2="218" stroke="#7d8ea0" stroke-width="2"></line> <line x1="438" y1="124" x2="438" y2="218" stroke="#7d8ea0" stroke-width="2"></line> <path d="M444 194 C456 166, 470 174, 482 138 C490 118, 498 128, 506 152" fill="none" stroke="#2a9d8f" stroke-width="4"></path> <text x="434" y="100" font-size="16" fill="#30495c" font-weight="700">one pixel spectrum</text> <text x="426" y="252" font-size="16" fill="#30495c">selected pixel -&gt; reflectance curve</text>
</svg>
</div>
<div class="cg-ill__card">
<h4 class="anchored">
What to remember
</h4>
<ul>
<li>
A normal image stores a few channels per pixel; a hyperspectral image stores a long spectrum per pixel.
</li>
<li>
The cube’s horizontal dimensions tell you <em>where</em>; the spectral dimension tells you <em>what kind of material</em>.
</li>
<li>
Absorption features in the curve are what let you distinguish vegetation, minerals, water, or soil.
</li>
<li>
Spectral libraries matter because identification is really a comparison between measured curves and known reference curves.
</li>
</ul>
</div>
</div>
</div>
</figure>
<hr>
<h2 id="building-the-mathematical-model" class="anchored">3. Building the Mathematical Model</h2>
<h3 id="spectral-unmixing" class="anchored">Spectral Unmixing</h3>
<p><strong>Mixed pixel problem:</strong></p>
<p>Pixel contains multiple materials (vegetation + soil, multiple minerals)</p>
<p><strong>Linear mixing model:</strong></p>
<p><span class="math display">\rho(\lambda) = \sum_{i=1}^{n} f_i \rho_i(\lambda) + \varepsilon(\lambda)</span></p>
<p>Where: - <span class="math inline">f_i</span> = fractional abundance of endmember <span class="math inline">i</span> - <span class="math inline">\rho_i(\lambda)</span> = reflectance spectrum of pure endmember <span class="math inline">i</span> - <span class="math inline">\varepsilon(\lambda)</span> = residual error</p>
<p><strong>Constraints:</strong></p>
<p><span class="math display">\sum_{i=1}^{n} f_i = 1</span> (fractions sum to 1)</p>
<p><span class="math display">f_i \geq 0</span> (non-negative fractions)</p>
<p><strong>Matrix formulation:</strong></p>
<p><span class="math display">\mathbf{r} = \mathbf{E} \mathbf{f} + \boldsymbol{\varepsilon}</span></p>
<p>Where: - <span class="math inline">\mathbf{r}</span> = measured spectrum (m × 1 vector, m bands) - <span class="math inline">\mathbf{E}</span> = endmember matrix (m × n, n endmembers) - <span class="math inline">\mathbf{f}</span> = abundance vector (n × 1)</p>
<p><strong>Solution (least squares):</strong></p>
<p><span class="math display">\mathbf{f} = (\mathbf{E}^T\mathbf{E})^{-1}\mathbf{E}^T\mathbf{r}</span></p>
<p>Subject to non-negativity and sum-to-one constraints.</p>
<h3 id="absorption-feature-depth" class="anchored">Absorption Feature Depth</h3>
<p><strong>Continuum removal:</strong></p>
<ol type="1">
<li>Fit continuum (straight line or convex hull) to spectrum</li>
<li>Normalize spectrum by continuum</li>
<li>Measure absorption depth</li>
</ol>
<p><strong>Continuum-removed reflectance:</strong></p>
<p><span class="math display">R_{CR}(\lambda) = \frac{\rho(\lambda)}{\rho_{continuum}(\lambda)}</span></p>
<p><strong>Absorption depth:</strong></p>
<p><span class="math display">D = 1 - \min(R_{CR}(\lambda))</span></p>
<p><strong>Example - 2200 nm clay feature:</strong></p>
<p>If minimum <span class="math inline">R_{CR} = 0.75</span>, then <span class="math inline">D = 0.25</span> (25% absorption)</p>
<h3 id="spectral-angle-mapper-sam" class="anchored">Spectral Angle Mapper (SAM)</h3>
<p><strong>Similarity metric</strong> between spectra:</p>
<p><span class="math display">\alpha = \arccos\left(\frac{\mathbf{r}_1 \cdot \mathbf{r}_2}{||\mathbf{r}_1|| \cdot ||\mathbf{r}_2||}\right)</span></p>
<p>Where: - <span class="math inline">\alpha</span> = spectral angle (radians or degrees) - Small angle → similar spectra</p>
<p><strong>Classification:</strong></p>
<p>Compare pixel spectrum to reference library spectra, assign to closest match (smallest angle).</p>
<p><strong>Insensitive to illumination</strong> (brightness variations) - measures shape, not magnitude.</p>
<h3 id="principal-component-analysis-pca" class="anchored">Principal Component Analysis (PCA)</h3>
<p><strong>Dimensionality reduction:</strong></p>
<p>Transform 200 bands → 5-10 principal components capturing most variance.</p>
<p><strong>Covariance matrix:</strong></p>
<p><span class="math display">\mathbf{C} = \frac{1}{n-1}\mathbf{X}^T\mathbf{X}</span></p>
<p><strong>Eigenvalue decomposition:</strong></p>
<p><span class="math display">\mathbf{C}\mathbf{v}_i = \lambda_i\mathbf{v}_i</span></p>
<p><strong>Principal components:</strong></p>
<p><span class="math display">PC_i = \mathbf{X}\mathbf{v}_i</span></p>
<p><strong>Variance explained:</strong></p>
<p><span class="math display">\text{Variance}_i = \frac{\lambda_i}{\sum \lambda_i}</span></p>
<p><strong>First few PCs</strong> typically capture &gt;95% variance.</p>
<hr>
<h2 id="worked-example-by-hand" class="anchored">4. Worked Example by Hand</h2>
<p><strong>Problem:</strong> Unmix pixel containing vegetation and soil.</p>
<p><strong>Measured spectrum (simplified, 5 wavelengths):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>λ (nm)</th>
<th>ρ_measured</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>550</td>
<td>0.08</td>
</tr>
<tr class="even">
<td>670</td>
<td>0.06</td>
</tr>
<tr class="odd">
<td>800</td>
<td>0.35</td>
</tr>
<tr class="even">
<td>1600</td>
<td>0.25</td>
</tr>
<tr class="odd">
<td>2200</td>
<td>0.22</td>
</tr>
</tbody>
</table>
<p><strong>Endmember spectra:</strong></p>
<p><strong>Vegetation:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>λ (nm)</th>
<th>ρ_veg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>550</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>670</td>
<td>0.04</td>
</tr>
<tr class="odd">
<td>800</td>
<td>0.50</td>
</tr>
<tr class="even">
<td>1600</td>
<td>0.35</td>
</tr>
<tr class="odd">
<td>2200</td>
<td>0.30</td>
</tr>
</tbody>
</table>
<p><strong>Soil:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>λ (nm)</th>
<th>ρ_soil</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>550</td>
<td>0.06</td>
</tr>
<tr class="even">
<td>670</td>
<td>0.08</td>
</tr>
<tr class="odd">
<td>800</td>
<td>0.20</td>
</tr>
<tr class="even">
<td>1600</td>
<td>0.15</td>
</tr>
<tr class="odd">
<td>2200</td>
<td>0.14</td>
</tr>
</tbody>
</table>
<p>Find fractional abundances <span class="math inline">f_{\text{veg}}</span> and <span class="math inline">f_{\text{soil}}</span>.</p>
<h3 id="solution" class="anchored">Solution</h3>
<p><strong>Linear mixing model:</strong></p>
<p><span class="math display">\rho(\lambda) = f_{\text{veg}} \rho_{\text{veg}}(\lambda) + f_{\text{soil}} \rho_{\text{soil}}(\lambda)</span></p>
<p>With constraint: <span class="math inline">f_{\text{veg}} + f_{\text{soil}} = 1</span></p>
<p><strong>Substitute constraint:</strong> <span class="math inline">f_{\text{soil}} = 1 - f_{\text{veg}}</span></p>
<p><span class="math display">\rho(\lambda) = f_{\text{veg}} \rho_{\text{veg}}(\lambda) + (1-f_{\text{veg}}) \rho_{\text{soil}}(\lambda)</span></p>
<p><span class="math display">\rho(\lambda) = f_{\text{veg}} (\rho_{\text{veg}}(\lambda) - \rho_{\text{soil}}(\lambda)) + \rho_{\text{soil}}(\lambda)</span></p>
<p><strong>Solve using one wavelength (800 nm):</strong></p>
<p><span class="math display">0.35 = f_{\text{veg}}(0.50 - 0.20) + 0.20</span></p>
<p><span class="math display">0.35 = 0.30 f_{\text{veg}} + 0.20</span></p>
<p><span class="math display">0.15 = 0.30 f_{\text{veg}}</span></p>
<p><span class="math display">f_{\text{veg}} = 0.50</span></p>
<p><span class="math display">f_{\text{soil}} = 0.50</span></p>
<p><strong>Verify at 670 nm:</strong></p>
<p><span class="math display">\rho_{pred} = 0.50(0.04) + 0.50(0.08) = 0.02 + 0.04 = 0.06</span> ✓</p>
<p><strong>Verify at 2200 nm:</strong></p>
<p><span class="math display">\rho_{pred} = 0.50(0.30) + 0.50(0.14) = 0.15 + 0.07 = 0.22</span> ✓</p>
<p><strong>Result:</strong> Pixel is 50% vegetation, 50% soil.</p>
<p><strong>Note:</strong> Using all bands simultaneously with least squares gives more robust estimate.</p>
<hr>
<h2 id="computational-implementation" class="anchored">5. Computational Implementation</h2>
<p>Below is an interactive hyperspectral analysis tool.</p>
<div class="viz-container" id="hyper-viz">
<div class="controls">
<label>
Vegetation fraction:
<input type="range" id="veg-frac" min="0" max="100" step="5" value="50">
<span id="veg-val">50</span>%
</label>
<label>
Add noise:
<input type="checkbox" id="add-noise">
</label>
<label>
Show endmembers:
<input type="checkbox" id="show-endmembers" checked="">
</label>
<label>
Analysis method:
<select id="analysis-method">
<option value="mixture">Linear unmixing</option>
<option value="sam">Spectral Angle Mapper</option>
<option value="absorption">Absorption features</option>
</select>
</label>
<div class="hyper-info">
<p><strong>Estimated vegetation:</strong> <span id="est-veg">--</span>%</p>
<p><strong>Estimated soil:</strong> <span id="est-soil">--</span>%</p>
<p><strong>RMSE:</strong> <span id="rmse">--</span></p>
<p><strong>Classification:</strong> <span id="classification">--</span></p>
</div>
</div>
<div id="hyper-canvas-container">
<canvas id="hyper-canvas" width="700" height="400" style="border: 1px solid #ddd;"></canvas>
</div>
</div>

<script type="module">
await new Promise(resolve => {
const checkECharts = () => {
if (typeof echarts !== 'undefined') resolve();
else setTimeout(checkECharts, 50);
};
checkECharts();
});

(function() {
const chart = echarts.init(document.getElementById('hyper-canvas'));
  
let vegFrac = 0.5;
let addNoise = false;
let showEndmembers = true;
let analysisMethod = 'mixture';
  
// Spectral libraries (simplified)
const wavelengths = [450, 550, 670, 750, 850, 1000, 1200, 1400, 1600, 1900, 2100, 2200, 2400];
  
const vegSpectrum = [0.04, 0.10, 0.04, 0.15, 0.50, 0.48, 0.45, 0.30, 0.35, 0.20, 0.28, 0.30, 0.25];
const soilSpectrum = [0.06, 0.08, 0.10, 0.12, 0.20, 0.22, 0.25, 0.23, 0.28, 0.24, 0.30, 0.32, 0.35];
const waterSpectrum = [0.05, 0.04, 0.03, 0.02, 0.01, 0.01, 0.01, 0.005, 0.005, 0.003, 0.002, 0.002, 0.001];
  
function generateMixedSpectrum(fVeg) {
const fSoil = 1 - fVeg;
const mixed = [];
    
for (let i = 0; i < wavelengths.length; i++) {
let val = fVeg * vegSpectrum[i] + fSoil * soilSpectrum[i];
if (addNoise) {
val += (Math.random() - 0.5) * 0.02;
}
mixed.push(Math.max(0, Math.min(1, val)));
}
    
return mixed;
}
  
function unmixSpectrum(mixed) {
// Simple two-endmember unmixing using NIR band (850 nm, index 4)
const idx = 4;
const measNIR = mixed[idx];
const vegNIR = vegSpectrum[idx];
const soilNIR = soilSpectrum[idx];
    
const fVegEst = (measNIR - soilNIR) / (vegNIR - soilNIR);
const fVegClamped = Math.max(0, Math.min(1, fVegEst));
    
return {
vegFrac: fVegClamped,
soilFrac: 1 - fVegClamped
};
}
  
function spectralAngleMapper(mixed) {
// Calculate angle with vegetation and soil spectra
let dotVeg = 0, dotSoil = 0;
let normMixed = 0, normVeg = 0, normSoil = 0;
    
for (let i = 0; i < wavelengths.length; i++) {
dotVeg += mixed[i] * vegSpectrum[i];
dotSoil += mixed[i] * soilSpectrum[i];
normMixed += mixed[i] * mixed[i];
normVeg += vegSpectrum[i] * vegSpectrum[i];
normSoil += soilSpectrum[i] * soilSpectrum[i];
}
    
normMixed = Math.sqrt(normMixed);
normVeg = Math.sqrt(normVeg);
normSoil = Math.sqrt(normSoil);
    
const angleVeg = Math.acos(dotVeg / (normMixed * normVeg)) * 180 / Math.PI;
const angleSoil = Math.acos(dotSoil / (normMixed * normSoil)) * 180 / Math.PI;
    
return angleVeg < angleSoil ? 'Vegetation-dominated' : 'Soil-dominated';
}
  
function calculateRMSE(mixed, estimated) {
const fVeg = estimated.vegFrac;
const fSoil = estimated.soilFrac;
    
let sumSqErr = 0;
for (let i = 0; i < wavelengths.length; i++) {
const pred = fVeg * vegSpectrum[i] + fSoil * soilSpectrum[i];
sumSqErr += (mixed[i] - pred) ** 2;
}
    
return Math.sqrt(sumSqErr / wavelengths.length);
}
  
function render() {
const mixed = generateMixedSpectrum(vegFrac);
const estimated = unmixSpectrum(mixed);
const rmse = calculateRMSE(mixed, estimated);
const samClass = spectralAngleMapper(mixed);
    
document.getElementById('est-veg').textContent = (estimated.vegFrac * 100).toFixed(1);
document.getElementById('est-soil').textContent = (estimated.soilFrac * 100).toFixed(1);
document.getElementById('rmse').textContent = rmse.toFixed(4);
document.getElementById('classification').textContent = samClass;
    
const series = [];
    
if (showEndmembers) {
series.push({
name: 'Vegetation (pure)',
type: 'line',
data: wavelengths.map((w, i) => [w, vegSpectrum[i]]),
lineStyle: {color: '#2E7D32', width: 2, type: 'dashed'},
showSymbol: false
});
      
series.push({
name: 'Soil (pure)',
type: 'line',
data: wavelengths.map((w, i) => [w, soilSpectrum[i]]),
lineStyle: {color: '#8D6E63', width: 2, type: 'dashed'},
showSymbol: false
});
}
    
series.push({
name: 'Measured spectrum',
type: 'line',
data: wavelengths.map((w, i) => [w, mixed[i]]),
lineStyle: {color: '#1976D2', width: 3},
symbolSize: 8,
itemStyle: {color: '#1976D2'}
});
    
// Reconstructed spectrum
const reconstructed = wavelengths.map((w, i) => {
return [w, estimated.vegFrac * vegSpectrum[i] + estimated.soilFrac * soilSpectrum[i]];
});
    
series.push({
name: 'Unmixed (reconstructed)',
type: 'line',
data: reconstructed,
lineStyle: {color: '#E91E63', width: 2, type: 'dotted'},
showSymbol: false
});
    
// Mark key absorption features
series.push({
name: 'Chlorophyll absorption',
type: 'scatter',
data: [[670, mixed[2]]],
symbolSize: 15,
itemStyle: {color: '#F44336'},
label: {
show: true,
formatter: '670nm\nChl',
position: 'top',
fontSize: 10
}
});
    
series.push({
name: 'NIR plateau',
type: 'scatter',
data: [[850, mixed[4]]],
symbolSize: 15,
itemStyle: {color: '#4CAF50'},
label: {
show: true,
formatter: '850nm\nNIR',
position: 'top',
fontSize: 10
}
});
    
const option = {
title: {
text: 'Hyperspectral Reflectance Spectrum',
left: 'center'
},
tooltip: {
trigger: 'axis',
axisPointer: {type: 'cross'}
},
legend: {
data: series.map(s => s.name),
top: 30,
type: 'scroll'
},
grid: {
left: 80,
right: 40,
top: 80,
bottom: 60
},
xAxis: {
type: 'value',
name: 'Wavelength (nm)',
nameLocation: 'middle',
nameGap: 30,
min: 400,
max: 2500
},
yAxis: {
type: 'value',
name: 'Reflectance',
nameLocation: 'middle',
nameGap: 50,
min: 0,
max: 0.6
},
series: series
};
    
chart.setOption(option, true);
}
  
document.getElementById('veg-frac').addEventListener('input', (e) => {
vegFrac = parseFloat(e.target.value) / 100;
document.getElementById('veg-val').textContent = e.target.value;
render();
});
  
document.getElementById('add-noise').addEventListener('change', (e) => {
addNoise = e.target.checked;
render();
});
  
document.getElementById('show-endmembers').addEventListener('change', (e) => {
showEndmembers = e.target.checked;
render();
});
  
document.getElementById('analysis-method').addEventListener('change', (e) => {
analysisMethod = e.target.value;
render();
});
  
render();
  
window.addEventListener('resize', () => chart.resize());
})();
</script>
<p><strong>Observations:</strong> - Green dashed line shows pure vegetation spectrum with strong NIR reflectance - Brown dashed line shows pure soil spectrum with more uniform response - Blue line with points is measured mixed spectrum - Pink dotted line is reconstructed spectrum from unmixing - Red marker at 670 nm shows chlorophyll absorption feature - Green marker at 850 nm shows NIR plateau characteristic of vegetation - Unmixing algorithm estimates component fractions from spectral shape - Adding noise degrades unmixing accuracy but algorithm remains robust - RMSE quantifies reconstruction quality</p>
<p><strong>Key insights:</strong> - Vegetation has distinctive spectral signature with red absorption and NIR reflectance - Mixed pixels can be decomposed into constituent materials - Narrow bands enable precise absorption feature measurement - Spectral libraries provide reference signatures for identification</p>
<hr>
<h2 id="interpretation" class="anchored">6. Interpretation</h2>
<h3 id="mineral-mapping" class="anchored">Mineral Mapping</h3>
<p><strong>Example - Cuprite, Nevada mining district:</strong></p>
<p>AVIRIS hyperspectral data identified: - Kaolinite (2200 nm absorption) - Alunite (2165 nm absorption) - Buddingtonite (2125 nm absorption) - Iron oxides (500-600 nm absorption)</p>
<p><strong>Economic value:</strong></p>
<p>Mapping alteration minerals indicates hydrothermal systems associated with ore deposits.</p>
<p><strong>Advantage over field mapping:</strong></p>
<ul>
<li>Cover large areas rapidly</li>
<li>Access remote/dangerous terrain</li>
<li>Objective, repeatable</li>
<li>Subsurface minerals exposed at surface</li>
</ul>
<h3 id="precision-agriculture" class="anchored">Precision Agriculture</h3>
<p><strong>Crop biochemistry from spectra:</strong></p>
<p><strong>Chlorophyll content:</strong> - Red edge position (700-750 nm) - Chlorophyll indices using 550, 670, 750 nm</p>
<p><strong>Water stress:</strong> - Water absorption at 1400, 1900 nm - Normalized difference water index</p>
<p><strong>Nitrogen status:</strong> - Correlation with chlorophyll - Red edge shifts with N availability</p>
<p><strong>Disease detection:</strong> - Early stress signatures before visual symptoms - Spectral changes in stressed tissue</p>
<p><strong>Application:</strong></p>
<p>Variable-rate fertilizer/pesticide application based on hyperspectral maps.</p>
<h3 id="water-quality" class="anchored">Water Quality</h3>
<p><strong>Optically active constituents:</strong></p>
<p><strong>Chlorophyll-a (algae):</strong> - Absorption at 440, 675 nm - Fluorescence peak at 685 nm</p>
<p><strong>Suspended sediment:</strong> - Scattering increases reflectance across all bands - Particularly strong in red/NIR</p>
<p><strong>Dissolved organic matter (DOM):</strong> - Absorption in blue/green - “Yellow substance”</p>
<p><strong>Example - Lake Erie harmful algal blooms:</strong></p>
<p>Hyperspectral imaging from aircraft detects: - Bloom extent - Chlorophyll concentration - Cyanobacteria vs green algae discrimination</p>
<p><strong>Public health application:</strong></p>
<p>Toxic cyanobacteria produce microcystin - early detection enables beach closures.</p>
<hr>
<h2 id="what-could-go-wrong" class="anchored">7. What Could Go Wrong?</h2>
<h3 id="atmospheric-interference" class="anchored">Atmospheric Interference</h3>
<p><strong>Problem:</strong></p>
<p>Atmosphere absorbs and scatters light.</p>
<p><strong>Water vapor absorption bands:</strong> - 1400 nm - 1900 nm - 2500+ nm</p>
<p><strong>In these bands:</strong> Surface reflectance unmeasurable from aircraft/satellite.</p>
<p><strong>Solution:</strong> - Atmospheric correction (ATREM, FLAASH algorithms) - Use bands outside absorption features - Ground-based measurements for validation</p>
<h3 id="endmember-variability" class="anchored">Endmember Variability</h3>
<p><strong>Assumption:</strong> Pure endmembers have fixed spectra.</p>
<p><strong>Reality:</strong> - Vegetation spectra vary with species, health, phenology - Soil spectra vary with moisture, texture, mineralogy - Shadows, topography affect apparent spectra</p>
<p><strong>Problem:</strong></p>
<p>Using library spectra from different location/time introduces error.</p>
<p><strong>Solution:</strong> - Image-derived endmembers (select from actual scene) - Multiple endmember spectral mixture analysis (MESMA) - Account for variability in library</p>
<h3 id="dimensionality-curse" class="anchored">Dimensionality Curse</h3>
<p><strong>High dimensionality</strong> (200+ bands) causes statistical problems:</p>
<p><strong>Hughes phenomenon:</strong> - Classification accuracy decreases with too many features - Need exponentially more training samples</p>
<p><strong>Multicollinearity:</strong> - Adjacent bands highly correlated - Redundant information</p>
<p><strong>Solution:</strong> - Dimensionality reduction (PCA, MNF) - Band selection (choose optimal subset) - Feature extraction (spectral indices)</p>
<h3 id="non-linear-mixing" class="anchored">Non-Linear Mixing</h3>
<p><strong>Linear model assumes:</strong></p>
<p>Photons interact with one material before sensor.</p>
<p><strong>Reality - multiple scattering:</strong> - Canopy: Photons bounce between leaves, soil - Mineral mixtures: Intimate vs areal mixing behave differently</p>
<p><strong>Non-linear effects</strong> especially strong in: - Dense vegetation - Rough surfaces - Multiple scattering media</p>
<p><strong>Solution:</strong> - Non-linear unmixing models - Radiative transfer modelling - Acknowledge limitation in interpretation</p>
<hr>
<h2 id="extension-derivative-spectroscopy" class="anchored">8. Extension: Derivative Spectroscopy</h2>
<p><strong>Spectral derivatives</strong> enhance subtle features.</p>
<p><strong>First derivative:</strong></p>
<p><span class="math display">\frac{d\rho}{d\lambda} \approx \frac{\rho(\lambda_{i+1}) - \rho(\lambda_{i-1})}{2\Delta\lambda}</span></p>
<p><strong>Second derivative:</strong></p>
<p><span class="math display">\frac{d^2\rho}{d\lambda^2} \approx \frac{\rho(\lambda_{i+1}) - 2\rho(\lambda_i) + \rho(\lambda_{i-1})}{\Delta\lambda^2}</span></p>
<p><strong>Advantages:</strong> - Remove background (continuum) - Enhance narrow absorption features - Less sensitive to illumination variations</p>
<p><strong>Red edge derivative:</strong></p>
<p>First derivative peak position indicates chlorophyll content and plant stress.</p>
<p><strong>Mineral identification:</strong></p>
<p>Second derivative reveals overlapping absorption features invisible in original spectrum.</p>
<p><strong>Challenge:</strong></p>
<p>Derivatives amplify noise - require smoothing.</p>
<hr>
<h2 id="math-refresher-vector-spaces-and-similarity" class="anchored">9. Math Refresher: Vector Spaces and Similarity</h2>
<h3 id="dot-product" class="anchored">Dot Product</h3>
<p><strong>Definition:</strong></p>
<p><span class="math display">\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i b_i = ||\mathbf{a}|| \cdot ||\mathbf{b}|| \cos\theta</span></p>
<p>Where <span class="math inline">\theta</span> = angle between vectors.</p>
<h3 id="cosine-similarity" class="anchored">Cosine Similarity</h3>
<p><strong>Normalized dot product:</strong></p>
<p><span class="math display">\text{similarity} = \frac{\mathbf{a} \cdot \mathbf{b}}{||\mathbf{a}|| \cdot ||\mathbf{b}||} = \cos\theta</span></p>
<p><strong>Range:</strong> -1 to +1 - +1: Identical direction - 0: Orthogonal - -1: Opposite direction</p>
<p><strong>Spectral Angle Mapper uses this:</strong></p>
<p>Angle <span class="math inline">\alpha = \arccos(\text{similarity})</span></p>
<p>Small angle → high similarity</p>
<h3 id="euclidean-distance" class="anchored">Euclidean Distance</h3>
<p><span class="math display">d = ||\mathbf{a} - \mathbf{b}|| = \sqrt{\sum_{i=1}^{n} (a_i - b_i)^2}</span></p>
<p><strong>Sensitive to magnitude</strong> - bright and dark versions of same material have large distance.</p>
<p><strong>Spectral angle insensitive to magnitude</strong> - better for reflectance spectra.</p>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<ul>
<li>Hyperspectral imaging captures hundreds of narrow spectral bands enabling material identification</li>
<li>Key advantage over multispectral is fine sampling of absorption features diagnostic of composition</li>
<li>Linear spectral unmixing decomposes mixed pixels into fractional abundances of pure materials</li>
<li>Spectral Angle Mapper classifies by comparing spectrum shape to reference library</li>
<li>Applications span mineral exploration, precision agriculture, water quality, and environmental monitoring</li>
<li>Continuum removal and derivative spectroscopy enhance subtle absorption features</li>
<li>Principal Component Analysis reduces dimensionality while preserving most variance</li>
<li>Challenges include atmospheric correction, endmember variability, and non-linear mixing effects</li>
<li>AVIRIS, EnMAP, PRISMA provide operational hyperspectral data from airborne and spaceborne platforms</li>
<li>Critical tool for biochemical and mineralogical mapping from remote platforms</li>
</ul>
<hr>


<footer class="wayward-footer">
  <div class="wayward-footer__inner">
    <div class="wayward-footer__brand">
      <div class="wayward-footer__logo">WaywardHouse<span>.</span></div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wayward-footer__group" aria-labelledby="footer-reading">
      <h2 id="footer-reading" class="anchored">Reading</h2>
      <a href="https://wayward.house/articles/">Articles</a>
      <a href="https://wayward.house/learn/">Library</a>
      <a href="https://wayward.house/archive.html">Archive</a>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-site">
      <h2 id="footer-site" class="anchored">Site</h2>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
      <a href="https://wayward.house/about.html">About</a>
      <a href="https://wayward.house/contact.html">Contact</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-resources">
      <h2 id="footer-resources" class="anchored">Resources</h2>
      <a href="https://wayward.house/topics/">All Topics</a>
      <a href="https://wayward.house/privacy.html">Privacy Policy</a>
      <a href="https://wayward.house/terms.html">Terms of Use</a>
    </nav>
  </div>
</footer>

<script type="module" src="../assets/dist/main.js"></script>
<script type="module" src="../assets/js/core.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>