<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-16">

<title>Renewable Resource Geography – Computational Geography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../economic-systems/alberta-renewable-economics.html" rel="next">
<link href="../economic-systems/integrated-network.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-cb9133ab498e63a3329f2e6b8cd285fe.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0dba3a7d1e2b2b167c9d024dac5357c9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<!-- Wayward House — book theme: fonts only (no render-blocking JS) -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;1,700&amp;family=Barlow:wght@300;400;500;600;700&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating reading-body tag-hash-math tag-hash-viz tag-hash-leaflet tag-hash-pyodide quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../economic-systems/alberta-renewable-resource-geography.html"><span class="chapter-title">Renewable Resource Geography</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Computational Geography</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Learn</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../all-models/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">All Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../getting-started/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 0: Getting Started</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../getting-started/how-to-read-equations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to Read Equations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../getting-started/units-scale-and-estimation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Units, Scale, and Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../getting-started/maps-coordinates-and-layers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Maps, Coordinates, and Layers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../getting-started/uncertainty-error-and-approximation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Uncertainty, Error, and Approximation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../getting-started/what-makes-a-model-computational.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">What Makes a Model Computational</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../getting-started/setting-up-your-environment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Setting Up Your Environment</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methods-and-tools/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Methods and Tools</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methods-and-tools/how-to-validate-a-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to Validate a Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methods-and-tools/how-to-choose-a-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to Choose a Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methods-and-tools/uncertainty-propagation-and-ensembles.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Uncertainty Propagation and Ensembles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methods-and-tools/simulation-paradigms.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Simulation Paradigms</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methods-and-tools/decision-models-and-optimization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Decision Models and Optimization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methods-and-tools/bayesian-updating-and-geographic-inference.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bayesian Updating and Geographic Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../methods-and-tools/causal-inference-for-geographic-questions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Causal Inference for Geographic Questions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 1: Maths for Modelling Space</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/what-is-a-spatial-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">What Is a Spatial Model?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/linear-change-and-rate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Linear Change and Rate</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/exponential-growth-and-logarithms.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exponential Growth and Logarithms</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/logistic-growth-and-equilibrium.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logistic Growth and Equilibrium</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/map-projections-and-coordinate-reference-systems.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Map Projections and Coordinate Reference Systems</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/digital-elevation-models-as-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Digital Elevation Models as Functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/gradient-aspect-steepest-descent.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Gradient, Aspect, and Direction of Steepest Descent</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/gravity-models-trade-migration.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Gravity Models of Trade and Migration</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/accessibility-and-spatial-opportunity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Accessibility and Spatial Opportunity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/medical-geography-and-care-access.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medical Geography and Care Access</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/social-vulnerability-and-exposure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Social Vulnerability and Exposure</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/public-health-and-environmental-exposure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Public Health and Environmental Exposure</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/migration-systems-and-selective-mobility.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Migration Systems and Selective Mobility</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/segregation-and-neighborhood-inequality.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Segregation and Neighborhood Inequality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/demographic-structure-and-population-change.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Demographic Structure and Population Change</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/spatial-diffusion-of-innovation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spatial Diffusion of Innovation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/what-is-remote-sensing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">What Is Remote Sensing?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/spatial-spectral-temporal-and-radiometric-resolution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spatial, Spectral, Temporal, and Radiometric Resolution</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/atmospheric-effects-and-surface-reflectance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Atmospheric Effects and Surface Reflectance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/light-attenuation-in-canopy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Light Attenuation in a Canopy</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/spectral-mixing-and-sensor-response.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spectral Mixing and Sensor Response</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/solar-geometry-and-projection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Solar Geometry and Projection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/hydrological-flow-as-optimization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hydrological Flow as Optimization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/earth-as-rotating-sphere.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Earth as a Rotating Sphere</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 2: Earth Systems and Observation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/net-radiation-and-albedo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Net Radiation and Albedo</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/sensible-and-latent-heat-fluxes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sensible and Latent Heat Fluxes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/soil-heat-diffusion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Soil Heat Diffusion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/photosynthesis-light-response.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Photosynthesis and Light Response</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/soil-moisture-dynamics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Soil Moisture Dynamics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/wind-profiles-and-turbulence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Wind Profiles and Atmospheric Turbulence</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/temperature-moisture-gradients.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Temperature and Moisture Gradients</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/multispectral-imagery-and-band-interpretation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multispectral Imagery and Band Interpretation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/vegetation-indices-and-remote-sensing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Vegetation Indices and Remote Sensing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/circular-orbits-and-keplers-third-law.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Circular Orbits and Kepler’s Third Law</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/ground-tracks-and-orbital-geometry.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ground Tracks and Orbital Geometry</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/satellite-overpasses-and-visibility.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Satellite Overpasses and Visibility</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/how-gps-works.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How GPS Works</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/carbon-allocation-and-npp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Carbon Allocation and Net Primary Productivity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/decomposition-and-soil-carbon.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Decomposition and Soil Carbon Turnover</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/nitrogen-cycling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Nitrogen Cycling and Limitation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/phenology-and-growing-season.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Phenology and Growing Season Dynamics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../environmental-systems/land-atmosphere-coupling-and-feedbacks.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Land-Atmosphere Coupling and Feedbacks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 3: GIS and Spatial Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/point-in-polygon-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Point-in-Polygon Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/buffer-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Buffer Operations and Distance Fields</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/polygon-overlay-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Polygon Overlay and Clipping</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/spatial-joins.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spatial Joins and Proximity Queries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/raster-resampling-interpolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Raster Resampling and Interpolation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/map-algebra-focal-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Map Algebra and Focal Operations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/raster-classification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Raster Classification and Reclassification</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/viewshed-line-of-sight.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Viewshed and Line-of-Sight Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/watershed-delineation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Watershed Delineation and Flow Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/cost-distance-least-cost-paths.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cost-Distance and Least-Cost Paths</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/supervised-image-classification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Supervised Image Classification</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/change-detection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Change Detection in Satellite Imagery</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../spatial-analysis/time-series-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Time Series Analysis of Satellite Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 4: Hazards, Change, and Prediction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/fire-weather-ignition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fire Weather and Ignition Potential</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/fire-spread-modeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fire Spread modelling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/rainfall-intensity-duration.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Rainfall Intensity-Duration-Frequency</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/flood-frequency-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Flood Frequency Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/urban-flood-modeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Urban Flood modelling and Green Infrastructure</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/fire-emissions-smoke.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fire Emissions and Smoke Dispersion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/thunderstorm-dynamics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Thunderstorm Dynamics and Severe Weather</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/tornado-formation-intensity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tornado Formation and Intensity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/hail-formation-forecasting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hail Formation and Forecasting</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/boundary-layer-turbulence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Boundary Layer Turbulence and Wind Profiles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/extreme-wind-events.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Extreme Wind Events and Downbursts</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../atmospheric-hazards/compound-hazards-and-cascading-risk.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Compound Hazards and Cascading Risk</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Part 5: Cities, Networks, and Economic Geography</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/canada-trade-gravity-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Gravity Model of Trade</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/urban-bid-rent-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Bid-Rent Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/urban-agglomeration-economies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Agglomeration Economies</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/markets-spatial-arbitrage.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Spatial Arbitrage and the Law of One Price</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/alberta-pipeline-crude-oil.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Alberta’s Crude Oil Pipeline Network</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/alberta-pipeline-ngl-condensate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">NGL and Condensate Pipeline Systems</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/alberta-pipeline-natural-gas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Natural Gas Transmission from Alberta</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/alberta-pipeline-refined-products.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Refined Products Distribution</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/alberta-pipeline-integrated-network.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Integrated Network</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/canada-trade-corridors.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Canadian Trade Corridors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/canada-port-economics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Port Economics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/canada-freight-modal-split.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Modal Split and Freight Economics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/canada-integrated-trade-network.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Integrated Trade Network</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/urban-city-size-zipf.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Zipf’s Law and the City Size Distribution</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/urban-economic-base.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Urban Economic Base</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/urban-integrated-system.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Integrated Urban System</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/markets-commodity-price-formation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Commodity Price Formation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/markets-futures-geographic-instruments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Futures Markets as Geographic Instruments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/markets-price-volatility.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Price Volatility and Its Geographic Consequences</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/markets-integrated-price-system.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Integrated Price System</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/resource-hotelling-rule.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Hotelling Rule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/resource-supply-cost-curves.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Supply Cost Curves and Break-Even Prices</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/resource-royalty-regimes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Royalty Regimes and Resource Rents</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/resource-curse.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Resource Curse</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/resource-integrated-system.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Integrated Resource System</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/crude-oil-pipelines.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Crude Oil Pipelines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/ngl-condensate-systems.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">NGL and Condensate Systems</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/natural-gas-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Natural Gas Transmission</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/refined-products-distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Refined Products Distribution</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/integrated-network.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Integrated Network</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/alberta-renewable-resource-geography.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Renewable Resource Geography</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/alberta-renewable-economics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Economics of Clean Generation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../economic-systems/alberta-renewable-policy-demand.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Policy, Capital, and the Grid</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../explore-more/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Topic Libraries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cryosphere and Mountain Systems</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/snowpack-energy-balance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Snowpack Energy Balance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/snow-accumulation-melt-modeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Snow Accumulation and Melt modelling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/swe-estimation-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Snow Water Equivalent Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/avalanche-terrain-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Avalanche Terrain Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/glacier-mass-balance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Glacier Mass Balance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/glacial-meltwater-chemistry.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Glacial Meltwater Chemistry</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/glacial-lake-outburst-floods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Glacial Lake Outburst Floods (GLOFs)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/slope-stability-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Slope Stability Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/debris-flow-modeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Debris Flow modelling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cryosphere-and-mountain-systems/permafrost-thaw-geohazards.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Permafrost Thaw and Geohazards</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Advanced Remote Sensing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/prospect-leaf-optical-properties.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Leaf Optical Properties — the PROSPECT Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/sail-canopy-reflectance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Canopy Reflectance — the SAIL Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/hyperspectral-imaging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hyperspectral Imaging</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/thermal-infrared-remote-sensing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Thermal Infrared Remote Sensing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/lidar-point-clouds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Terrestrial LiDAR Point Clouds</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/bathymetric-lidar-sonar.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bathymetric LiDAR and Sonar Mapping</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/sar-fundamentals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">SAR Fundamentals and Applications</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-remote-sensing/gravity-remote-sensing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Gravity Remote Sensing (GRACE)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced-investigations/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Advanced Investigations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Computational Geography Laboratory</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/sar-fundamentals-and-applications.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">SAR Fundamentals and Applications</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/insar-deformation-monitoring.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">InSAR Deformation Monitoring</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/gravity-remote-sensing-grace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Gravity Remote Sensing (GRACE)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/passive-microwave-radiometry.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Passive Microwave Radiometry</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/rock-weathering-and-soil-formation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Rock Weathering and Soil Formation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/soil-erosion-and-the-rusle.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Soil Erosion and the RUSLE</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/shallow-landslides-and-slope-stability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Shallow Landslides and Slope Stability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/sediment-transport-in-rivers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sediment Transport in Rivers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/channel-morphology-and-hydraulic-geometry.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Channel Morphology and Hydraulic Geometry</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/wave-dynamics-and-nearshore-transformation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Wave Dynamics and Nearshore Transformation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/longshore-sediment-transport-and-coastal-budgets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Longshore Sediment Transport and Coastal Budgets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/sea-level-storm-surge-and-coastal-morphodynamics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sea Level, Storm Surge, and Coastal Morphodynamics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/urban-heat-island-dynamics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Urban Heat Island Dynamics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/urban-ventilation-and-pollutant-dispersion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Urban Ventilation and Pollutant Dispersion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/transportation-network-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Transportation Network Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/accessibility-and-travel-demand-modeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Accessibility and Travel Demand modelling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/land-use-change-modeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Land Use Change modelling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/urban-scaling-laws-and-city-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Urban Scaling Laws and City Structure</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/demographic-spatial-dynamics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Demographic Spatial Dynamics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/reservoir-operations-and-mass-balance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reservoir Operations and Mass Balance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/stochastic-streamflow-and-drought-risk.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Stochastic Streamflow and Drought Risk</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/dissolved-oxygen-dynamics-and-the-streeter-phelps-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dissolved Oxygen Dynamics and the Streeter-Phelps Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/nutrient-dynamics-and-lake-eutrophication.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Nutrient Dynamics and Lake Eutrophication</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/sediment-and-contaminant-transport-in-rivers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sediment and Contaminant Transport in Rivers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/groundwater-contaminant-plumes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Groundwater Contaminant Plumes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/pump-and-treat-and-in-situ-remediation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pump-and-Treat and In-Situ Remediation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/bayesian-inference-for-environmental-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bayesian Inference for Environmental Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/regression-for-continuous-spatial-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regression for Continuous Spatial Variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/dimensionality-reduction-for-high-dimensional-geographic-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dimensionality Reduction for High-Dimensional Geographic Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/ensemble-forecasting-and-uncertainty-quantification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ensemble Forecasting and Uncertainty Quantification</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/the-kalman-filter-and-sequential-data-assimilation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Kalman Filter and Sequential Data Assimilation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/satellite-data-assimilation-in-environmental-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Satellite Data Assimilation in Environmental Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/Fossil-Fuel-Combustion-Chemistry.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fossil Fuel Combustion Chemistry</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/Biomass-Burning-and-Pyrogenic-Carbon.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Biomass Burning and Pyrogenic Carbon</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/Land-Use-Change-and-Deforestation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Land Use Change and Deforestation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/Photosynthesis-and-Gross-Primary-Production.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Photosynthesis and Gross Primary Production</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/Ocean-Carbon-Uptake-and-Air-Sea-Exchange.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ocean Carbon Uptake and Air-Sea Exchange</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/Soil-Carbon-Storage-and-Decomposition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Soil Carbon Storage and Decomposition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../laboratory/Methanogenesis-in-Anaerobic-Environments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Methanogenesis in Anaerobic Environments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine-learning/index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Machine Learning for Geographic Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine-learning/regression-continuous-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Regression for Continuous Variables</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../machine-learning/dimensionality-reduction-pca-tsne-umap.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dimensionality Reduction: PCA, t-SNE, and UMAP</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#before-you-start" id="toc-before-you-start" class="nav-link active" data-scroll-target="#before-you-start">Before You Start</a></li>
  <li><a href="#reading-the-sun-albertas-solar-atlas" id="toc-reading-the-sun-albertas-solar-atlas" class="nav-link" data-scroll-target="#reading-the-sun-albertas-solar-atlas">Reading the sun: Alberta’s solar atlas</a></li>
  <li><a href="#wind-from-the-mountains-albertas-wind-atlas" id="toc-wind-from-the-mountains-albertas-wind-atlas" class="nav-link" data-scroll-target="#wind-from-the-mountains-albertas-wind-atlas">Wind from the mountains: Alberta’s wind atlas</a></li>
  <li><a href="#where-the-resource-meets-the-grid" id="toc-where-the-resource-meets-the-grid" class="nav-link" data-scroll-target="#where-the-resource-meets-the-grid">Where the resource meets the grid</a></li>
  <li><a href="#reference-implementation" id="toc-reference-implementation" class="nav-link" data-scroll-target="#reference-implementation">Reference implementation</a></li>
  <li><a href="#run-it-yourself" id="toc-run-it-yourself" class="nav-link" data-scroll-target="#run-it-yourself">Run it yourself</a></li>
  <li><a href="#the-resource-is-not-the-constraint" id="toc-the-resource-is-not-the-constraint" class="nav-link" data-scroll-target="#the-resource-is-not-the-constraint">The resource is not the constraint</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<!-- Wayward House — book theme: site header (rendered before Quarto body) -->
<header class="wh-bk-hdr" role="banner">
  <div class="wh-bk-hdr__inner">

    <a class="wh-bk-brand" href="https://wayward.house/" aria-label="Wayward House home">
      <span class="wh-bk-brand__word">Wayward</span><span class="wh-bk-brand__dot" aria-hidden="true">·</span><span class="wh-bk-brand__word">House</span>
    </a>

    <nav class="wh-bk-nav" aria-label="Site navigation">
      <a href="https://wayward.house/essays/">Essays</a>
      <a href="https://wayward.house/signals/">Signals</a>
      <a href="https://wayward.house/library/">Library</a>
    </nav>

    <!-- Mobile sidebar toggle — mirrors Quarto's own button so it works with Bootstrap collapse -->
    <button class="wh-bk-menu-btn" type="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle chapter navigation">
      <span class="wh-bk-menu-btn__bar" aria-hidden="true"></span>
      <span class="wh-bk-menu-btn__bar" aria-hidden="true"></span>
      <span class="wh-bk-menu-btn__bar" aria-hidden="true"></span>
    </button>

  </div>
</header>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Renewable Resource Geography</span></h1>
<p class="subtitle lead">Solar irradiance, wind atlas, and where Alberta’s energy landscape shifts</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="before-you-start" class="level2">
<h2 class="anchored" data-anchor-id="before-you-start">Before You Start</h2>
<p><strong>You should know</strong><br>
That renewable energy resources vary geographically, and that solar and wind output depend on physical conditions rather than on fuel delivery.</p>
<p><strong>You will learn</strong><br>
How Alberta’s geography shapes solar irradiance, wind potential, and renewable project siting.</p>
<p><strong>Why this matters</strong><br>
The energy transition starts with resource geography: where strong solar and wind conditions actually exist.</p>
<p><strong>If this gets hard, focus on…</strong><br>
The two governing ideas: sun angle for solar and wind speed for wind power.</p>
<p>Alberta is, by Canadian standards, a sunbaked and wind-scoured province. The same geography that made it a fossil fuel province — the Rocky Mountain front, the vast treeless prairie, the continental climate — also makes it one of Canada’s best places to generate electricity from the sky.</p>
<p>This is not a rhetorical observation. It follows directly from physics. Solar irradiance at the surface is highest where the atmosphere is thin and dry, and where the sun is not too low in the sky. Wind power is highest where terrain channels airflow and surface roughness is low. Alberta’s latitude, continental position, and topographic setting satisfy all of these conditions better than most of the country. Understanding the renewable energy transition in Alberta means first understanding the spatial structure of these resources — which the province’s geography concentrates, and which it spreads unevenly.</p>
<p>That is the work of this essay: to map Alberta’s renewable resource in quantitative terms, using the physics of solar geometry and atmospheric irradiance on the solar side, and the boundary-layer wind statistics on the wind side. The mathematics is not complicated, but it rewards precision. The difference between a 7 m/s and an 8.5 m/s wind site is not 21% more energy — it is 73% more power, because wind power scales with the cube of speed. At the scale of a 300 MW project, that difference is decisive.</p>
<figure class="cg-ill figure">
<div class="cg-ill__frame" data-markdown="1">
<div class="cg-ill__eyebrow">
Resource Geography
</div>
<h3 class="cg-ill__title anchored">
Alberta’s Renewable Landscape Splits Into A Sunny South And A Windier Foothills-Prairie Belt
</h3>
<p class="cg-ill__lede">
The chapter’s main teaching move is geographic: solar and wind are not just “renewables” in the abstract. They peak in different parts of Alberta for different physical reasons. Solar follows dry air and lower latitude. Wind follows terrain exposure, roughness, and channelled airflow. That contrast explains why the transition is spatially uneven even inside one province.
</p>
<div class="cg-ill__grid cg-ill__grid--2">
<div class="cg-ill__card">
<div class="cg-ill__label">
Solar
</div>
<h4 class="anchored">
Highest In The Dry Southern Belt
</h4>
<p>
Southern Alberta benefits from lower latitude, more frequent clear-sky conditions, and drier air, which makes fixed-tilt solar unusually productive by Canadian standards.
</p>
</div>
<div class="cg-ill__card">
<div class="cg-ill__label">
Wind
</div>
<h4 class="anchored">
Best Along The Foothills And Open Prairie Corridors
</h4>
<p>
Wind quality improves where airflow is accelerated by topography or preserved by open prairie fetch, which is why Alberta’s best wind sites cluster differently from its best solar sites.
</p>
</div>
</div>
<div class="cg-ill__route-footer">
<p class="cg-ill__route-note">
Renewable siting starts with spatial physics. Alberta is not one resource province but several overlapping solar and wind geographies with different advantages and tradeoffs.
</p>
</div>
</div>
</figure>
</section>
<section id="reading-the-sun-albertas-solar-atlas" class="level2">
<h2 class="anchored" data-anchor-id="reading-the-sun-albertas-solar-atlas">Reading the sun: Alberta’s solar atlas</h2>
<p>The amount of solar energy arriving at the Earth’s surface depends on two factors that geography controls: the angle of the sun above the horizon, and the thickness and composition of the atmosphere the sunlight must traverse. Both vary with latitude and season in ways that can be calculated from first principles.</p>
<p>The sun’s position in the sky at any moment is described by two angles. The most important for resource assessment is the <strong>solar zenith angle</strong> <em>θ</em><sub><em>z</em></sub> — the angle between the sun’s rays and the vertical. When the sun is directly overhead, <em>θ</em><sub><em>z</em></sub> = 0° and irradiance is at its maximum. When the sun is near the horizon, <em>θ</em><sub><em>z</em></sub> approaches 90° and irradiance falls toward zero, both because the sunbeam spreads across a larger surface area and because it travels through a longer path of atmosphere.</p>
<p>The zenith angle at solar noon depends on latitude <em>ϕ</em> and the sun’s <strong>declination</strong> <em>δ</em>, which is its angular distance north or south of the celestial equator. Declination varies through the year as the Earth orbits the sun with its axis tilted at 23.45°:</p>
<p><span class="math display">
\delta = -23.45° \cdot \cos\left(\frac{360°}{365}(d + 10)\right)
</span></p>
<p>where <em>d</em> is the day of year. At the June solstice (<em>d</em> ≈ 172), <em>δ</em> ≈ +23.45°: the sun is as far north as it gets, days are longest, and irradiance is highest in the northern hemisphere. At the December solstice, <em>δ</em> ≈ −23.45°: the sun is far south, Alberta receives barely seven hours of low-angle winter sunlight, and daily energy collection collapses.</p>
<p>The cosine of the solar zenith angle at noon follows from spherical geometry:</p>
<p>cos (<em>θ</em><sub><em>z</em></sub>) = sin (<em>ϕ</em>)sin (<em>δ</em>) + cos (<em>ϕ</em>)cos (<em>δ</em>)</p>
<p>At Lethbridge (<em>ϕ</em> = 49.7°N) on the summer solstice, cos (<em>θ</em><sub><em>z</em></sub>) ≈ 0.91, meaning the sun reaches 65.7° above the horizon. At the winter solstice, the same calculation gives cos (<em>θ</em><sub><em>z</em></sub>) ≈ 0.41, with the sun peaking at only 24.1° elevation. The ratio — roughly 2:1 between summer and winter peak irradiance — is the geometric foundation of Alberta’s strongly seasonal solar resource.</p>
<p>From the zenith angle, we compute surface irradiance using a simplified Beer-Lambert atmospheric attenuation model. The atmosphere absorbs and scatters sunlight in proportion to the path length through it, which is proportional to sec (<em>θ</em><sub><em>z</em></sub>). The peak irradiance at the surface is:</p>
<p><em>G</em><sub>0</sub> = <em>G</em><sub>*s**c<em></em></sub><em> ⋅ cos (</em>θ<em><sub></sub></em>z<em>) ⋅ </em>τ<em><sup>sec (</sup></em>θ<em><sub></sub></em>z*)</p>
<table>
<thead>
<tr>
<th>
Symbol
</th>
<th>
Meaning
</th>
<th>
Value
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<span class="math inline"><em>G</em><sub><em>s</em><em>c</em></sub></span>
</td>
<td>
Solar constant
</td>
<td>
1,361 W/m²
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>θ</em><sub><em>z</em></sub></span>
</td>
<td>
Solar zenith angle at noon
</td>
<td>
degrees
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>τ</em></span>
</td>
<td>
Atmospheric transmittance
</td>
<td>
~0.75 (clear sky)
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>ϕ</em></span>
</td>
<td>
Latitude
</td>
<td>
degrees — Lethbridge 49.7°N; Edmonton 53.6°N
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>δ</em></span>
</td>
<td>
Solar declination
</td>
<td>
degrees, varies ±23.45°
</td>
</tr>
</tbody>
</table>
<p>The <em>τ</em><sup>sec (<em>θ</em><sub><em>z</em></sub>)</sup> term captures the exponential depletion of the beam as path length increases. At large zenith angles — early morning, late afternoon, winter — the sun is dim even on clear days because the beam has traversed a thicker column of air.</p>
<p>Daily total irradiance integrates <em>G</em><sub>0</sub> over the daylight period. A useful approximation treats the daily curve as sinusoidal and scales by the <strong>clearness index</strong> <em>k</em><sub><em>t</em></sub>, the ratio of actual surface irradiance to the theoretical clear-sky value. <em>k</em><sub><em>t</em></sub> accounts for cloud cover, aerosols, and humidity on average over the year. Alberta’s continental climate produces <em>k</em><sub><em>t</em></sub> ≈ 0.52–0.58, which is remarkably high by Canadian standards. Southern Alberta in particular benefits from frequent high-pressure systems, low atmospheric humidity, and the Chinook’s tendency to clear winter cloud:</p>
<p><span class="math display">
\text{GHI}\_{\text{annual}} \approx \frac{1}{365}\sum\_{d=1}^{365} G_0(d) \cdot h\_{\text{daylight}}(d) \cdot k_t
</span></p>
<p>where <em>h</em><sub>daylight</sub>(<em>d</em>) is the number of daylight hours on day <em>d</em>, computed from the sunrise equation.</p>
<p>The result, summed across Alberta’s latitude range, is a solar resource gradient that runs from approximately 1,280 kWh/m²/year at Lethbridge to 1,020 kWh/m²/year at Grande Prairie:</p>
<p><strong>Alberta solar resource (NRCan Solar Atlas, approximate annual GHI):</strong></p>
<table>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr>
<th>
Location
</th>
<th>
Latitude
</th>
<th>
Annual GHI (kWh/m²)
</th>
<th>
Capacity factor (20% panel)
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Lethbridge
</td>
<td>
49.7°N
</td>
<td>
~1,280
</td>
<td>
~26%
</td>
</tr>
<tr>
<td>
Medicine Hat
</td>
<td>
50.0°N
</td>
<td>
~1,260
</td>
<td>
~26%
</td>
</tr>
<tr>
<td>
Vulcan County
</td>
<td>
50.4°N
</td>
<td>
~1,240
</td>
<td>
~25%
</td>
</tr>
<tr>
<td>
Calgary
</td>
<td>
51.1°N
</td>
<td>
~1,180
</td>
<td>
~24%
</td>
</tr>
<tr>
<td>
Red Deer
</td>
<td>
52.3°N
</td>
<td>
~1,130
</td>
<td>
~23%
</td>
</tr>
<tr>
<td>
Edmonton
</td>
<td>
53.6°N
</td>
<td>
~1,090
</td>
<td>
~22%
</td>
</tr>
<tr>
<td>
Grande Prairie
</td>
<td>
55.2°N
</td>
<td>
~1,020
</td>
<td>
~21%
</td>
</tr>
</tbody>
</table>
<p>The <strong>solar capacity factor</strong> converts annual GHI to a dimensionless measure of effective utilisation. For a panel with efficiency <em>η</em>:</p>
<p><span class="math display">
\text{CF}\_{\text{solar}} = \frac{\text{GHI}\_{\text{annual}} \cdot \eta\_{\text{panel}}}{8760 \text{ h} \cdot G\_{sc}}
</span></p>
<p>A 20% efficient panel at Lethbridge, receiving 1,280 kWh/m²/year and measuring against the theoretical maximum if the sun delivered its full 1,361 W/m² continuously (which of course it does not), yields a capacity factor of roughly 26%. More practically, a 1 MW solar array at Lethbridge generates approximately 1,280 × 0.20 × 1,000 = 256,000 kWh per year — 256 MWh from 1 MW of nameplate capacity.</p>
<p>The comparison to other regions is informative. Lethbridge’s 1,280 kWh/m²/year GHI exceeds many locations in southern Germany, where utility-scale solar has been deployed at scale since the early 2000s. Munich receives roughly 1,200 kWh/m²/year. The political and regulatory constraints on Alberta solar deployment are not, in other words, explained by inadequate resource.</p>
<p>The Vulcan County cluster — where both Blackspring Ridge Wind (544 MW) and Travers Solar (465 MW, completed 2022–2023 and Canada’s largest solar farm at the time of construction) are located — sits at approximately 50.4°N. It captures a combination of high insolation, flat Class 1 agricultural land with low reflectivity losses, and proximity to the existing 240kV transmission corridor running north from Lethbridge. The geography dictated the economics before any project was proposed.</p>
<div data-leaflet="" id="alberta-resource-map" style="height:520px;" data-lat="52.5" data-lng="-113.5" data-zoom="5" data-tiles="carto"></div>
<p><em>Alberta renewable resource geography — wind resource zones (blue fill, darker = higher capacity factor) and annual solar irradiance at key stations (gold circles, sized by GHI). Click any zone or circle for data. Source: NRCan Solar Atlas; Environment Canada Wind Atlas.</em></p>
<script>
document.getElementById('alberta-resource-map').addEventListener('leaflet:ready', function(e) {
const map = e.detail.map;
const L   = window.L;

map.fitBounds([[49.0, -117.5], [57.0, -110.0]]);

// ── Wind resource zones ────────────────────────────────────────────────────
// Approximate rectangular zones based on Environment Canada Wind Atlas.
// Colours use the primary blue palette scaled by capacity factor.
const windZones = [
{
bounds: [[49.0, -115.0], [50.5, -113.2]],
color: '#1e5c99',
label: 'Crowsnest / Pincher Creek corridor',
speed: '8.0–9.5 m/s', cf: '38–45%',
note: 'Mountain front katabatic forcing. Castle Rock Ridge, Pincher Creek cluster.'
},
{
bounds: [[49.0, -113.2], [50.5, -111.0]],
color: '#2e7dd1',
label: 'Lethbridge foothills',
speed: '7.0–8.5 m/s', cf: '32–40%',
note: 'Blackspring Ridge Wind (544 MW), Forty Mile. Proximity to 240 kV corridor.'
},
{
bounds: [[50.2, -113.8], [51.5, -112.0]],
color: '#4e8ac4',
label: 'Vulcan County',
speed: '6.5–7.5 m/s', cf: '27–35%',
note: 'Travers Solar (465 MW) also in this zone. Sundial Wind and multiple co-located projects.'
},
{
bounds: [[50.5, -115.5], [52.2, -113.8]],
color: '#6baed6',
label: 'Calgary foothills',
speed: '6.0–7.5 m/s', cf: '22–35%',
note: 'Foothills lose mountain channelling effect north of Calgary. Various smaller projects.'
},
{
bounds: [[49.0, -111.0], [52.0, -110.0]],
color: '#9ecae1',
label: 'Eastern prairie',
speed: '5.5–7.0 m/s', cf: '18–28%',
note: 'Flat terrain, low roughness — adequate wind but not competitive with SW corridor at current costs.'
},
{
bounds: [[52.0, -117.5], [57.5, -110.0]],
color: '#c6dbef',
label: 'Central / North Alberta',
speed: '5.5–6.5 m/s', cf: '18–26%',
note: 'Northwestern boreal margin. Without Rocky Mountain forcing; CF well below SW corridor.'
},
];

windZones.forEach(z => {
L.rectangle(z.bounds, {
color: 'transparent',
fillColor: z.color,
fillOpacity: 0.42,
weight: 0,
})
.bindPopup(
`<strong>${z.label}</strong><br>` +
`Wind speed: ${z.speed}<br>` +
`Capacity factor: ${z.cf}<br>` +
`<em style="font-size:11px;">${z.note}</em>`
)
.addTo(map);
});

// ── Solar resource stations ────────────────────────────────────────────────
// Circle radius scales linearly with GHI. Gold fill (#e8cc6a = site secondary).
const solarStations = [
{ name: 'Lethbridge',     lat: 49.70, lng: -112.83, ghi: 1280, cf: 26 },
{ name: 'Medicine Hat',   lat: 50.05, lng: -110.68, ghi: 1260, cf: 26 },
{ name: 'Calgary',        lat: 51.04, lng: -114.06, ghi: 1180, cf: 24 },
{ name: 'Red Deer',       lat: 52.27, lng: -113.81, ghi: 1130, cf: 23 },
{ name: 'Edmonton',       lat: 53.55, lng: -113.50, ghi: 1090, cf: 22 },
{ name: 'Grande Prairie', lat: 55.17, lng: -118.80, ghi: 1020, cf: 21 },
];

const isDark = document.documentElement.dataset.theme === 'dark';
const ringColor = isDark ? '#ffffff' : '#5a4a10';

solarStations.forEach(s => {
const r = 7 + (s.ghi - 1000) / 35;   // range ~7–17 px
L.circleMarker([s.lat, s.lng], {
radius: r,
fillColor: '#e8cc6a',
color: ringColor,
weight: 1.5,
fillOpacity: 0.9,
})
.bindPopup(
`<strong>${s.name}</strong><br>` +
`Annual GHI: ${s.ghi} kWh/m²/year<br>` +
`Solar CF (20% panel): ~${s.cf}%`
)
.addTo(map);
});

// ── Key project markers ────────────────────────────────────────────────────
const projects = [
{ name: 'Travers Solar',           mw: 465, lat: 50.35, lng: -113.18, type: 'solar' },
{ name: 'Blackspring Ridge Wind',  mw: 544, lat: 50.08, lng: -112.87, type: 'wind'  },
{ name: 'Pincher Creek cluster',   mw: 300, lat: 49.48, lng: -113.92, type: 'wind'  },
];

projects.forEach(p => {
L.circleMarker([p.lat, p.lng], {
radius: 8,
fillColor: p.type === 'solar' ? '#e8cc6a' : '#4e8ac4',
color: isDark ? '#ffffff' : '#222222',
weight: 2.5,
fillOpacity: 1,
})
.bindPopup(`<strong>${p.name}</strong><br>${p.mw} MW · ${p.type}`)
.addTo(map);
});

// ── Legend ────────────────────────────────────────────────────────────────
const legend = L.control({ position: 'bottomright' });
legend.onAdd = () => {
const bg   = isDark ? 'rgba(28,28,28,0.92)' : 'rgba(255,255,255,0.92)';
const text = isDark ? '#d4d4d4' : '#333333';
const div  = L.DomUtil.create('div');
div.style.cssText = `background:${bg};color:${text};padding:10px 14px;border-radius:4px;
font-size:11px;line-height:1.9;box-shadow:0 1px 5px rgba(0,0,0,0.25);max-width:215px;`;
div.innerHTML = `
<strong style="font-size:12px;display:block;margin-bottom:2px;">Wind capacity factor</strong>
<span style="background:#1e5c99;opacity:.7;display:inline-block;width:13px;height:9px;margin-right:5px;"></span>38–45% · Crowsnest / Pincher Creek<br>
<span style="background:#2e7dd1;opacity:.7;display:inline-block;width:13px;height:9px;margin-right:5px;"></span>32–40% · Lethbridge foothills<br>
<span style="background:#4e8ac4;opacity:.7;display:inline-block;width:13px;height:9px;margin-right:5px;"></span>27–35% · Vulcan County<br>
<span style="background:#6baed6;opacity:.7;display:inline-block;width:13px;height:9px;margin-right:5px;"></span>22–35% · Calgary foothills<br>
<span style="background:#9ecae1;opacity:.7;display:inline-block;width:13px;height:9px;margin-right:5px;"></span>18–28% · Prairies / north<br>
<br>
<strong style="font-size:12px;display:block;margin-bottom:2px;">Solar irradiance</strong>
<span style="background:#e8cc6a;border:1.5px solid #8a6800;display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px;"></span>Annual GHI — circle size ∝ intensity<br>
<br>
<strong style="font-size:12px;display:block;margin-bottom:2px;">Projects</strong>
<span style="background:#e8cc6a;border:2px solid #222;display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px;"></span>Solar<br>
<span style="background:#4e8ac4;border:2px solid #222;display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px;"></span>Wind
`;
return div;
};
legend.addTo(map);
});
</script>
</section>
<section id="wind-from-the-mountains-albertas-wind-atlas" class="level2">
<h2 class="anchored" data-anchor-id="wind-from-the-mountains-albertas-wind-atlas">Wind from the mountains: Alberta’s wind atlas</h2>
<p>Alberta’s wind resource is more geographically concentrated than its solar resource. Where solar irradiance varies by roughly 25% across the province’s latitude range, wind power density in the most productive southwest corner can exceed that of the central prairie by a factor of three or more. The difference lies in the Rocky Mountain front.</p>
<p>The mechanism is twofold. First, the Rockies channel and accelerate airflow through gaps and passes. The Crowsnest Pass and the broader Livingstone Range produce a pronounced <strong>katabatic wind regime</strong> — downslope flow that accelerates as it descends from the Continental Divide and fans across the prairie. The Chinook is the most familiar expression of this: a warm, dry, gusty wind that can raise Calgary’s temperature by 20°C in an hour in winter. But the same topographic forcing produces elevated mean wind speeds year-round in a belt from Crowsnest Pass through Pincher Creek and northeast toward Lethbridge and the Vulcan County area.</p>
<p>Second, the shortgrass prairie of southwest Alberta has exceptionally low aerodynamic roughness. The <strong>atmospheric boundary layer</strong> — the lowest few hundred metres of the troposphere, where wind speed is retarded by friction with the surface — develops more slowly over smooth prairie than over forest or urban terrain. At 80m hub height, a modern wind turbine is well above the surface roughness layer in most of southern Alberta, sampling the more energetic flow of the free atmosphere.</p>
<p>The <strong>wind power density</strong> at a given hub height follows directly from fluid mechanics:</p>
<p><span class="math display">
P = \frac{1}{2} \rho v^3
</span></p>
<p>where <em>ρ</em> ≈ 1.225 kg/m³ is air density at sea level and <em>v</em> is wind speed in m/s. The cubic dependence on speed is the most important single fact about wind energy siting. At 7 m/s, wind power density is <span class="math inline">\frac{1}{2} \times 1.225 \times 343 = 210</span> W/m². At 8.5 m/s — a 21% increase in speed — it is <span class="math inline">\frac{1}{2} \times 1.225 \times 614 = 376</span> W/m². That 21% increase in speed produces 79% more power. This is why the Pincher Creek / Crowsnest corridor with mean 80m speeds of 8.0–9.5 m/s is economically in a different category from the central prairie at 6.0–7.0 m/s, even though both locations look adequate on a wind resource map.</p>
<p>The <strong>wind capacity factor</strong> — the dimensionless measure of how much of the theoretical maximum a turbine actually produces — can be estimated from mean hub-height speed using a rule of thumb calibrated to Alberta’s turbine fleet:</p>
<p>CF<sub>wind</sub> ≈ 0.087 ⋅ <em>v</em><sub>80<em>m</em></sub> − 0.30</p>
<p>where <em>v</em><sub>80<em>m</em></sub> is mean wind speed at 80m hub height in m/s. This linear approximation is valid in the 6–10 m/s range where most Alberta projects operate. At 8.5 m/s (Pincher Creek cluster), it gives CF ≈ 0.44; at 7.0 m/s (Vulcan County), CF ≈ 0.31; at 6.0 m/s (central prairie), CF ≈ 0.22.</p>
<p><strong>Alberta wind resource (Environment Canada Wind Atlas, 80m hub height):</strong></p>
<table>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr>
<th>
Zone
</th>
<th>
Mean wind speed
</th>
<th>
Capacity factor (typical)
</th>
<th>
Key projects
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Crowsnest / Pincher Creek
</td>
<td>
8.0–9.5 m/s
</td>
<td>
38–45%
</td>
<td>
Castle Rock Ridge, Pincher Creek cluster
</td>
</tr>
<tr>
<td>
Lethbridge foothills
</td>
<td>
7.0–8.5 m/s
</td>
<td>
32–40%
</td>
<td>
Blackspring Ridge (544 MW), Forty Mile
</td>
</tr>
<tr>
<td>
Vulcan County
</td>
<td>
6.5–7.5 m/s
</td>
<td>
27–35%
</td>
<td>
Sundial, multiple projects
</td>
</tr>
<tr>
<td>
Calgary foothills
</td>
<td>
6.0–7.5 m/s
</td>
<td>
22–35%
</td>
<td>
Various
</td>
</tr>
<tr>
<td>
Central prairie
</td>
<td>
5.5–7.0 m/s
</td>
<td>
18–30%
</td>
<td>
Northern projects
</td>
</tr>
</tbody>
</table>
<p>The Blackspring Ridge Wind project, at 544 MW one of the largest wind farms in Canada, sits in the Lethbridge foothills zone — not the highest-resource Crowsnest corridor, but a zone with well-understood resource, existing 240kV access, and fewer competing transmission queue applications than the Crowsnest area. This illustrates a recurring theme in Alberta renewable development: the best resource is not always where the best projects get built, because the grid, land access, and regulatory environment all filter the economic outcome.</p>
<p>North of Calgary, the Alberta foothills lose their channeling effect on airflow. The Grande Prairie region has moderate northwesterly wind from the boreal margin of the province, but without the mountain forcing. Mean 80m speeds of 5.5–6.5 m/s yield capacity factors in the 18–26% range — technically viable, but not competitive with the southwest corridor at current capital costs.</p>
</section>
<section id="where-the-resource-meets-the-grid" class="level2">
<h2 class="anchored" data-anchor-id="where-the-resource-meets-the-grid">Where the resource meets the grid</h2>
<p>The map above makes the central argument visible. Alberta’s best solar resource — concentrated in the Lethbridge, Medicine Hat, and Vulcan County area — and its best wind resource — concentrated in the Crowsnest/Pincher Creek corridor — both sit in the southwestern quarter of the province. But Alberta’s primary electricity load centres are Edmonton (population 1.5 million) and Calgary (population 1.5 million), and the industrial heartland — petrochemical facilities at Fort Saskatchewan, coal and gas generation at Genesee and Wabamun — is concentrated in the Edmonton-Calgary corridor, serviced by an extensive 240kV and 500kV network.</p>
<p>The AESO’s transmission backbone was built to serve that industrial geography. The main 500kV corridor runs north-south between Edmonton and Calgary, with a southward extension toward Lethbridge. The eastern radials serve the oil sands and the coal fleet. The southwest corner — precisely where the best renewable resource is concentrated — is served by 240kV infrastructure that was designed for a smaller and less variable load, not for connecting gigawatts of variable renewable generation to the Edmonton and Calgary load centres.</p>
<p>The consequence is what grid planners call <strong>transmission constraint</strong>: the physical limit on how much energy can flow from generation source to load centre on the existing wires. When the wind blows hard in the Pincher Creek corridor on a mild spring night, and Calgary and Edmonton demand is low, the 240kV lines from the southwest can be fully subscribed. Generation that could be delivered has nowhere to go. Projects in the AESO interconnection queue that would add to this corridor face years of transmission planning studies, potential upgrade costs running to hundreds of millions of dollars, and uncertainty about whether the upgrade will be built before the project reaches its financial close decision.</p>
<figure class="cg-ill figure">
<div class="cg-ill__frame" data-markdown="1">
<div class="cg-ill__eyebrow">
Siting Tradeoffs
</div>
<h3 class="cg-ill__title anchored">
The Best Renewable Site Is Where Resource Quality And Grid Access Overlap
</h3>
<p class="cg-ill__lede">
High irradiance or strong wind alone is not enough. A project only becomes easy to build when the resource, transmission access, land availability, and demand geography line up well enough to keep connection cost and curtailment risk under control.
</p>
<div class="cg-ill__compare">
<div class="cg-ill__compare-card">
<div class="cg-ill__label">
South Solar
</div>
<h4 class="anchored">
Excellent Sun, Variable Grid Reach
</h4>
<p>
Southern Alberta often wins on annual solar yield, but transmission reinforcement and distance to major load can still decide project viability.
</p>
<p><strong>Main question: how expensive is interconnection?</strong></p>
</div>
<div class="cg-ill__compare-card">
<div class="cg-ill__label">
Foothills Wind
</div>
<h4 class="anchored">
Excellent Wind, More Siting Friction
</h4>
<p>
Wind corridors can be exceptional, but terrain, permitting, and local congestion can offset part of the meteorological advantage.
</p>
<p><strong>Main question: does strong wind survive the network bottleneck?</strong></p>
</div>
<div class="cg-ill__compare-card">
<div class="cg-ill__label">
Balanced Site
</div>
<h4 class="anchored">
Resource + Grid + Land
</h4>
<p>
The strongest projects often sit slightly below the pure resource maximum because transmission and development conditions are better.
</p>
<p><strong>Main question: what is the best total project geography?</strong></p>
</div>
</div>
<figcaption>
Renewable geography is really a matching problem between physical resource and electrical infrastructure. The winning site is rarely chosen by weather alone.
</figcaption>
</div>
</figure>
<p>The Travers Solar project (465 MW) successfully navigated this environment because it sits near existing 240kV infrastructure in the Lethbridge area, and because its generation profile — peaking in the afternoon when Calgary air-conditioning demand is also high — partially aligns with load timing. Projects further into the Crowsnest corridor face a more difficult transmission calculus. The AESO Long-term Transmission Plan has identified the southern Alberta region as requiring investment, but the timeline and funding mechanism remain subjects of ongoing regulatory proceedings.</p>
<p>There is also the question of the <strong>southern intertie</strong>. Alberta has a limited interconnection to Montana’s grid (approximately 300 MW) and a more substantial connection to British Columbia (approximately 1,200 MW, though BC’s capacity is often committed to export or internal supply). These interties allow Alberta to export surplus renewable generation when it cannot be absorbed domestically, and to import when Alberta’s dispatchable fleet is short. But at 300 MW and 1,200 MW respectively, they are small relative to Alberta’s approximately 18,000 MW of peak demand, and cannot resolve large renewable surplus or deficit events. The BC intertie in the Crowsnest Pass area is geographically close to the province’s best wind resource but is not designed as a renewable export corridor.</p>
<p>The spatial mismatch between resource and grid is, in the language of the cluster brief, the dominant engineering and economic constraint on Alberta’s renewable transition. It is not that the resource is insufficient — southern Alberta’s wind and solar potential, if fully developed, could supply Alberta’s electricity demand many times over. The constraint is the capital-intensive, time-consuming work of connecting the resource to the load. That work is the subject of the LCOE analysis in R2.</p>
</section>
<section id="reference-implementation" class="level2">
<h2 class="anchored" data-anchor-id="reference-implementation">Reference implementation</h2>
<p>The full static implementation: compute annual GHI and capacity factor for Alberta stations from first principles, using the solar geometry model.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>sys.path.insert(<span class="dv">0</span>, <span class="st">"../../"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> shared.plot_style <span class="im">import</span> <span class="bu">apply</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Solar geometry ──────────────────────────────────────────────────────────</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> solar_declination(day_of_year: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Solar declination angle (degrees) for a given day of year."""</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span><span class="fl">23.45</span> <span class="op">*</span> np.cos(np.radians(<span class="dv">360</span> <span class="op">/</span> <span class="dv">365</span> <span class="op">*</span> (day_of_year <span class="op">+</span> <span class="dv">10</span>)))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cos_zenith_noon(lat_deg: <span class="bu">float</span>, day_of_year: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Cosine of solar zenith angle at solar noon."""</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    delta <span class="op">=</span> np.radians(solar_declination(day_of_year))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    phi   <span class="op">=</span> np.radians(lat_deg)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.sin(phi) <span class="op">*</span> np.sin(delta) <span class="op">+</span> np.cos(phi) <span class="op">*</span> np.cos(delta)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> daylight_hours(lat_deg: <span class="bu">float</span>, day_of_year: <span class="bu">int</span>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Approximate daylight hours using sunrise equation."""</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    delta <span class="op">=</span> np.radians(solar_declination(day_of_year))</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    phi   <span class="op">=</span> np.radians(lat_deg)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    cos_ha <span class="op">=</span> <span class="op">-</span>np.tan(phi) <span class="op">*</span> np.tan(delta)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    cos_ha <span class="op">=</span> np.clip(cos_ha, <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    ha <span class="op">=</span> np.degrees(np.arccos(cos_ha))       <span class="co"># hour angle at sunrise (degrees)</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">2</span> <span class="op">*</span> ha <span class="op">/</span> <span class="fl">15.0</span>                     <span class="co"># convert to hours</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> daily_ghi_wh(lat_deg: <span class="bu">float</span>, day_of_year: <span class="bu">int</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>                 tau: <span class="bu">float</span> <span class="op">=</span> <span class="fl">0.75</span>, kt: <span class="bu">float</span> <span class="op">=</span> <span class="fl">0.55</span>) <span class="op">-&gt;</span> <span class="bu">float</span>:</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">    Approximate daily GHI (Wh/m²) using peak irradiance × daylight hours × clearness.</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co">    ----------</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co">    lat_deg : latitude (degrees north)</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">    day_of_year : 1–365</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co">    tau : atmospheric transmittance (clear sky ~0.75)</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="co">    kt  : clearness index (actual/extraterrestrial) — Alberta: 0.52–0.58</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    cz <span class="op">=</span> cos_zenith_noon(lat_deg, day_of_year)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> cz <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">0.0</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    G_sc <span class="op">=</span> <span class="fl">1361.0</span>                             <span class="co"># W/m² solar constant</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    G0   <span class="op">=</span> G_sc <span class="op">*</span> cz <span class="op">*</span> tau<span class="op">**</span>(<span class="dv">1</span> <span class="op">/</span> cz)         <span class="co"># Beer-Lambert clear-sky at noon</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    dl   <span class="op">=</span> daylight_hours(lat_deg, day_of_year)</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sinusoidal integration approximation: daily total ≈ (2/π) × peak × daylight_seconds</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    daily_kwh <span class="op">=</span> (<span class="dv">2</span> <span class="op">/</span> np.pi) <span class="op">*</span> G0 <span class="op">*</span> dl <span class="op">*</span> <span class="dv">3600</span> <span class="op">*</span> kt <span class="op">/</span> <span class="dv">1000</span>   <span class="co"># kWh/m²/day</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> daily_kwh <span class="op">*</span> <span class="dv">1000</span>                                  <span class="co"># Wh/m²/day</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Annual GHI for Alberta stations ────────────────────────────────────────</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>stations <span class="op">=</span> {</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Lethbridge (49.7°N)"</span>:  <span class="fl">49.7</span>,</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Calgary (51.1°N)"</span>:     <span class="fl">51.1</span>,</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Red Deer (52.3°N)"</span>:    <span class="fl">52.3</span>,</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Edmonton (53.6°N)"</span>:    <span class="fl">53.6</span>,</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Grande Prairie (55.2°N)"</span>: <span class="fl">55.2</span>,</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>days <span class="op">=</span> np.arange(<span class="dv">1</span>, <span class="dv">366</span>)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Annual solar resource — Alberta stations (clear-sky model, kt=0.55)"</span>)</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Station'</span><span class="sc">:&lt;28}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Annual GHI (kWh/m²)'</span><span class="sc">:&gt;20}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Peak sun-hours/day'</span><span class="sc">:&gt;20}</span><span class="ss">"</span>)</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, lat <span class="kw">in</span> stations.items():</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>    daily <span class="op">=</span> np.array([daily_ghi_wh(lat, d) <span class="op">/</span> <span class="dv">1000</span> <span class="cf">for</span> d <span class="kw">in</span> days])  <span class="co"># kWh/m²/day</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>    annual <span class="op">=</span> np.<span class="bu">sum</span>(daily)</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>    psh <span class="op">=</span> annual <span class="op">/</span> <span class="dv">365</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>name<span class="sc">:&lt;26}</span><span class="ss"> </span><span class="sc">{</span>annual<span class="sc">:&gt;18.0f}</span><span class="ss">   </span><span class="sc">{</span>psh<span class="sc">:&gt;18.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre><code>Annual solar resource — Alberta stations (clear-sky model, kt=0.55)
Station                      Annual GHI (kWh/m²)   Peak sun-hours/day
  Lethbridge (49.7°N)                      1277                 3.50
  Calgary (51.1°N)                         1211                 3.32
  Red Deer (52.3°N)                        1157                 3.17
  Edmonton (53.6°N)                        1094                 3.00
  Grande Prairie (55.2°N)                  1005                 2.75</code></pre>
<p>The model outputs match the NRCan Solar Atlas values to within a few percent — reasonable agreement for a two-parameter approximation (transmittance and clearness index) applied over a 6° latitude range. The remaining discrepancy reflects seasonal variation in cloud cover and aerosol loading that a fixed <em>k</em><sub><em>t</em></sub> cannot capture.</p>
</section>
<section id="run-it-yourself" class="level2">
<h2 class="anchored" data-anchor-id="run-it-yourself">Run it yourself</h2>
<p>The cell below calculates annual solar resource and capacity factor for any Alberta latitude, and estimates wind capacity factor from mean hub-height speed. Change <code>latitude_deg</code> to compare Lethbridge (49.7), Calgary (51.1), or Edmonton (53.6). Adjust <code>kt</code> down to 0.45 to simulate a cloudy year. For wind, try <code>wind_speed_80m = 8.5</code> for the Pincher Creek corridor, or <code>6.0</code> for a central prairie site near the economic break-even.</p>
<div class="pyodide-cell"><pre><code class="language-python">import numpy as np

# ── Solar resource calculator ──────────────────────────────────────────────
# Estimate annual GHI and solar capacity factor for any Alberta location

# ── Parameters — change these ──────────────────────────────────────────────
latitude_deg   = 49.7    # degrees N — Lethbridge: 49.7; Calgary: 51.1; Edmonton: 53.6
kt             = 0.55    # clearness index — southern AB: 0.55–0.58; northern: 0.52–0.54
panel_eff      = 0.20    # panel efficiency (fraction) — typical 2024 utility: 0.20–0.22
wind_speed_80m = 7.5     # mean wind speed at 80m hub height (m/s) — Pincher Creek: 8.5; prairie: 6–7

# ── Solar calculation ──────────────────────────────────────────────────────
def solar_declination(d):
return -23.45 * np.cos(np.radians(360 / 365 * (d + 10)))

def cos_zenith(lat, d):
delta = np.radians(solar_declination(d))
phi   = np.radians(lat)
return np.sin(phi)*np.sin(delta) + np.cos(phi)*np.cos(delta)

def daylight_h(lat, d):
delta = np.radians(solar_declination(d))
phi   = np.radians(lat)
cos_ha = np.clip(-np.tan(phi)*np.tan(delta), -1, 1)
return 2 * np.degrees(np.arccos(cos_ha)) / 15.0

days = np.arange(1, 366)
annual_ghi = 0.0
for d in days:
cz = cos_zenith(latitude_deg, d)
if cz &lt;= 0:
continue
G0 = 1361 * cz * 0.75**(1/cz)
dl = daylight_h(latitude_deg, d)
annual_ghi += (2/np.pi) * G0 * dl * kt / 1000   # kWh/m²/day

annual_ghi_total = annual_ghi                         # kWh/m²/year
cf_solar = annual_ghi_total * panel_eff / 8760        # capacity factor

# ── Wind calculation ────────────────────────────────────────────────────────
cf_wind  = max(0, 0.087 * wind_speed_80m - 0.30)      # rule of thumb
rho_air  = 1.225                                        # kg/m³ at sea level
power_density = 0.5 * rho_air * wind_speed_80m**3      # W/m²

# ── Output ─────────────────────────────────────────────────────────────────
print(f"Location: {latitude_deg:.1f}°N  (clearness index kt = {kt:.2f})")
print()
print("Solar resource:")
print(f"  Annual GHI        : {annual_ghi_total:,.0f} kWh/m²/year")
print(f"  Peak sun hours    : {annual_ghi_total/365:.2f} h/day (annual average)")
print(f"  Panel efficiency  : {panel_eff*100:.0f}%")
print(f"  Capacity factor   : {cf_solar:.3f}  ({cf_solar*100:.1f}%)")
print()
print("Wind resource:")
print(f"  Mean wind speed   : {wind_speed_80m:.1f} m/s at 80m hub height")
print(f"  Power density     : {power_density:.0f} W/m² rotor area")
print(f"  Capacity factor   : {cf_wind:.3f}  ({cf_wind*100:.1f}%)")
print()
print("Comparison (at 1 MW nameplate):")
print(f"  Annual solar gen  : {cf_solar * 8760 * 1000:,.0f} kWh/year  (1 MW solar array)")
print(f"  Annual wind gen   : {cf_wind  * 8760 * 1000:,.0f} kWh/year  (1 MW wind turbine)")
</code></pre></div>
<p>The numbers that emerge from this exercise reward careful attention. At Lethbridge (49.7°N, kt = 0.55), annual GHI is approximately 1,277 kWh/m²/year, yielding a solar capacity factor of about 2.9% — which sounds low until you note it corresponds to 254 MWh per year per MW of installed capacity. At Edmonton (53.6°N), the same calculation gives roughly 1,094 kWh/m² and a CF of 2.5%. The 15% gap between Lethbridge and Edmonton in annual solar generation is a direct consequence of the latitude-driven change in solar zenith angle compounded over 365 days.</p>
<p>For wind, the sensitivity to speed is the dominant message. Dropping from the Pincher Creek mean of 8.5 m/s to a central prairie site at 6.0 m/s changes the estimated capacity factor from 44% to 22%. That difference, applied to a 300 MW project generating over a 25-year life, is the difference between a project that clears its required rate of return and one that does not. The cubic law is not an abstraction — it is the reason the Crowsnest Pass wind corridor attracts developers despite its more difficult transmission access.</p>
</section>
<section id="the-resource-is-not-the-constraint" class="level2">
<h2 class="anchored" data-anchor-id="the-resource-is-not-the-constraint">The resource is not the constraint</h2>
<p>This essay has established three things. First, Alberta’s solar resource is competitive by international standards: Lethbridge’s 1,280 kWh/m²/year GHI exceeds southern Germany’s, and the province’s clearness index of 0.55–0.58 reflects its dry, continental climate. Second, Alberta’s wind resource is dramatically geographically concentrated: the Chinook belt along the Rocky Mountain front produces capacity factors of 35–45%, while the central and northern prairie yields 20–30%. Third, both resources are most abundant in the southwest corner of the province — precisely the corner that is least well served by the transmission infrastructure that was built to connect an industrial heartland based on coal and oil sands to Edmonton and Calgary.</p>
<p>The resource is not the constraint. Enough wind and solar potential exists in southern Alberta to supply the province’s electricity demand many times over, at capacity factors that compare favourably with most of Europe and the upper midwest of the United States. What constrains deployment is the capital-intensive, time-consuming, and institutionally complicated process of connecting that potential to the grid, pricing the electricity it produces in a volatile merchant market, and attracting the financing to build projects that are exposed to real-time pool prices that ranged from near zero to $999/MWh in recent years.</p>
<p>Those are questions of economics, not geography. And economics — specifically the LCOE framework that lets analysts compare wind, solar, storage, and gas generation on a common dollar-per-megawatt-hour basis — is the subject of the next essay in this cluster.</p>
<p><em>The pipeline cluster (P1–P5) showed how Alberta’s hydrocarbon resource is physically extracted, moved, and priced. The renewable transition begins with the same first question: where is the resource, and what does the geography tell us about where generation will concentrate? R2 will build the LCOE model from first principles and use it to compare wind, solar, and storage economics — identifying the transmission and capital constraints that determine where projects actually get built.</em></p>
<hr>
<p><em>Sources: NRCan Solar Atlas (solar.nrcan.gc.ca); Environment Canada Wind Atlas; AESO 2024 Annual Electricity Data Book; AESO Long-term Transmission Plan.</em></p>


</section>

</main> <!-- /main -->
<!-- Wayward House — book theme: footer + behaviour JS -->

<footer class="wh-bk-ftr" role="contentinfo">
  <div class="wh-bk-ftr__inner">

    <div class="wh-bk-ftr__brand">
      <div class="wh-bk-ftr__logo">Wayward<span>·</span>House</div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wh-bk-ftr__col" aria-labelledby="ftr-read">
      <h2 id="ftr-read">Read</h2>
      <a href="https://wayward.house/essays/">Essays</a>
      <a href="https://wayward.house/signals/">System Signals</a>
      <a href="https://wayward.house/topics/">Topics</a>
    </nav>

    <nav class="wh-bk-ftr__col" aria-labelledby="ftr-learn">
      <h2 id="ftr-learn">Learn</h2>
      <a href="https://wayward.house/library/">Library</a>
      <a href="https://wayward.house/computational-geography/">Computational Geography</a>
      <a href="https://wayward.house/mathematics/">Mathematics</a>
    </nav>

    <nav class="wh-bk-ftr__col" aria-labelledby="ftr-site">
      <h2 id="ftr-site">Site</h2>
      <a href="https://wayward.house/about/">About</a>
      <a href="https://wayward.house/start-here/">Start Here</a>
      <a href="https://wayward.house/privacy/">Privacy</a>
      <a href="https://wayward.house/terms/">Terms</a>
    </nav>

  </div>
  <div class="wh-bk-ftr__base">
    <span>© 2026 Wayward House · Paul Hobson</span>
    <span>CC BY 4.0 · MIT code</span>
  </div>
</footer>

<!-- Back-to-top button -->
<button class="wh-bk-top" type="button" aria-label="Back to top" hidden="">
  <span aria-hidden="true">↑</span>
</button>

<script>
(function () {
  'use strict';

  /* ── 0. Hoist footer + back-to-top to <body> for full-width layout ───── *
   *  include-after-body lands inside #quarto-document-content, which sits  *
   *  alongside the sidebar column. Moving both elements to document.body   *
   *  lets them span the full viewport width.                                */
  var _ftr = document.querySelector('.wh-bk-ftr');
  var _top = document.querySelector('.wh-bk-top');
  if (_ftr) document.body.appendChild(_ftr);
  if (_top) document.body.appendChild(_top);

  /* ── 1. Sidebar: hide Quarto's built-in navbar chrome ───────────────── */
  var hdr = document.querySelector('#quarto-header, header.navbar');
  if (hdr) hdr.style.display = 'none';

  /* ── 2. Desktop sidebar: persist open/closed state ─────────────────── */
  var STORAGE_KEY = 'wh-book-sidebar';
  var media       = window.matchMedia('(min-width: 992px)');
  var body        = document.body;

  function setSidebar(open) {
    body.classList.toggle('wh-sidebar-open',     open);
    body.classList.toggle('wh-sidebar-collapsed', !open);
    try { localStorage.setItem(STORAGE_KEY, open ? '1' : '0'); } catch (_) {}
  }

  function initSidebar() {
    if (!media.matches) {
      body.classList.remove('wh-sidebar-open', 'wh-sidebar-collapsed');
      return;
    }
    var stored;
    try { stored = localStorage.getItem(STORAGE_KEY); } catch (_) {}
    setSidebar(stored === '0' ? false : true); // default open
  }

  /* Wire the WH menu button AND Quarto's own toggle buttons */
  document.addEventListener('click', function (e) {
    var btn = e.target.closest(
      '.wh-bk-menu-btn, [data-bs-target=".quarto-sidebar-collapse-item"]'
    );
    if (!btn || !media.matches) return;
    e.preventDefault();
    e.stopPropagation();
    setSidebar(body.classList.contains('wh-sidebar-collapsed'));
  });

  /* Close sidebar when glass overlay is tapped on mobile */
  var glass = document.getElementById('quarto-sidebar-glass');
  if (glass) {
    glass.addEventListener('click', function (e) {
      if (media.matches) return;
      e.preventDefault();
    });
  }

  (media.addEventListener
    ? function (fn) { media.addEventListener('change', fn); }
    : function (fn) { media.addListener(fn); }
  )(initSidebar);

  initSidebar();

  /* ── 3. Sidebar title link → site home ─────────────────────────────── */
  var sidebar = document.getElementById('quarto-sidebar');
  if (sidebar) {
    var titleA = sidebar.querySelector('.sidebar-title a');
    if (titleA) titleA.href = 'https://wayward.house/';
  }

  /* ── 4. Back-to-top button ──────────────────────────────────────────── */
  var topBtn   = document.querySelector('.wh-bk-top');
  var ticking  = false;
  var reduced  = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  function updateTop() {
    if (!topBtn) return;
    var scrolled  = window.scrollY || document.documentElement.scrollTop || 0;
    var longPage  = document.documentElement.scrollHeight > window.innerHeight * 1.5;
    var threshold = Math.max(380, window.innerHeight * 0.6);
    topBtn.hidden = !(longPage && scrolled > threshold);
    ticking = false;
  }

  if (topBtn) {
    topBtn.hidden = true;
    topBtn.addEventListener('click', function () {
      window.scrollTo({ top: 0, behavior: reduced ? 'auto' : 'smooth' });
    });
    window.addEventListener('scroll',  function () {
      if (!ticking) { requestAnimationFrame(updateTop); ticking = true; }
    }, { passive: true });
    window.addEventListener('resize', updateTop, { passive: true });
    updateTop();
  }

  /* ── 5. Suppress Quarto's native page-footer ────────────────────────── */
  var qtFtr = document.querySelector('footer.page-footer');
  if (qtFtr) qtFtr.style.display = 'none';

})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../economic-systems/integrated-network.html" class="pagination-link" aria-label="The Integrated Network">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">The Integrated Network</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../economic-systems/alberta-renewable-economics.html" class="pagination-link" aria-label="The Economics of Clean Generation">
        <span class="nav-page-text"><span class="chapter-title">The Economics of Clean Generation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>