<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-10">

<title>The Integrated Network – Computational Geography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-640605f58ae58ee79329c070719e555b.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script>
  (function () {
    document.documentElement.dataset.theme = 'light';
    document.documentElement.dataset.brand = 'wayward';
    try {
      localStorage.removeItem('theme');
    } catch (err) {
      void err;
    }
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-math tag-hash-pyodide">


<header id="title-block-header">
<h1 class="title"><span class="chapter-title">The Integrated Network</span></h1>
<p class="subtitle">Max-flow, min-cut, and the full netback price surface across Alberta’s export corridors</p>

<p class="date">2026-03-10</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#before-you-start" id="toc-before-you-start">Before You Start</a></li>
  <li><a href="#the-network-as-a-directed-graph" id="toc-the-network-as-a-directed-graph">The network as a directed graph</a></li>
  <li><a href="#max-flow-and-the-binding-constraint" id="toc-max-flow-and-the-binding-constraint">Max-flow and the binding constraint</a></li>
  <li><a href="#network-centrality-and-the-hardisty-problem" id="toc-network-centrality-and-the-hardisty-problem">Network centrality and the Hardisty problem</a></li>
  <li><a href="#the-netback-price-surface" id="toc-the-netback-price-surface">The netback price surface</a></li>
  <li><a href="#reference-implementation" id="toc-reference-implementation">Reference implementation</a></li>
  <li><a href="#run-it-yourself" id="toc-run-it-yourself">Run it yourself</a></li>
  <li><a href="#where-next" id="toc-where-next">Where next?</a></li>
  </ul>
</nav>
<h2 id="before-you-start" class="anchored">Before You Start</h2>
<p><strong>You should know</strong><br>
That the crude, gas, NGL, and refined-products systems can all be represented as one network of nodes and constrained links.</p>
<p><strong>You will learn</strong><br>
How max-flow, min-cut, and netback-surface analysis expose Alberta’s export-system bottlenecks.</p>
<p><strong>Why this matters</strong><br>
A system-level network view reveals vulnerabilities that commodity-by-commodity analysis can miss.</p>
<p><strong>If this gets hard, focus on…</strong><br>
The main question: which links actually limit total export flow?</p>
<p>Alberta’s pipeline network exports more than 3 million barrels of oil per day — but that capacity is concentrated through a single hub, at a single location, in a way that any graph theorist would immediately recognise as a structural vulnerability.</p>
<p>The preceding four essays developed the physics and economics of each commodity system independently: Darcy-Weisbach for crude, mass balance for NGL, Weymouth for gas, Cola and batch scheduling for refined products. This essay does something different. It assembles all four systems into a single directed capacity graph, applies the Ford-Fulkerson max-flow min-cut theorem to identify the network’s binding export constraints, and maps the netback price surface — the function that converts a market price at any destination into a wellhead value at any Alberta production site.</p>
<p>The mathematics reveals a structure that is simultaneously more capable and more concentrated than either side of the pipeline debate typically acknowledges.</p>
<h2 id="the-network-as-a-directed-graph" class="anchored">The network as a directed graph</h2>
<p>A <strong>directed graph</strong> (digraph) represents a pipeline network as a set of nodes connected by directed edges with capacity constraints. The mapping is direct:</p>
<ul>
<li><strong>Nodes</strong> — production aggregates, pipeline hubs, border crossings, and market sinks</li>
<li><strong>Directed edges</strong> — individual pipelines, with direction indicating permitted flow direction</li>
<li><strong>Edge weights</strong> — nameplate capacity in thousands of barrels per day (Mbbl/day)</li>
</ul>
<p>The Alberta crude export network, simplified for analysis, has seven nodes:</p>
<table>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr>
<th>
Node
</th>
<th>
Description
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
PROD
</td>
<td>
Alberta wellhead aggregate — upstream production
</td>
</tr>
<tr>
<td>
EDMT
</td>
<td>
Edmonton hub — primary origin for TMX and refined products; NGL/condensate gathering
</td>
</tr>
<tr>
<td>
HARD
</td>
<td>
Hardisty hub — primary crude export origin; Mainline, Keystone origin point
</td>
</tr>
<tr>
<td>
SUPR
</td>
<td>
Superior, WI — Enbridge Mainline eastern terminus; connection to Flanagan South/Seaway
</td>
</tr>
<tr>
<td>
CUSH
</td>
<td>
Cushing, OK — WTI delivery hub; Keystone terminus
</td>
</tr>
<tr>
<td>
BURN
</td>
<td>
Burnaby, BC — Trans Mountain terminus; Pacific tanker loading
</td>
</tr>
<tr>
<td>
GULF / SARN / PCFC
</td>
<td>
Market sinks — U.S. Gulf Coast, Ontario/Quebec refineries, Pacific Basin
</td>
</tr>
</tbody>
</table>
<p>The directed edges and their approximate 2024 capacities:</p>
<table>
<thead>
<tr>
<th>
Edge
</th>
<th>
Capacity (Mbbl/day)
</th>
<th>
System
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
PROD → EDMT
</td>
<td>
3,800
</td>
<td>
Upstream gathering to Edmonton
</td>
</tr>
<tr>
<td>
PROD → HARD
</td>
<td>
3,800
</td>
<td>
Upstream gathering to Hardisty
</td>
</tr>
<tr>
<td>
EDMT → HARD
</td>
<td>
3,500
</td>
<td>
Enbridge Mainline gathering
</td>
</tr>
<tr>
<td>
EDMT → BURN
</td>
<td>
890
</td>
<td>
Trans Mountain (TMX, post-expansion)
</td>
</tr>
<tr>
<td>
HARD → SUPR
</td>
<td>
2,850
</td>
<td>
Enbridge Mainline (Lines 2–13)
</td>
</tr>
<tr>
<td>
HARD → CUSH
</td>
<td>
590
</td>
<td>
Keystone
</td>
</tr>
<tr>
<td>
SUPR → GULF
</td>
<td>
2,850
</td>
<td>
Flanagan South + Seaway → Gulf Coast
</td>
</tr>
<tr>
<td>
SUPR → SARN
</td>
<td>
500
</td>
<td>
Enbridge Line 9 → Ontario/Quebec
</td>
</tr>
<tr>
<td>
CUSH → GULF
</td>
<td>
590
</td>
<td>
Keystone extension to Gulf
</td>
</tr>
<tr>
<td>
BURN → PCFC
</td>
<td>
890
</td>
<td>
Pacific tanker capacity
</td>
</tr>
</tbody>
</table>
<p><em>Sources: CER Pipeline Profiles; Enbridge annual reports; Trans Mountain Corporation; TC Energy disclosures. Capacities are nameplate; actual utilisation varies by contract and maintenance.</em></p>
<figure class="cg-ill">
<div class="cg-ill__frame" data-markdown="1">
<div class="cg-ill__eyebrow">
Network Logic
</div>
<h3 class="cg-ill__title anchored">
Max Flow Is Limited By A Small Set Of Export Corridors
</h3>
<p class="cg-ill__lede">
A network view makes the bottleneck visible. Alberta production can fan out to multiple hubs, but only a few downstream corridors actually control how much volume reaches market.
</p>
<div class="cg-ill__network-grid">
<div class="cg-ill__network-diagram">
<div class="cg-ill__network-node cg-ill__network-node--source" style="left:4%;top:34%;">
PROD
</div>
<div class="cg-ill__network-node" style="left:26%;top:14%;">
EDMT
</div>
<div class="cg-ill__network-node" style="left:26%;top:56%;">
HARD
</div>
<div class="cg-ill__network-node" style="left:52%;top:16%;">
BURN
</div>
<div class="cg-ill__network-node" style="left:52%;top:54%;">
SUPR
</div>
<div class="cg-ill__network-node" style="left:52%;top:78%;">
CUSH
</div>
<div class="cg-ill__network-node cg-ill__network-node--sink" style="left:79%;top:16%;">
PCFC
</div>
<div class="cg-ill__network-node cg-ill__network-node--sink" style="left:79%;top:48%;">
SARN
</div>
<div class="cg-ill__network-node cg-ill__network-node--sink" style="left:79%;top:72%;">
GULF
</div>
<div class="cg-ill__network-edge" style="left:13%;top:29%;width:16%;transform:rotate(-22deg);">
3800
</div>
<div class="cg-ill__network-edge" style="left:13%;top:51%;width:16%;transform:rotate(24deg);">
3800
</div>
<div class="cg-ill__network-edge" style="left:35%;top:29%;width:15%;transform:rotate(8deg);">
890
</div>
<div class="cg-ill__network-edge cg-ill__network-edge--bottleneck" style="left:35%;top:56%;width:15%;transform:rotate(-8deg);">
2850
</div>
<div class="cg-ill__network-edge cg-ill__network-edge--bottleneck" style="left:35%;top:72%;width:15%;transform:rotate(8deg);">
590
</div>
<div class="cg-ill__network-edge" style="left:61%;top:22%;width:15%;transform:rotate(0deg);">
890
</div>
<div class="cg-ill__network-edge" style="left:61%;top:54%;width:15%;transform:rotate(-7deg);">
500
</div>
<div class="cg-ill__network-edge cg-ill__network-edge--bottleneck" style="left:61%;top:66%;width:15%;transform:rotate(12deg);">
2850
</div>
<div class="cg-ill__network-edge cg-ill__network-edge--bottleneck" style="left:61%;top:79%;width:15%;transform:rotate(-6deg);">
590
</div>
<div class="cg-ill__network-legend">
<span><i class="cg-ill__network-swatch"></i> regular corridor</span> <span><i class="cg-ill__network-swatch cg-ill__network-swatch--bottleneck"></i> cut-defining corridor</span> <span>numbers are approximate capacity in Mbbl/day</span>
</div>
</div>
<div class="cg-ill__card">
<h4 class="anchored">
Why this matters
</h4>
<ul>
<li>
Upstream gathering is large, but export capacity narrows quickly downstream.
</li>
<li>
The bottleneck is not one pipe everywhere; it is the set of links that define the minimum cut.
</li>
<li>
TMX creates Pacific optionality, but Hardisty-centered crude still depends heavily on the Superior and Gulf routes.
</li>
<li>
That concentration is why netbacks and outage risk vary sharply across the network.
</li>
</ul>
</div>
</div>
</div>
<figcaption>
A directed-capacity network makes min-cut reasoning visible: the critical question is which constrained export links separate Alberta production from end markets.
</figcaption>
</figure>
<h2 id="max-flow-and-the-binding-constraint" class="anchored">Max-flow and the binding constraint</h2>
<p>The <strong>Ford-Fulkerson max-flow min-cut theorem</strong> states:</p>
<p>max_flow(<em>s</em>, <em>t</em>) = min_cut(<em>G</em>, <em>s</em>, <em>t</em>) = min<sub>(<em>S</em>, <em>T</em>) ∈ 𝒞</sub>∑<sub>(<em>u</em>, <em>v</em>): <em>u</em> ∈ <em>S</em>, <em>v</em> ∈ <em>T</em></sub><em>c</em>(<em>u</em>, <em>v</em>)</p>
<table>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr>
<th>
Symbol
</th>
<th>
Meaning
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<span class="math inline"><em>G</em></span>
</td>
<td>
Directed graph representing the pipeline network
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>s</em></span>
</td>
<td>
Source node (Alberta production)
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>t</em></span>
</td>
<td>
Sink node (export destination)
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>S</em>, <em>T</em></span>
</td>
<td>
Partition of nodes: source-side and sink-side
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>c</em>(<em>u</em>, <em>v</em>)</span>
</td>
<td>
Capacity of directed edge <span class="math inline">(<em>u</em>, <em>v</em>)</span>
</td>
</tr>
<tr>
<td>
<span class="math inline">min_cut</span>
</td>
<td>
Minimum total capacity of edges crossing from <span class="math inline"><em>S</em></span> to <span class="math inline"><em>T</em></span>
</td>
</tr>
</tbody>
</table>
<p>The theorem’s power is in what it reveals about network structure: <strong>the bottleneck is always identifiable as a cut</strong> — a set of edges whose combined removal would disconnect production from market. Removing any single edge with capacity less than the max-flow reduces that flow by exactly the removed capacity; removing an edge not in the min-cut has no effect on max-flow at all.</p>
<p>For the Alberta crude network, the <strong>Edmonds-Karp algorithm</strong> (a BFS-based implementation of Ford-Fulkerson) finds these results:</p>
<ul>
<li><strong>Max-flow to Gulf Coast:</strong> ~3,440 Mbbl/day (limited by SUPR → GULF = 2,850 + CUSH → GULF = 590)</li>
<li><strong>Max-flow to Pacific (PCFC):</strong> 890 Mbbl/day (EDMT → BURN = BURN → PCFC = 890)</li>
<li><strong>Max-flow to Ontario (SARN):</strong> 500 Mbbl/day (SUPR → SARN = 500)</li>
<li><strong>Total network export capacity:</strong> ~4,830 Mbbl/day</li>
</ul>
<p>The min-cut for the total network passes through the edges immediately downstream of the HARD and EDMT nodes — the edges leaving Alberta. This is the graph-theoretic representation of the <strong>export constraint</strong>: Alberta’s pipelines can carry everything the province produces to one or another destination, but the set of edges leaving the province is the binding cut.</p>
<p><strong>Scenario: Keystone cancellation.</strong> Setting HARD → CUSH = 0 reduces Gulf max-flow from 3,440 to 2,850 Mbbl/day — a reduction of exactly 590, because that edge was in the min-cut. The theorem guarantees this result without simulation.</p>
<p><strong>Scenario: Second TMX-scale Pacific pipeline.</strong> Setting EDMT → BURN = 1,200 Mbbl/day adds 310 Mbbl/day to Pacific capacity, but does not change the binding constraint on Gulf flows — those are limited by a different cut entirely. The two corridors compete for Edmonton production volumes (shared PROD → EDMT edge) but not for capacity at any common downstream node.</p>
<h2 id="network-centrality-and-the-hardisty-problem" class="anchored">Network centrality and the Hardisty problem</h2>
<p><strong>Betweenness centrality</strong> measures a node’s structural importance by counting how many shortest paths between all node pairs pass through it:</p>
<p><span class="math display">
C_B(v) = \sum\_{s \neq v \neq t} \frac{\sigma(s,t \mid v)}{\sigma(s,t)}
</span></p>
<table>
<thead>
<tr>
<th>
Symbol
</th>
<th>
Meaning
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<span class="math inline"><em>C</em><sub><em>B</em></sub>(<em>v</em>)</span>
</td>
<td>
Betweenness centrality of node <span class="math inline"><em>v</em></span>
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>σ</em>(<em>s</em>, <em>t</em>)</span>
</td>
<td>
Total number of shortest paths from <span class="math inline"><em>s</em></span> to <span class="math inline"><em>t</em></span>
</td>
</tr>
<tr>
<td>
<span class="math inline"><em>σ</em>(<em>s</em>, <em>t</em> ∣ <em>v</em>)</span>
</td>
<td>
Number of those paths passing through <span class="math inline"><em>v</em></span>
</td>
</tr>
</tbody>
</table>
<p><strong>Hardisty has near-maximum betweenness centrality</strong> in Alberta’s crude export network. Every path from Alberta production to any Gulf or eastern market routes through HARD. Edmonton routes the Pacific corridor (EDMT → BURN) but not the Mainline or Keystone flows. Hardisty is on all paths to Gulf and Sarnia.</p>
<p>The operational implications are significant. A disruption at Hardisty — fire, flood, equipment failure, regulatory order — is a <strong>systemic event</strong> affecting all downstream flows simultaneously. A disruption at Edmonton affects only the TMX corridor. The difference is one of network centrality, not just geography.</p>
<p>The <strong>Hardisty tank farm</strong> addresses this concentration risk through storage buffering. With approximately 35 million barrels of crude storage capacity across multiple tank farm operators (Enbridge, Gibson Energy, and others), Hardisty holds enough inventory to sustain downstream pipeline flows for roughly 10–12 days at full throughput even with no upstream injection. This is not coincidence — the storage capacity was built in part to provide resilience against exactly the kind of upstream disruption that Hardisty’s structural position makes consequential.</p>
<h2 id="the-netback-price-surface" class="anchored">The netback price surface</h2>
<p>The <strong>netback price surface</strong> is a function of destination and time:</p>
<p><em>P</em><sub>wellhead</sub>(<em>d</em>, <em>t</em>) = <em>P</em><sub>market</sub>(<em>d</em>, <em>t</em>) − <em>T</em>(<em>d</em>) − <em>A</em>(<em>d</em>)</p>
<p>where <em>d</em> = destination, <em>t</em> = time, <em>T</em>(<em>d</em>) is the transport tariff, and <em>A</em>(<em>d</em>) is the quality adjustment. At any given moment, the surface has one value for each accessible destination.</p>
<p>At approximate 2023 market conditions:</p>
<table>
<thead>
<tr>
<th>
Route
</th>
<th>
Market price
</th>
<th>
Tariff
</th>
<th>
Quality adj
</th>
<th>
Netback
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Gulf Coast (Keystone)
</td>
<td>
$70.00
</td>
<td>
$8.00
</td>
<td>
$14.00
</td>
<td>
<strong>$48.00</strong>
</td>
</tr>
<tr>
<td>
Gulf Coast (Mainline)
</td>
<td>
$70.00
</td>
<td>
$5.00
</td>
<td>
$14.00
</td>
<td>
<strong>$51.00</strong>
</td>
</tr>
<tr>
<td>
Pacific / TMX
</td>
<td>
$74.00
</td>
<td>
$11.00
</td>
<td>
$10.00
</td>
<td>
<strong>$53.00</strong>
</td>
</tr>
<tr>
<td>
Ontario (Sarnia)
</td>
<td>
$68.00
</td>
<td>
$4.50
</td>
<td>
$14.00
</td>
<td>
<strong>$49.50</strong>
</td>
</tr>
</tbody>
</table>
<p>The Pacific row — added by the TMX expansion — dominates the surface in this scenario. Two factors combine: Pacific Basin refineries (Japan, Korea, China) price Alberta heavy crude at a smaller quality discount ($10/bbl versus $14/bbl at Gulf Coast) because their refinery configurations are better matched to heavy sour feedstocks, and the Pacific market price in this scenario is $4/bbl above Gulf Coast. Together these offset TMX’s higher tariff ($11 versus $5 on the Mainline).</p>
<p>The surface is not static. It changes continuously with market prices, the WCS-WTI differential, exchange rates (since TMX revenues are in USD while AECO is in CAD/GJ), and tariff adjustments. A producer with access to multiple corridors faces an optimisation problem: which route maximises netback today? Long-term ship-or-pay contracts foreclose this optimisation for committed volumes, which is why pipeline access diversification — the ability to move barrels across multiple systems — is itself valuable, beyond the capacity it provides.</p>
<h2 id="reference-implementation" class="anchored">Reference implementation</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> defaultdict, deque</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ── BFS augmenting path search ─────────────────────────────────────────────</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> bfs_find_path(graph: <span class="bu">dict</span>, source: <span class="bu">str</span>, sink: <span class="bu">str</span>, parent: <span class="bu">dict</span>) <span class="op">-&gt;</span> <span class="bu">bool</span>:</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""BFS to find an augmenting path from source to sink in residual graph."""</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    visited <span class="op">=</span> {source}</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    queue   <span class="op">=</span> deque([source])</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> queue:</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>        u <span class="op">=</span> queue.popleft()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> v <span class="kw">in</span> graph[u]:</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> v <span class="kw">not</span> <span class="kw">in</span> visited <span class="kw">and</span> graph[u][v] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                visited.add(v)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                parent[v] <span class="op">=</span> u</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> v <span class="op">==</span> sink:</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">return</span> <span class="va">True</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>                queue.append(v)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">False</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> edmonds_karp(graph: <span class="bu">dict</span>, source: <span class="bu">str</span>, sink: <span class="bu">str</span>) <span class="op">-&gt;</span> <span class="bu">tuple</span>:</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">    Edmonds-Karp algorithm (BFS-based Ford-Fulkerson).</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns (max_flow_value, min_cut_edges).</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co">    ----------</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co">    graph  : adjacency dict — graph[u][v] = capacity of edge u→v</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co">    source : source node name</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">    sink   : sink node name</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co">    -------</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co">    (float, list) : (maximum flow value, list of min-cut edge tuples)</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    residual <span class="op">=</span> defaultdict(<span class="kw">lambda</span>: defaultdict(<span class="bu">float</span>))</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> u <span class="kw">in</span> graph:</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> v, cap <span class="kw">in</span> graph[u].items():</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>            residual[u][v] <span class="op">+=</span> cap</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    max_flow_val <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    parent       <span class="op">=</span> {}</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> bfs_find_path(residual, source, sink, parent):</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Find bottleneck</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>        path_flow <span class="op">=</span> <span class="bu">float</span>(<span class="st">"inf"</span>)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>        v <span class="op">=</span> sink</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>        <span class="cf">while</span> v <span class="op">!=</span> source:</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>            u <span class="op">=</span> parent[v]</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>            path_flow <span class="op">=</span> <span class="bu">min</span>(path_flow, residual[u][v])</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>            v <span class="op">=</span> u</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Update residuals</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>        v <span class="op">=</span> sink</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>        <span class="cf">while</span> v <span class="op">!=</span> source:</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>            u <span class="op">=</span> parent[v]</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>            residual[u][v] <span class="op">-=</span> path_flow</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>            residual[v][u] <span class="op">+=</span> path_flow</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>            v <span class="op">=</span> u</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>        max_flow_val <span class="op">+=</span> path_flow</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>        parent <span class="op">=</span> {}</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Find min-cut edges</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>    visited <span class="op">=</span> <span class="bu">set</span>()</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>    queue <span class="op">=</span> deque([source])</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> queue:</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>        u <span class="op">=</span> queue.popleft()</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> u <span class="kw">in</span> visited:</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>        visited.add(u)</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> v <span class="kw">in</span> residual[u]:</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> residual[u][v] <span class="op">&gt;</span> <span class="dv">0</span> <span class="kw">and</span> v <span class="kw">not</span> <span class="kw">in</span> visited:</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>                queue.append(v)</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>    min_cut_edges <span class="op">=</span> [(u, v, graph.get(u, {}).get(v, <span class="dv">0</span>))</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>                     <span class="cf">for</span> u <span class="kw">in</span> visited <span class="cf">for</span> v <span class="kw">in</span> graph.get(u, {})</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>                     <span class="cf">if</span> v <span class="kw">not</span> <span class="kw">in</span> visited <span class="kw">and</span> graph[u][v] <span class="op">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> max_flow_val, min_cut_edges</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Alberta pipeline network — capacities in 1,000 bbl/day ────────────────</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>NETWORK <span class="op">=</span> {</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PROD"</span>:  {<span class="st">"EDMT"</span>: <span class="dv">3_800</span>, <span class="st">"HARD"</span>: <span class="dv">3_800</span>},</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>    <span class="st">"EDMT"</span>:  {<span class="st">"HARD"</span>: <span class="dv">3_500</span>, <span class="st">"BURN"</span>: <span class="dv">890</span>},</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>    <span class="st">"HARD"</span>:  {<span class="st">"SUPR"</span>: <span class="dv">2_850</span>, <span class="st">"CUSH"</span>: <span class="dv">590</span>},</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SUPR"</span>:  {<span class="st">"GULF"</span>: <span class="dv">2_850</span>, <span class="st">"SARN"</span>: <span class="dv">500</span>},</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CUSH"</span>:  {<span class="st">"GULF"</span>: <span class="dv">590</span>},</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>    <span class="st">"BURN"</span>:  {<span class="st">"PCFC"</span>: <span class="dv">890</span>},</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>    <span class="st">"GULF"</span>:  {},</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SARN"</span>:  {},</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PCFC"</span>:  {},</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>source <span class="op">=</span> <span class="st">"PROD"</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>sinks  <span class="op">=</span> [<span class="st">"GULF"</span>, <span class="st">"SARN"</span>, <span class="st">"PCFC"</span>]</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Alberta crude export network — max-flow analysis"</span>)</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Capacities in 1,000 bbl/day</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sink <span class="kw">in</span> sinks:</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>    net <span class="op">=</span> {k: <span class="bu">dict</span>(v) <span class="cf">for</span> k, v <span class="kw">in</span> NETWORK.items()}</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>    mf, mc <span class="op">=</span> edmonds_karp(net, source, sink)</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Max flow PROD → </span><span class="sc">{</span>sink<span class="sc">:&lt;8}</span><span class="ss">: </span><span class="sc">{</span>mf<span class="sc">:&gt;6,.0f}</span><span class="ss"> Mbbl/day"</span>)</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  Min-cut edges: </span><span class="sc">{</span>[(u, v, <span class="bu">int</span>(c)) <span class="cf">for</span> u, v, c <span class="kw">in</span> mc]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="co"># Netback price surface</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Netback price surface — WCS crude, approximate 2023 conditions"</span>)</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Destination'</span><span class="sc">:&lt;24}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Market'</span><span class="sc">:&gt;8}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Tariff'</span><span class="sc">:&gt;8}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Quality'</span><span class="sc">:&gt;9}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Netback'</span><span class="sc">:&gt;9}</span><span class="ss">"</span>)</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>routes <span class="op">=</span> [</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Gulf Coast (Keystone)"</span>,   <span class="fl">70.0</span>,  <span class="fl">8.0</span>, <span class="fl">14.0</span>),</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Gulf Coast (Mainline)"</span>,   <span class="fl">70.0</span>,  <span class="fl">5.0</span>, <span class="fl">14.0</span>),</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Pacific (Burnaby / TMX)"</span>, <span class="fl">74.0</span>, <span class="fl">11.0</span>, <span class="fl">10.0</span>),</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"Ontario (Sarnia)"</span>,        <span class="fl">68.0</span>,  <span class="fl">4.5</span>, <span class="fl">14.0</span>),</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dest, market, tariff, quality <span class="kw">in</span> routes:</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>    netback <span class="op">=</span> market <span class="op">-</span> tariff <span class="op">-</span> quality</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>dest<span class="sc">:&lt;22}</span><span class="ss"> </span><span class="sc">{</span>market<span class="sc">:&gt;8.2f}</span><span class="ss"> </span><span class="sc">{</span>tariff<span class="sc">:&gt;8.2f}</span><span class="ss"> </span><span class="sc">{</span>quality<span class="sc">:&gt;9.2f}</span><span class="ss"> </span><span class="sc">{</span>netback<span class="sc">:&gt;9.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre><code>Alberta crude export network — max-flow analysis
Capacities in 1,000 bbl/day

Max flow PROD → GULF    :  3,440 Mbbl/day
  Min-cut edges: [('SUPR', 'GULF', 2850), ('CUSH', 'GULF', 590)]

Max flow PROD → SARN    :    500 Mbbl/day
  Min-cut edges: [('SUPR', 'SARN', 500)]

Max flow PROD → PCFC    :    890 Mbbl/day
  Min-cut edges: [('EDMT', 'BURN', 890)]

Netback price surface — WCS crude, approximate 2023 conditions
Destination              Market   Tariff   Quality   Netback
  Gulf Coast (Keystone)   70.00     8.00     14.00     48.00
  Gulf Coast (Mainline)   70.00     5.00     14.00     51.00
  Pacific (Burnaby / TMX) 74.00    11.00     10.00     53.00
  Ontario (Sarnia)        68.00     4.50     14.00     49.50</code></pre>
<h2 id="run-it-yourself" class="anchored">Run it yourself</h2>
<p>Two experiments illuminate the most important structural features of the network. First, set <code>HARD→CUSH</code> to 0 and observe the exact effect on Gulf max-flow: the theorem guarantees a reduction of precisely 590 Mbbl/day, no more, no less. Second, increase <code>EDMT→BURN</code> to 1,200 and observe that Pacific capacity grows by 310 Mbbl/day while Gulf capacity is unchanged — the two corridors share upstream capacity but not downstream bottlenecks.</p>
<div class="pyodide-cell"><pre><code class="language-python">from collections import defaultdict, deque

# ── Simplified Edmonds-Karp ────────────────────────────────────────────────
def bfs(graph, s, t, parent):
visited = {s}
q = deque([s])
while q:
u = q.popleft()
for v, cap in graph[u].items():
if v not in visited and cap &gt; 0:
visited.add(v); parent[v] = u; q.append(v)
if v == t: return True
return False

def max_flow(cap, s, t):
r = defaultdict(lambda: defaultdict(float))
for u, nbrs in cap.items():
for v, c in nbrs.items(): r[u][v] += c
flow = 0
while True:
p = {}
if not bfs(r, s, t, p): break
f = float('inf'); v = t
while v != s: u = p[v]; f = min(f, r[u][v]); v = u
v = t
while v != s: u = p[v]; r[u][v] -= f; r[v][u] += f; v = u
flow += f
return flow

# ── Network capacities (Mbbl/day) — change these ──────────────────────────
# Try: set HARD→CUSH to 0 (Keystone cancelled) and see effect on Gulf flows
# Try: increase EDMT→BURN to 1200 (another TMX-scale project) and check Pacific max-flow

NET = {
"PROD": {"EDMT": 3800, "HARD": 3800},
"EDMT": {"HARD": 3500, "BURN": 890},      # &lt;- Try BURN: 890 → 1200
"HARD": {"SUPR": 2850, "CUSH": 590},      # &lt;- Try CUSH: 590 → 0
"SUPR": {"GULF": 2850, "SARN": 500},
"CUSH": {"GULF": 590},
"BURN": {"PCFC": 890},
"GULF": {}, "SARN": {}, "PCFC": {},
}

# Max flow to each destination
print("Max-flow from Alberta production to each market sink:")
for sink in ["GULF", "SARN", "PCFC"]:
mf = max_flow(NET, "PROD", sink)
print(f"  → {sink}: {mf:,.0f} Mbbl/day")

# Aggregate (all sinks via supersink)
SUPER = {k: dict(v) for k, v in NET.items()}
for s in ["GULF", "SARN", "PCFC"]: SUPER[s]["SUPER"] = 9_999_999
total = max_flow(SUPER, "PROD", "SUPER")
print(f"\nTotal network export capacity: {total:,.0f} Mbbl/day")

# Netback price surface
print("\nNetback price surface (USD/bbl):")
print(f"{'Route':&lt;24} {'Market':&gt;8} {'Tariff':&gt;8} {'Quality':&gt;9} {'Netback':&gt;9}")
for dest, mkt, tar, qual in [
("Gulf Coast (Keystone)", 70.0,  8.0, 14.0),
("Gulf Coast (Mainline)", 70.0,  5.0, 14.0),
("Pacific / TMX",         74.0, 11.0, 10.0),
("Ontario (Sarnia)",      68.0,  4.5, 14.0),
]:
print(f"  {dest:&lt;22} {mkt:&gt;8.2f} {tar:&gt;8.2f} {qual:&gt;9.2f} {mkt-tar-qual:&gt;9.2f}")
</code></pre></div>
<h2 id="where-next" class="anchored">Where next?</h2>
<p>The five essays in this cluster have moved from individual pipe hydraulics — the pressure drop across a 30-inch steel pipe carrying dilbit at 2 m/s — through commodity-specific flow equations, to the integrated capacity network that carries Alberta’s hydrocarbons to continental and Pacific markets.</p>
<p>The system is larger, more capable, and more structurally concentrated than either side of the political debate about pipelines typically acknowledges. What the mathematics reveals is not a case for or against pipeline investment. It is a precise description of what the existing network can and cannot do: its maximum throughput to each market, its binding bottleneck cuts, the node whose failure would be most consequential, and the netback price each route offers at any given market condition.</p>
<p>That is what it means to model a geographic system rather than argue about it.</p>


<footer class="wayward-footer">
  <div class="wayward-footer__inner">
    <div class="wayward-footer__brand">
      <div class="wayward-footer__logo">WaywardHouse<span>.</span></div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wayward-footer__group" aria-labelledby="footer-reading">
      <h2 id="footer-reading" class="anchored">Reading</h2>
      <a href="https://wayward.house/articles/">Articles</a>
      <a href="https://wayward.house/learn/">Library</a>
      <a href="https://wayward.house/archive.html">Archive</a>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-site">
      <h2 id="footer-site" class="anchored">Site</h2>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
      <a href="https://wayward.house/about.html">About</a>
      <a href="https://wayward.house/contact.html">Contact</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-resources">
      <h2 id="footer-resources" class="anchored">Resources</h2>
      <a href="https://wayward.house/topics/">All Topics</a>
      <a href="https://wayward.house/privacy.html">Privacy Policy</a>
      <a href="https://wayward.house/terms.html">Terms of Use</a>
    </nav>
  </div>
</footer>

<script type="module" src="../assets/dist/main.js"></script>
<script type="module" src="../assets/js/core.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>