<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-05">
<meta name="description" content="Lake Winnipeg receives phosphorus from the entire southern Manitoba watershed — agriculture, cities, and atmospheric deposition — and has responded with expanding blue-green algae blooms that now cover thousands of square kilometres. This essay derives the Vollenweider phosphorus loading model, quantifies the phosphorus-chlorophyll relationship, explains how summer stratification creates hypolimnetic oxygen depletion, and builds the Total Maximum Daily Load framework that allocates loading reductions among point and nonpoint sources.">

<title>Nutrient Dynamics and Lake Eutrophication – Computational Geography</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-640605f58ae58ee79329c070719e555b.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script>
  (function () {
    document.documentElement.dataset.theme = 'light';
    document.documentElement.dataset.brand = 'wayward';
    try {
      localStorage.removeItem('theme');
    } catch (err) {
      void err;
    }
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-math tag-hash-viz">


<header id="title-block-header">
<h1 class="title"><span class="chapter-title">Nutrient Dynamics and Lake Eutrophication</span></h1>
<p class="subtitle">Phosphorus loading, Vollenweider model, stratification, and TMDL frameworks</p>

<p class="date">2026-03-05</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#before-you-start-this-investigation" id="toc-before-you-start-this-investigation">Before You Start This Investigation</a></li>
  <li><a href="#the-question" id="toc-the-question">1. The Question</a></li>
  <li><a href="#the-conceptual-model" id="toc-the-conceptual-model">2. The Conceptual Model</a></li>
  <li><a href="#building-the-mathematical-model" id="toc-building-the-mathematical-model">3. Building the Mathematical Model</a>
  <ul>
  <li><a href="#lake-phosphorus-mass-balance" id="toc-lake-phosphorus-mass-balance">3.1 Lake Phosphorus Mass Balance</a></li>
  <li><a href="#phosphorus-loading-budget" id="toc-phosphorus-loading-budget">3.2 Phosphorus Loading Budget</a></li>
  <li><a href="#phosphorus-chlorophyll-relationship" id="toc-phosphorus-chlorophyll-relationship">3.3 Phosphorus-Chlorophyll Relationship</a></li>
  <li><a href="#thermal-stratification-and-hypolimnetic-oxygen-depletion" id="toc-thermal-stratification-and-hypolimnetic-oxygen-depletion">3.4 Thermal Stratification and Hypolimnetic Oxygen Depletion</a></li>
  <li><a href="#total-maximum-daily-load-tmdl" id="toc-total-maximum-daily-load-tmdl">3.5 Total Maximum Daily Load (TMDL)</a></li>
  </ul></li>
  <li><a href="#worked-example-by-hand" id="toc-worked-example-by-hand">4. Worked Example by Hand</a></li>
  <li><a href="#computational-implementation" id="toc-computational-implementation">5. Computational Implementation</a></li>
  <li><a href="#visualization" id="toc-visualization">6. Visualization</a></li>
  <li><a href="#interpretation" id="toc-interpretation">7. Interpretation</a></li>
  <li><a href="#what-could-go-wrong" id="toc-what-could-go-wrong">8. What Could Go Wrong?</a></li>
  <li><a href="#summary" id="toc-summary">9. Summary</a></li>
  <li><a href="#math-refresher" id="toc-math-refresher">Math Refresher</a></li>
  </ul>
</nav>
<p>Lake Winnipeg is the world’s tenth-largest freshwater lake by surface area. It is also one of the world’s most rapidly eutrophying large lakes. Total phosphorus concentrations have increased more than 10-fold in the south basin since the 1960s, driven primarily by agricultural runoff from the Red River watershed and municipal discharges from Winnipeg’s wastewater treatment plants. The response has been an explosion of Aphanizomenon and Dolichospermum (formerly Anabaena) cyanobacteria — blue-green algae that produce toxins dangerous to livestock, pets, and children.</p>
<p>The quantitative framework for understanding this transition from clear oligotrophic lake to turbid hypereutrophic system is the <strong>Vollenweider model</strong> — a mass balance approach that links watershed phosphorus loading to lake phosphorus concentration, and lake phosphorus concentration to algal biomass.</p>
<hr>
<h2 id="before-you-start-this-investigation" class="anchored">Before You Start This Investigation</h2>
<p><strong>You should have completed:</strong> - Pathway B: Soil Moisture Dynamics - Pathway B: Photosynthesis &amp; Light Response - Methods Reference: Differential Equations</p>
<p><strong>You will learn:</strong> - How phosphorus loading, lake response, stratification, and TMDL allocation fit into one eutrophication framework.</p>
<p><strong>Estimated time:</strong> 12 hours</p>
<p><strong>See also:</strong> Pathway B, Soil Moisture — extend to coupled nutrient-water dynamics</p>
<p><strong>Why this matters:</strong> Lake eutrophication is a mass-balance problem with direct consequences for oxygen, toxins, and water quality policy.</p>
<p><strong>If this gets hard, focus on:</strong> The feedback loop: more phosphorus means more algae, which can mean less deep-water oxygen, which can release even more phosphorus.</p>
<h2 id="the-question" class="anchored">1. The Question</h2>
<p>How does phosphorus enter a lake and what controls its steady-state concentration? How does phosphorus concentration predict algal biomass (chlorophyll-a)? Why does summer stratification create oxygen depletion at the bottom? And how does the TMDL framework allocate loading reductions among sources to meet a water quality target?</p>
<hr>
<h2 id="the-conceptual-model" class="anchored">2. The Conceptual Model</h2>
<p>Lakes receive phosphorus from their watersheds via streams (point and nonpoint sources), direct atmospheric deposition, and shoreline erosion. They lose phosphorus through the outlet and through sedimentation to the lake bed. At steady state, inputs equal outputs — the lake phosphorus concentration reflects this equilibrium.</p>
<p>Phosphorus is the primary limiting nutrient for algal growth in most freshwater lakes. More phosphorus → more algae. More algae → more organic matter sinking to the bottom. More organic matter decomposing at the bottom → less oxygen in the deep water. Less oxygen in deep water → release of phosphorus from sediments (internal loading) → even more phosphorus. This positive feedback loop, once triggered, is the mechanism of eutrophication.</p>
<hr>
<h2 id="building-the-mathematical-model" class="anchored">3. Building the Mathematical Model</h2>
<h3 id="lake-phosphorus-mass-balance" class="anchored">3.1 Lake Phosphorus Mass Balance</h3>
<p>The Vollenweider model treats the lake as a completely mixed reactor. The mass of phosphorus <span class="math inline">M_P</span> [g] in the lake:</p>
<p><span class="math display">\frac{dM_P}{dt} = L_P - Q_{\text{out}} C_P - v_s A_s C_P</span></p>
<p>where <span class="math inline">L_P</span> [g yr⁻¹] is total phosphorus loading, <span class="math inline">Q_{\text{out}}</span> [m³ yr⁻¹] is outflow, <span class="math inline">C_P</span> [g m⁻³ = mg L⁻¹] is in-lake phosphorus concentration, <span class="math inline">v_s</span> [m yr⁻¹] is the apparent settling velocity of phosphorus (sedimentation), and <span class="math inline">A_s</span> [m²] is lake surface area.</p>
<p>Dividing by lake volume <span class="math inline">V</span> [m³]:</p>
<p><span class="math display">\frac{dC_P}{dt} = \frac{L_P}{V} - \frac{Q_{\text{out}}}{V} C_P - \frac{v_s A_s}{V} C_P</span></p>
<p>Define: <strong>hydraulic flushing rate</strong> <span class="math inline">\rho = Q_{\text{out}}/V</span> [yr⁻¹] (the inverse of hydraulic residence time <span class="math inline">\tau_w = V/Q_{\text{out}}</span>), and write <span class="math inline">v_s A_s/V = v_s/\bar{z}</span> where <span class="math inline">\bar{z} = V/A_s</span> is mean depth [m].</p>
<p>At <strong>steady state</strong> (<span class="math inline">dC_P/dt = 0</span>):</p>
<p><span class="math display">C_P^* = \frac{L_P/V}{\rho + v_s/\bar{z}} = \frac{L_P/A_s}{\bar{z}(\rho + v_s/\bar{z})} = \frac{[L_P]}{\bar{z}(\rho + v_s/\bar{z})}</span></p>
<p>where <span class="math inline">[L_P] = L_P/A_s</span> [g m⁻² yr⁻¹] is the <strong>areal phosphorus loading</strong>. Rearranging:</p>
<p><span class="math display">\boxed{C_P^* = \frac{[L_P]/\bar{z}}{\rho + v_s/\bar{z}} = \frac{[L_P]}{v_s + \rho\bar{z}}}</span></p>
<p>Vollenweider (1975) found empirically that <span class="math inline">v_s \approx 10</span> m yr⁻¹ for total phosphorus in most lakes. This gives the simple form:</p>
<p><span class="math display">C_P^* = \frac{[L_P]}{10 + \rho\bar{z}}</span></p>
<p>where <span class="math inline">[L_P]</span> is in mg m⁻² yr⁻¹ and <span class="math inline">\bar{z}</span> in m, giving <span class="math inline">C_P^*</span> in mg m⁻³ (= μg L⁻¹).</p>
<h3 id="phosphorus-loading-budget" class="anchored">3.2 Phosphorus Loading Budget</h3>
<p>The total areal loading <span class="math inline">[L_P]</span> is the sum of all sources divided by lake area:</p>
<p><span class="math display">[L_P] = \frac{1}{A_s}\left(\sum_i Q_i C_{P,i}^{\text{stream}} + L_P^{\text{atm}} A_s + L_P^{\text{internal}}\right)</span></p>
<p>where the terms represent tributary loads, atmospheric deposition (typically 10–50 mg m⁻² yr⁻¹ in temperate regions), and internal loading from sediment release.</p>
<p><strong>Export coefficients</strong> estimate nonpoint source loading from land use:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Land use</th>
<th>Phosphorus export coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Natural forest</td>
<td>5–15 mg m⁻² yr⁻¹</td>
</tr>
<tr class="even">
<td>Improved pasture</td>
<td>30–80 mg m⁻² yr⁻¹</td>
</tr>
<tr class="odd">
<td>Row crops (corn/wheat)</td>
<td>40–150 mg m⁻² yr⁻¹</td>
</tr>
<tr class="even">
<td>Urban residential</td>
<td>50–150 mg m⁻² yr⁻¹</td>
</tr>
<tr class="odd">
<td>Urban commercial/industrial</td>
<td>100–300 mg m⁻² yr⁻¹</td>
</tr>
<tr class="even">
<td>Feedlot/intensive livestock</td>
<td>500–5000 mg m⁻² yr⁻¹</td>
</tr>
</tbody>
</table>
<p>Total watershed nonpoint load:</p>
<p><span class="math display">L_P^{\text{NPS}} = \sum_k e_k A_k</span></p>
<p>where <span class="math inline">e_k</span> [mg m⁻² yr⁻¹] is the export coefficient and <span class="math inline">A_k</span> [m²] is the area of land use type <span class="math inline">k</span>.</p>
<h3 id="phosphorus-chlorophyll-relationship" class="anchored">3.3 Phosphorus-Chlorophyll Relationship</h3>
<p>In-lake phosphorus concentration predicts algal biomass (chlorophyll-a, <span class="math inline">\text{Chl}_a</span>) through an empirical regression calibrated across hundreds of lakes (Dillon and Rigler 1974; OECD 1982):</p>
<p><span class="math display">\log_{10}(\text{Chl}_a) = a + b \log_{10}(C_P)</span></p>
<p>with typical values <span class="math inline">a \approx -0.369</span>, <span class="math inline">b \approx 0.876</span> (Chl<span class="math inline">_a</span> in μg L⁻¹, <span class="math inline">C_P</span> in μg L⁻¹). Equivalently:</p>
<p><span class="math display">\text{Chl}_a = 0.427 \cdot C_P^{0.876}</span></p>
<p>Trophic state boundaries (OECD classification):</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Trophic state</th>
<th><span class="math inline">C_P</span> (μg/L)</th>
<th>Chl<span class="math inline">_a</span> (μg/L)</th>
<th>Secchi depth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Oligotrophic</td>
<td>&lt; 10</td>
<td>&lt; 2.5</td>
<td>&gt; 6 m</td>
</tr>
<tr class="even">
<td>Mesotrophic</td>
<td>10–35</td>
<td>2.5–8</td>
<td>3–6 m</td>
</tr>
<tr class="odd">
<td>Eutrophic</td>
<td>35–100</td>
<td>8–25</td>
<td>1.5–3 m</td>
</tr>
<tr class="even">
<td>Hypereutrophic</td>
<td>&gt; 100</td>
<td>&gt; 25</td>
<td>&lt; 1.5 m</td>
</tr>
</tbody>
</table>
<p>Lake Winnipeg south basin: <span class="math inline">C_P \approx 100</span>–200 μg/L → hypereutrophic, Chl<span class="math inline">_a</span> predicted at 25–50 μg/L → consistent with observed summer bloom conditions.</p>
<h3 id="thermal-stratification-and-hypolimnetic-oxygen-depletion" class="anchored">3.4 Thermal Stratification and Hypolimnetic Oxygen Depletion</h3>
<p>In summer, solar heating creates a warm, less-dense surface layer (epilimnion) floating above cold, dense bottom water (hypolimnion), separated by the <strong>thermocline</strong>. Once stratified, vertical mixing between these layers is suppressed for weeks to months.</p>
<p>The hypolimnion is a closed system: no reaeration from the surface (too far away and stratification prevents mixing), and organic matter settling from the productive surface layer decomposes aerobically. The oxygen consumption rate in the hypolimnion:</p>
<p><span class="math display">\frac{dC_O}{dt} = -k_h \cdot \text{BOD}_{\text{settling}}</span></p>
<p>where <span class="math inline">k_h</span> [day⁻¹] is the hypolimnetic oxygen consumption rate, proportional to the organic matter flux settling from above. In eutrophic lakes, the hypolimnetic oxygen depletion rate <span class="math inline">R</span> [mg L⁻¹ day⁻¹] correlates with TP concentration:</p>
<p><span class="math display">R \approx 0.010 \cdot C_P^{0.7}</span></p>
<p>(empirical; <span class="math inline">R</span> in mg L⁻¹ day⁻¹, <span class="math inline">C_P</span> in μg L⁻¹). If the hypolimnion starts the stratified period with DO = 10 mg/L and stratification lasts 90 days:</p>
<p><span class="math display">C_O(90) = 10 - 90 R</span></p>
<p>For <span class="math inline">C_P = 80</span> μg/L: <span class="math inline">R = 0.010 \times 80^{0.7} = 0.010 \times 27.1 = 0.271</span> mg/L/day, so <span class="math inline">C_O(90) = 10 - 24.4 = -14.4</span> mg/L — oxygen is exhausted after <span class="math inline">10/0.271 \approx 37</span> days of stratification.</p>
<p><strong>Internal loading:</strong> When hypolimnetic DO drops to zero (anaerobic conditions), iron-bound phosphorus in sediments is released:</p>
<p><span class="math display">L_P^{\text{internal}} = r_{\text{int}} \cdot A_{\text{hypolimnion}} \cdot t_{\text{anoxia}}</span></p>
<p>Typical internal loading rates <span class="math inline">r_{\text{int}} = 1</span>-<span class="math inline">10</span> mg m⁻² day⁻¹ during anoxic periods. Internal loading from sediments can equal or exceed the entire external loading — making lake recovery difficult even after external load reductions.</p>
<h3 id="total-maximum-daily-load-tmdl" class="anchored">3.5 Total Maximum Daily Load (TMDL)</h3>
<p>A <strong>TMDL</strong> is the maximum amount of a pollutant that a water body can receive while still meeting water quality standards. The TMDL framework (US Clean Water Act Section 303(d); similar Canadian frameworks) allocates loading among sources:</p>
<p><span class="math display">\text{TMDL} = \sum_i \text{WLA}_i + \sum_j \text{LA}_j + \text{MOS}</span></p>
<p>where WLA = Waste Load Allocations (point sources), LA = Load Allocations (nonpoint sources), and MOS = Margin of Safety (typically 10% of TMDL to account for uncertainty).</p>
<p><strong>Setting the TMDL:</strong> Work backwards from the water quality target (e.g., Chl<span class="math inline">_a \leq 10</span> μg/L for mesotrophic classification):</p>
<ol type="1">
<li>From Chl<span class="math inline">_a</span> target → <span class="math inline">C_P^*</span> target (via Dillon-Rigler regression)</li>
<li>From <span class="math inline">C_P^*</span> → <span class="math inline">[L_P]</span> target (via Vollenweider equation)</li>
<li>From <span class="math inline">[L_P]</span> → <span class="math inline">L_P^{\text{total}}</span> target = <span class="math inline">[L_P] \times A_s</span></li>
<li>Current loading <span class="math inline">L_P^{\text{current}}</span> → Required reduction = <span class="math inline">L_P^{\text{current}} - L_P^{\text{target}}</span></li>
<li>Allocate reductions among point sources (WLA) and nonpoint sources (LA)</li>
</ol>
<p>The allocation step involves both technical feasibility (what reduction is achievable from each source type?) and equity (who pays?). Point sources are regulated through permit limits; nonpoint sources through incentive programmes, best management practices (BMPs), and land use regulations.</p>
<hr>
<h2 id="worked-example-by-hand" class="anchored">4. Worked Example by Hand</h2>
<p><strong>Setting:</strong> A small Alberta lake, 4 km² surface area, mean depth 8 m, residence time <span class="math inline">\tau_w = 3</span> years (<span class="math inline">\rho = 0.333</span> yr⁻¹). Current areal loading <span class="math inline">[L_P] = 3.2</span> g m⁻² yr⁻¹ = 3200 mg m⁻² yr⁻¹. Target: mesotrophic (Chl<span class="math inline">_a \leq 8</span> μg/L).</p>
<p><strong>Step 1: Current steady-state phosphorus</strong></p>
<p><span class="math display">C_P^* = \frac{3200}{10 + 0.333 \times 8} = \frac{3200}{10 + 2.67} = \frac{3200}{12.67} = 252 \text{ μg/L}</span></p>
<p>Hypereutrophic — consistent with observed conditions.</p>
<p><strong>Step 2: Target phosphorus from Chl target</strong></p>
<p>From Chl<span class="math inline">_a = 8</span> μg/L → <span class="math inline">C_P = (8/0.427)^{1/0.876} = (18.74)^{1.142}</span>:</p>
<p><span class="math inline">\ln C_P = 1.142 \ln(18.74) = 1.142 × 2.931 = 3.347</span> → <span class="math inline">C_P = e^{3.347} = 28.4</span> μg/L ≈ 28 μg/L (mesotrophic boundary ✓)</p>
<p><strong>Step 3: Target areal loading</strong></p>
<p><span class="math display">[L_P]^{\text{target}} = C_P^{\text{target}} \times (10 + \rho\bar{z}) = 28 \times 12.67 = 355 \text{ mg m}^{-2}\text{yr}^{-1}</span></p>
<p><strong>Step 4: Required reduction</strong></p>
<p><span class="math display">\Delta[L_P] = 3200 - 355 = 2845 \text{ mg m}^{-2}\text{yr}^{-1} = 89\% \text{ reduction required}</span></p>
<p>This 89% reduction is a severe but realistic result for heavily loaded agricultural lakes in the Prairies. The dominant source — non-point agricultural runoff — cannot be reduced by 89% through incremental BMPs alone; it requires fundamental changes to watershed land management.</p>
<hr>
<h2 id="computational-implementation" class="anchored">5. Computational Implementation</h2>
<pre><code>function vollenweider_Cp(L_areal_mg_m2_yr, z_bar_m, rho_yr, vs=10):
    return L_areal_mg_m2_yr / (vs + rho_yr * z_bar_m)

function dillon_rigler(Cp_ug_L):
    return 0.427 * Cp_ug_L**0.876

function trophic_state(Cp_ug_L):
    if Cp_ug_L &lt; 10:   return "Oligotrophic"
    if Cp_ug_L &lt; 35:   return "Mesotrophic"
    if Cp_ug_L &lt; 100:  return "Eutrophic"
    return "Hypereutrophic"

function tmdl_target_loading(chl_target, z_bar, rho, vs=10):
    # Invert Dillon-Rigler
    Cp_target = (chl_target / 0.427)**(1/0.876)
    L_target = Cp_target * (vs + rho * z_bar)
    return L_target, Cp_target

function hypo_oxygen_depletion(Cp_ug_L, days_stratified, DO_initial=10):
    R = 0.010 * Cp_ug_L**0.7  # mg/L/day
    days_to_anoxia = DO_initial / R
    final_DO = max(0, DO_initial - R * days_stratified)
    return final_DO, days_to_anoxia</code></pre>
<pre class="{pyodide}"><code>import numpy as np

def vollenweider(L, z, rho, vs=10):
    return L / (vs + rho * z)

def dillon_rigler(Cp):
    return 0.427 * Cp**0.876

def trophic_state(Cp):
    if Cp &lt; 10:   return "Oligotrophic"
    elif Cp &lt; 35: return "Mesotrophic"
    elif Cp &lt; 100: return "Eutrophic"
    else:         return "Hypereutrophic"

def tmdl_loading(chl_target, z, rho, vs=10):
    Cp = (chl_target / 0.427)**(1/0.876)
    return Cp * (vs + rho * z), Cp

def hypo_depletion(Cp, days, DO0=10):
    R = 0.010 * Cp**0.7
    anoxia_day = DO0 / R
    final_DO = max(0, DO0 - R * days)
    return R, anoxia_day, final_DO

# Alberta lake example
z, rho = 8.0, 0.333
L_current = 3200.0   # mg/m²/yr

Cp = vollenweider(L_current, z, rho)
chl = dillon_rigler(Cp)
print(f"Current state:")
print(f"  Cp* = {Cp:.0f} μg/L → {trophic_state(Cp)}")
print(f"  Predicted Chl-a = {chl:.1f} μg/L")

L_target, Cp_target = tmdl_loading(8.0, z, rho)
print(f"\nTMDL for Chl ≤ 8 μg/L:")
print(f"  Target Cp = {Cp_target:.1f} μg/L")
print(f"  Target loading = {L_target:.0f} mg/m²/yr")
print(f"  Reduction needed = {100*(L_current-L_target)/L_current:.0f}%")

print("\nHypolimnetic oxygen depletion (90-day stratification):")
for Cp_test in [20, 50, 80, 150]:
    R, td, DO_final = hypo_depletion(Cp_test, 90)
    print(f"  Cp={Cp_test:3d} μg/L: R={R:.3f} mg/L/d, anoxia in {td:.0f} d, DO_final={DO_final:.1f} mg/L")</code></pre>
<hr>
<h2 id="visualization" class="anchored">6. Visualization</h2>
<div data-viz="echarts" style="height:420px" data-options="{
&quot;title&quot;: {&quot;text&quot;: &quot;Vollenweider Diagram — Phosphorus Loading vs Lake Trophic State&quot;, &quot;textStyle&quot;: {&quot;fontSize&quot;: 14}},
&quot;tooltip&quot;: {&quot;trigger&quot;: &quot;axis&quot;},
&quot;legend&quot;: {&quot;data&quot;: [&quot;Predicted Chl-a (μg/L)&quot;, &quot;Eutrophic threshold (Chl=8)&quot;, &quot;Hypereutrophic threshold (Chl=25)&quot;], &quot;bottom&quot;: 0},
&quot;xAxis&quot;: {&quot;name&quot;: &quot;Areal phosphorus loading (mg m⁻² yr⁻¹)&quot;, &quot;nameLocation&quot;: &quot;middle&quot;, &quot;nameGap&quot;: 30,
&quot;data&quot;: [50, 100, 200, 400, 800, 1200, 1600, 2400, 3200]},
&quot;yAxis&quot;: {&quot;name&quot;: &quot;Predicted chlorophyll-a (μg L⁻¹)&quot;, &quot;nameLocation&quot;: &quot;middle&quot;, &quot;nameGap&quot;: 55},
&quot;series&quot;: [
{&quot;name&quot;: &quot;Predicted Chl-a (μg/L)&quot;, &quot;type&quot;: &quot;line&quot;, &quot;smooth&quot;: true,
&quot;itemStyle&quot;: {&quot;color&quot;: &quot;#2E7D32&quot;},
&quot;data&quot;: [1.5, 3.1, 6.5, 13.8, 29.4, 44.6, 59.8, 91.0, 122.0]},
{&quot;name&quot;: &quot;Eutrophic threshold (Chl=8)&quot;, &quot;type&quot;: &quot;line&quot;,
&quot;lineStyle&quot;: {&quot;type&quot;: &quot;dashed&quot;, &quot;color&quot;: &quot;#F57F17&quot;},
&quot;data&quot;: [8,8,8,8,8,8,8,8,8]},
{&quot;name&quot;: &quot;Hypereutrophic threshold (Chl=25)&quot;, &quot;type&quot;: &quot;line&quot;,
&quot;lineStyle&quot;: {&quot;type&quot;: &quot;dashed&quot;, &quot;color&quot;: &quot;#C62828&quot;},
&quot;data&quot;: [25,25,25,25,25,25,25,25,25]}
]
}"></div>
<p>The transition from mesotrophic to eutrophic occurs at ~200 mg m⁻² yr⁻¹ loading for this lake, and to hypereutrophic at ~900 mg m⁻² yr⁻¹. The Alberta lake in the worked example receives 3200 mg m⁻² yr⁻¹ — well into hypereutrophic territory. The steep slope of the curve at high loadings means that large reductions in loading produce relatively modest improvements in trophic state until loading falls below the eutrophic threshold.</p>
<hr>
<h2 id="interpretation" class="anchored">7. Interpretation</h2>
<p>The Vollenweider model gives water quality managers a precise answer to a policy question: how much must we reduce phosphorus loading to achieve a target water quality? The 89% reduction required for the Alberta lake is sobering but honest — incremental BMPs typically achieve 20–40% reductions, and meeting the 89% target requires fundamental changes to agricultural practice or watershed land use.</p>
<p>The internal loading problem makes lake recovery slower than watershed recovery. Even after external loads are reduced to target levels, legacy phosphorus in bottom sediments continues to release during summer anoxia, potentially maintaining eutrophic conditions for years to decades. This is why passive management (reducing external loads and waiting) often requires supplementation with active measures: alum treatment of the water column to bind phosphorus, hypolimnetic aeration to prevent sediment release, or even dredging to remove the phosphorus-rich surface sediment layer.</p>
<p>Lake Winnipeg illustrates the international dimension: approximately 50% of its phosphorus loading originates in the United States (Minnesota and North Dakota via the Red River). No Canadian water quality regulation can address this load directly — it requires international agreements under the Boundary Waters Treaty, analogous to the Great Lakes agreements that achieved remarkable water quality improvements in Lakes Erie and Ontario in the 1970s–1990s through the International Joint Commission framework.</p>
<hr>
<h2 id="what-could-go-wrong" class="anchored">8. What Could Go Wrong?</h2>
<p><strong>The Vollenweider model assumes complete mixing.</strong> Many lakes are poorly mixed: shallow embayments experience higher phosphorus concentrations than the main basin; stratified lakes have very different epilimnetic and hypolimnetic concentrations. Applying the completely-mixed model to a stratified lake overestimates dilution and underestimates the local algal response.</p>
<p><strong>Export coefficients are highly uncertain.</strong> The range of values for row crops (40–150 mg m⁻² yr⁻¹) spans nearly a factor of 4. Actual export depends on soil type, tillage practice, drainage tile density, proximity to watercourses, and weather. Using mid-range export coefficients can produce loading estimates that are off by a factor of 2–3 — sufficient to change the TMDL target allocation significantly.</p>
<p><strong>Internal loading is often underestimated.</strong> The simple empirical formula <span class="math inline">R = 0.010 C_P^{0.7}</span> gives the lake-average depletion rate, but sediment phosphorus release is spatially heterogeneous and time-dependent. Newly deposited organic-rich sediments have much higher release rates than well-oxidised mineral sediments. After external load reductions, the hypolimnion may remain anoxic for years as legacy sediment phosphorus is gradually depleted.</p>
<p><strong>The phosphorus-chlorophyll regression has wide scatter.</strong> The Dillon-Rigler regression has an <span class="math inline">r^2</span> of approximately 0.7 — a 30-unit <span class="math inline">C_P</span> difference does not reliably translate to the predicted chlorophyll change. Individual lakes deviate substantially from the regression line due to differences in light availability, nitrogen limitation, grazing pressure, and species composition. The regression should be used for order-of-magnitude planning, not precise prediction.</p>
<hr>
<h2 id="summary" class="anchored">9. Summary</h2>
<p>The Vollenweider phosphorus mass balance model relates areal phosphorus loading <span class="math inline">[L_P]</span> to steady-state in-lake concentration <span class="math inline">C_P^* = [L_P]/(v_s + \rho\bar{z})</span>, where <span class="math inline">v_s \approx 10</span> m yr⁻¹ is the apparent sedimentation velocity and <span class="math inline">\rho = 1/\tau_w</span> is the hydraulic flushing rate. The Dillon-Rigler regression <span class="math inline">\text{Chl}_a = 0.427 C_P^{0.876}</span> predicts algal biomass from phosphorus concentration.</p>
<p>Summer stratification seals the hypolimnion from reaeration; organic matter decomposition exhausts hypolimnetic oxygen within weeks to months in eutrophic lakes, triggering anaerobic phosphorus release from sediments (internal loading). The TMDL framework works backwards from a water quality target through the phosphorus-chlorophyll regression and Vollenweider equation to derive a loading target, then allocates reductions among point (WLA) and nonpoint (LA) sources.</p>
<p><strong>Key equations:</strong></p>
<p><span class="math display">C_P^* = \frac{[L_P]}{v_s + \rho\bar{z}}, \quad v_s \approx 10 \text{ m yr}^{-1}</span></p>
<p><span class="math display">\text{Chl}_a = 0.427\, C_P^{0.876}</span></p>
<p><span class="math display">\text{TMDL} = \Sigma\text{WLA} + \Sigma\text{LA} + \text{MOS}</span></p>
<hr>
<h2 id="math-refresher" class="anchored">Math Refresher</h2>
<p><strong>The log-log regression.</strong> The Dillon-Rigler relationship <span class="math inline">\text{Chl}_a = 0.427 C_P^{0.876}</span> is a power law — it appears as a straight line on a log-log plot. Taking logarithms: <span class="math inline">\log(\text{Chl}_a) = \log(0.427) + 0.876 \log(C_P)</span>. The slope 0.876 is the scaling exponent — a 10% increase in <span class="math inline">C_P</span> produces a <span class="math inline">1.10^{0.876} - 1 = 8.7\%</span> increase in chlorophyll (slightly sublinear). Inverting the equation to find <span class="math inline">C_P</span> from a Chl target: <span class="math inline">C_P = (\text{Chl}_a / 0.427)^{1/0.876}</span>.</p>
<p><strong>Residence time and flushing.</strong> The hydraulic residence time <span class="math inline">\tau_w = V/Q_{\text{out}}</span> is the average time a water molecule spends in the lake. A lake with <span class="math inline">\tau_w = 10</span> years is flushed once per decade — it responds slowly to changes in loading. A lake with <span class="math inline">\tau_w = 3</span> months responds quickly. The flushing rate <span class="math inline">\rho = 1/\tau_w</span> appears in the Vollenweider denominator: fast-flushing lakes (high <span class="math inline">\rho</span>) have lower <span class="math inline">C_P^*</span> for the same loading because they export phosphorus through the outlet more rapidly before it settles.</p>


<footer class="wayward-footer">
  <div class="wayward-footer__inner">
    <div class="wayward-footer__brand">
      <div class="wayward-footer__logo">WaywardHouse<span>.</span></div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wayward-footer__group" aria-labelledby="footer-reading">
      <h2 id="footer-reading" class="anchored">Reading</h2>
      <a href="https://wayward.house/articles/">Articles</a>
      <a href="https://wayward.house/learn/">Library</a>
      <a href="https://wayward.house/archive.html">Archive</a>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-site">
      <h2 id="footer-site" class="anchored">Site</h2>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
      <a href="https://wayward.house/about.html">About</a>
      <a href="https://wayward.house/contact.html">Contact</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-resources">
      <h2 id="footer-resources" class="anchored">Resources</h2>
      <a href="https://wayward.house/topics/">All Topics</a>
      <a href="https://wayward.house/privacy.html">Privacy Policy</a>
      <a href="https://wayward.house/terms.html">Terms of Use</a>
    </nav>
  </div>
</footer>

<script type="module" src="../assets/dist/main.js"></script>
<script type="module" src="../assets/js/core.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>