<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-05">
<meta name="description" content="Pump-and-treat is the standard remedial technology at groundwater contamination sites: pump contaminated groundwater to the surface, treat it, and either discharge it or reinfiltrate. Whether it works depends on the pumping well’s capture zone — the upgradient area whose groundwater flows to the well. This essay derives capture zone geometry from Theis and steady-state well equations, calculates the minimum pumping rate to prevent plume escape, quantifies in-situ chemical oxidation reagent requirements stoichiometrically, defines monitored natural attenuation criteria, and compares remediation approaches economically using net present value.">

<title>Pump-and-Treat and In-Situ Remediation – Computational Geography</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-734cb40618f438257b19a1e532635a32.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script>
  (function () {
    var s = localStorage.getItem('theme');
    var dark = s !== null ? s === 'dark' : false;
    document.documentElement.dataset.theme = dark ? 'dark' : 'light';
    document.documentElement.dataset.brand = 'wayward';
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-math tag-hash-viz">


<header id="title-block-header">
<h1 class="title"><span class="chapter-title">Pump-and-Treat and In-Situ Remediation</span></h1>
<p class="subtitle">Capture zone analysis, Theis equation, and cost-benefit comparison of remediation approaches</p>

<p class="date">2026-03-05</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-question" id="toc-the-question">1. The Question</a></li>
  <li><a href="#the-conceptual-model" id="toc-the-conceptual-model">2. The Conceptual Model</a></li>
  <li><a href="#building-the-mathematical-model" id="toc-building-the-mathematical-model">3. Building the Mathematical Model</a>
  <ul>
  <li><a href="#steady-state-radial-flow-thiem-equation" id="toc-steady-state-radial-flow-thiem-equation">3.1 Steady-State Radial Flow — Thiem Equation</a></li>
  <li><a href="#transient-response-theis-equation" id="toc-transient-response-theis-equation">3.2 Transient Response — Theis Equation</a></li>
  <li><a href="#capture-zone-analysis" id="toc-capture-zone-analysis">3.3 Capture Zone Analysis</a></li>
  <li><a href="#in-situ-chemical-oxidation-isco" id="toc-in-situ-chemical-oxidation-isco">3.4 In-Situ Chemical Oxidation (ISCO)</a></li>
  <li><a href="#monitored-natural-attenuation-criteria" id="toc-monitored-natural-attenuation-criteria">3.5 Monitored Natural Attenuation Criteria</a></li>
  <li><a href="#net-present-value-cost-comparison" id="toc-net-present-value-cost-comparison">3.6 Net Present Value Cost Comparison</a></li>
  </ul></li>
  <li><a href="#worked-example-by-hand" id="toc-worked-example-by-hand">4. Worked Example by Hand</a></li>
  <li><a href="#computational-implementation" id="toc-computational-implementation">5. Computational Implementation</a></li>
  <li><a href="#visualization" id="toc-visualization">6. Visualization</a></li>
  <li><a href="#interpretation" id="toc-interpretation">7. Interpretation</a></li>
  <li><a href="#what-could-go-wrong" id="toc-what-could-go-wrong">8. What Could Go Wrong?</a></li>
  <li><a href="#summary" id="toc-summary">9. Summary</a></li>
  <li><a href="#math-refresher" id="toc-math-refresher">Math Refresher</a></li>
  </ul>
</nav>
<p>The largest pump-and-treat system in North America operates at the Rocky Mountain Arsenal near Denver, Colorado — a former chemical weapons manufacturing site contaminated with nerve agent precursors, pesticides, and aviation fuel. The system has been pumping and treating since 1982, handling up to 6,000 gallons per minute through a treatment train that includes air stripping, activated carbon adsorption, and biological treatment. After 40 years and hundreds of millions of dollars, it continues to operate — not because it has failed, but because the contamination was so severe and so deeply embedded in the aquifer that complete cleanup will take generations.</p>
<p>Pump-and-treat is not a silver bullet. It is a hydraulic containment technology that, in the best case, prevents plume migration to receptors while natural attenuation and time slowly reduce contaminant mass. Understanding its mathematics — capture zones, pumping rates, and the economics of operation over decades — is essential for realistic site management.</p>
<hr>
<h2 id="the-question" class="anchored">1. The Question</h2>
<p>What pumping rate is required to capture a contaminant plume and prevent it from migrating to a receptor? How does a single pumping well affect the surrounding water table? What in-situ chemical treatment can destroy contaminant mass? And how do we compare remediation alternatives economically over a 30-year project life?</p>
<hr>
<h2 id="the-conceptual-model" class="anchored">2. The Conceptual Model</h2>
<p>A pumping well in an aquifer with regional groundwater flow creates a cone of depression — a radially symmetric drawdown zone that deflects the regional flow lines toward the well. The <strong>capture zone</strong> is the upgradient area whose flow lines converge on the well. Any contaminant within the capture zone will be pumped to the surface; any contaminant outside will continue to migrate downgradient.</p>
<p>The width of the capture zone at the well is determined by the pumping rate relative to the regional flow rate. Insufficient pumping allows the plume to pass between wells; excessive pumping wastes energy and treatment costs.</p>
<hr>
<h2 id="building-the-mathematical-model" class="anchored">3. Building the Mathematical Model</h2>
<h3 id="steady-state-radial-flow-thiem-equation" class="anchored">3.1 Steady-State Radial Flow — Thiem Equation</h3>
<p>For a single well pumping at rate <span class="math inline">Q</span> [m³ s⁻¹] in a confined aquifer at steady state, the drawdown <span class="math inline">s = h_0 - h</span> (where <span class="math inline">h_0</span> is undisturbed head) at distance <span class="math inline">r</span> [m] from the well is described by the <strong>Thiem equation</strong>:</p>
<p><span class="math display">s(r) = s(r_1) - \frac{Q}{2\pi T}\ln\!\left(\frac{r}{r_1}\right)</span></p>
<p>where <span class="math inline">T = Kb</span> [m² s⁻¹] is <strong>transmissivity</strong> (hydraulic conductivity × saturated thickness), and <span class="math inline">r_1</span> is a reference distance where head is known.</p>
<p>For an unconfined aquifer (water table), the equivalent is:</p>
<p><span class="math display">h(r)^2 - h(r_1)^2 = \frac{Q}{\pi K}\ln\!\left(\frac{r}{r_1}\right)</span></p>
<h3 id="transient-response-theis-equation" class="anchored">3.2 Transient Response — Theis Equation</h3>
<p>Before steady state is reached, drawdown evolves with time. The <strong>Theis equation</strong> (1935):</p>
<p><span class="math display">s(r,t) = \frac{Q}{4\pi T} W(u)</span></p>
<p>where <span class="math inline">W(u) = -\text{Ei}(-u) = \int_u^\infty \frac{e^{-t}}{t}dt</span> is the <strong>well function</strong> and:</p>
<p><span class="math display">u = \frac{r^2 S}{4Tt}</span></p>
<p><span class="math inline">S</span> is the <strong>storativity</strong> (confined: 10⁻⁵–10⁻³; unconfined = specific yield <span class="math inline">S_y \approx 0.1</span>–0.3), and <span class="math inline">t</span> is time.</p>
<p><strong>Cooper-Jacob approximation</strong> (valid for <span class="math inline">u &lt; 0.05</span>, i.e., large <span class="math inline">t</span> or small <span class="math inline">r</span>):</p>
<p><span class="math display">s(r,t) \approx \frac{Q}{4\pi T}\left[\ln\!\left(\frac{2.25Tt}{r^2 S}\right)\right] = \frac{2.303Q}{4\pi T}\log_{10}\!\left(\frac{2.25Tt}{r^2 S}\right)</span></p>
<p>For <span class="math inline">Q = 0.01</span> m³/s, <span class="math inline">T = 0.002</span> m²/s, <span class="math inline">r = 50</span> m, <span class="math inline">S = 0.001</span>, <span class="math inline">t = 24</span> hours = 86,400 s:</p>
<p><span class="math inline">u = 50^2 \times 0.001 / (4 \times 0.002 \times 86400) = 2500 \times 0.001/691.2 = 0.00362</span> (&lt; 0.05 ✓)</p>
<p><span class="math inline">s = 0.01/(4\pi \times 0.002) \times \ln(2.25 \times 0.002 \times 86400/(2500 \times 0.001))</span> <span class="math inline">= 0.0398 \times \ln(155.52)</span> <span class="math inline">= 0.0398 \times 5.047 = 0.201</span> m drawdown at 50 m after 24 hours.</p>
<h3 id="capture-zone-analysis" class="anchored">3.3 Capture Zone Analysis</h3>
<p>In a uniform regional flow field with Darcy flux <span class="math inline">q_0 = K \cdot i</span> [m/day], a pumping well of rate <span class="math inline">Q</span> [m³/day] creates a capture zone whose <strong>maximum width</strong> <span class="math inline">y_{\max}</span> at the well (the total width far upgradient) is:</p>
<p><span class="math display">y_{\max} = \frac{Q}{q_0 b}</span></p>
<p>where <span class="math inline">b</span> is aquifer saturated thickness. This is the width of the entire capture zone — the region whose groundwater is captured by the well.</p>
<p>The <strong>stagnation point</strong> — the upgradient point where the regional flow exactly balances the wellward flow — is at distance:</p>
<p><span class="math display">x_s = -\frac{Q}{2\pi T i \cdot b} = -\frac{Q}{2\pi q_0 b}</span></p>
<p>(negative = upgradient). Beyond this point, all groundwater flows toward the well.</p>
<p>The <strong>capture zone boundary</strong> is the streamline that divides captured from escaped flow. Its shape is:</p>
<p><span class="math display">y = \pm\frac{Q}{2q_0 b}\left(1 - \frac{x}{|x_s|}\right) \quad \text{(approximate, for large }x\text{)}</span></p>
<p>For complete capture of a plume of width <span class="math inline">W_{\text{plume}}</span>: need <span class="math inline">y_{\max} \geq W_{\text{plume}}</span> → required pumping rate:</p>
<p><span class="math display">Q_{\min} = W_{\text{plume}} \cdot q_0 \cdot b</span></p>
<h3 id="in-situ-chemical-oxidation-isco" class="anchored">3.4 In-Situ Chemical Oxidation (ISCO)</h3>
<p>ISCO destroys contaminants in the subsurface by injecting a strong oxidant — permanganate (KMnO₄), persulfate (Na₂S₂O₈), or Fenton’s reagent (H₂O₂ + Fe²⁺). The stoichiometric requirement for each contaminant is derived from the balanced chemical equation.</p>
<p><strong>PCE destruction by permanganate:</strong></p>
<p><span class="math inline">&amp;#36;3\text{C}_2\text{Cl}_4 + 4\text{KMnO}_4 \rightarrow 6\text{CO}_2 + 4\text{KCl} + 4\text{MnO}_2 + 2\text{Cl}_2</span>$</p>
<p>Stoichiometric ratio: 4 mol KMnO₄ per 3 mol PCE.</p>
<p>Molar masses: PCE (<span class="math inline">C_2Cl_4</span>) = 165.8 g/mol; KMnO₄ = 158.0 g/mol.</p>
<p>Mass ratio: <span class="math inline">\frac{4 \times 158.0}{3 \times 165.8} = \frac{632}{497.4} = 1.27</span> kg KMnO₄ per kg PCE.</p>
<p><strong>Practical demand:</strong> The subsurface <strong>natural oxidant demand (NOD)</strong> — from naturally occurring reduced compounds (organic matter, Fe²⁺, Mn²⁺, sulfide) — typically requires 1–10× the theoretical ISCO demand. Total oxidant mass:</p>
<p><span class="math display">M_{\text{oxidant}} = (S_R \cdot M_{\text{contaminant}} + \text{NOD} \cdot V_{\text{treatment}}) \cdot \text{safety factor}</span></p>
<p>where <span class="math inline">S_R</span> is stoichiometric ratio, <span class="math inline">M_{\text{contaminant}}</span> is contaminant mass to destroy, <span class="math inline">\text{NOD}</span> is oxidant demand per unit aquifer volume, and the safety factor is typically 2–5 to ensure reaction completion.</p>
<h3 id="monitored-natural-attenuation-criteria" class="anchored">3.5 Monitored Natural Attenuation Criteria</h3>
<p><strong>Monitored natural attenuation (MNA)</strong> is accepted as a remedial strategy when:</p>
<ol type="1">
<li><p><strong>Lines of evidence</strong> demonstrate active biodegradation:</p>
<ul>
<li>Decreasing concentrations along the flow path</li>
<li>Depletion of electron acceptors (O₂, NO₃⁻, SO₄²⁻) and accumulation of metabolic byproducts (Fe²⁺, Mn²⁺, CH₄)</li>
<li>Stable or shrinking plume footprint over time (at least 3–4 years of data)</li>
</ul></li>
<li><p><strong>Plume stability</strong> demonstrated: <span class="math inline">L_{\text{plume}} &lt; L_{\text{receptor}}</span> (plume length does not reach nearest receptor)</p></li>
<li><p><strong>Risk-based</strong> cleanup targets reachable within a reasonable timeframe (typically 30–50 years for residential use)</p></li>
</ol>
<p>The <strong>attenuation rate constant</strong> <span class="math inline">\lambda</span> is estimated from the spatial decrease in concentration along the plume centreline:</p>
<p><span class="math display">\ln C(x) = \ln C_0 - \frac{\lambda}{v_c} x</span></p>
<p>If <span class="math inline">\ln C</span> vs.&nbsp;<span class="math inline">x</span> is linear, the slope gives <span class="math inline">-\lambda/v_c</span>, and <span class="math inline">\lambda = -\text{slope} \times v_c</span>.</p>
<h3 id="net-present-value-cost-comparison" class="anchored">3.6 Net Present Value Cost Comparison</h3>
<p>Remediation costs extend over decades. <strong>Net present value (NPV)</strong> converts all future costs to present-day equivalents:</p>
<p><span class="math display">\text{NPV} = \sum_{t=0}^{T} \frac{C_t}{(1+r)^t}</span></p>
<p>where <span class="math inline">C_t</span> is cost in year <span class="math inline">t</span>, <span class="math inline">r</span> is discount rate (typically 3–7% for public projects), and <span class="math inline">T</span> is project horizon.</p>
<p>For a pump-and-treat system with capital cost <span class="math inline">C_0</span> and annual O&amp;M cost <span class="math inline">C_{\text{OM}}</span> for <span class="math inline">T</span> years:</p>
<p><span class="math display">\text{NPV}_{\text{P\&amp;T}} = C_0 + C_{\text{OM}} \cdot \frac{1-(1+r)^{-T}}{r}</span></p>
<p>The factor <span class="math inline">[1-(1+r)^{-T}]/r</span> is the <strong>present value annuity factor</strong> (PVAF).</p>
<p><strong>Comparison example:</strong> Three options for a PCE plume at <span class="math inline">Q = 0.002</span> m³/s pump rate:</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Option</th>
<th>Capital (<span class="math inline">M) | Annual O&amp;M (</span>M/yr)</th>
<th>Duration (yr)</th>
<th>NPV at 5% ($M)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pump-and-treat</td>
<td>2.0</td>
<td>0.4</td>
<td>30</td>
<td>2.0 + 0.4×15.37 = <strong>8.15</strong></td>
</tr>
<tr class="even">
<td>ISCO</td>
<td>1.5</td>
<td>0.05</td>
<td>5</td>
<td>1.5 + 0.05×4.33 = <strong>1.72</strong></td>
</tr>
<tr class="odd">
<td>MNA with monitoring</td>
<td>0.1</td>
<td>0.08</td>
<td>30</td>
<td>0.1 + 0.08×15.37 = <strong>1.33</strong></td>
</tr>
</tbody>
</table>
<p>PVAF (5%, 30yr) = <span class="math inline">[1-(1.05)^{-30}]/0.05 = 15.37</span>; PVAF (5%, 5yr) = 4.33.</p>
<p>MNA has the lowest NPV if the site qualifies — but requires demonstrating regulatory criteria. ISCO has higher NPV than MNA but lower than P&amp;T and achieves faster cleanup of source mass. P&amp;T is by far the most expensive option over a 30-year horizon — yet it remains the most common technology at major sites because it provides immediate hydraulic containment and regulatory certainty.</p>
<hr>
<h2 id="worked-example-by-hand" class="anchored">4. Worked Example by Hand</h2>
<p><strong>Setting:</strong> A TCE plume at a Calgary industrial site. Aquifer: <span class="math inline">K = 5\times10^{-4}</span> m/s, <span class="math inline">b = 12</span> m, <span class="math inline">i = 0.003</span>, <span class="math inline">T = Kb = 6\times10^{-3}</span> m²/s. Plume width at leading edge: 35 m. Design a capture well.</p>
<p><strong>Step 1: Regional Darcy flux</strong></p>
<p><span class="math display">q_0 = K \cdot i = 5\times10^{-4} \times 0.003 = 1.5\times10^{-6} \text{ m/s} = 0.130 \text{ m/day}</span></p>
<p><strong>Step 2: Minimum pumping rate for full capture</strong></p>
<p><span class="math display">Q_{\min} = W_{\text{plume}} \cdot q_0 \cdot b = 35 \times 1.5\times10^{-6} \times 12 = 6.3\times10^{-4} \text{ m}^3/\text{s} = 54.4 \text{ m}^3/\text{day}</span></p>
<p><strong>Step 3: Stagnation point location</strong></p>
<p><span class="math display">x_s = -\frac{Q_{\min}}{2\pi q_0 b} = -\frac{6.3\times10^{-4}}{2\pi \times 1.5\times10^{-6} \times 12} = -\frac{6.3\times10^{-4}}{1.131\times10^{-4}} = -5.57 \text{ m}</span></p>
<p>The stagnation point is 5.6 m upgradient of the well — a relatively small capture zone for this plume width, meaning the well is positioned close to the leading edge.</p>
<p><strong>Step 4: ISCO requirement</strong> (TCE source mass = 80 kg)</p>
<p>TCE + permanganate: $2_4 + _2_3 _2 + 2_2 + 2 + $</p>
<p>Stoichiometric ratio: <span class="math inline">(2 \times 158.0)/(131.4) = 316/131.4 = 2.41</span> kg KMnO₄/kg TCE</p>
<p><span class="math inline">M_{\text{KMnO}_4,\text{stoic}} = 2.41 \times 80 = 193</span> kg</p>
<p>With NOD of 3 g/kg aquifer solids and treatment volume 1000 m³ at bulk density 1800 kg/m³:</p>
<p><span class="math inline">\text{NOD mass} = 3 \times 10^{-3} \times 1800 \times 1000 = 5400</span> kg</p>
<p><span class="math inline">M_{\text{total}} = (193 + 5400) \times 2 \text{ (safety factor)} = 11{,}186</span> kg KMnO₄</p>
<p>At <span class="math inline">\&amp;#36;1.50</span>/kg, reagent cost ≈ $&amp;#36;16{,}800.</p>
<hr>
<h2 id="computational-implementation" class="anchored">5. Computational Implementation</h2>
<pre><code>function theis_drawdown(r, t, Q, T, S):
    u = r**2 * S / (4 * T * t)
    W_u = well_function(u)  # -Ei(-u)
    return Q / (4 * pi * T) * W_u

function capture_width(Q, q0, b):
    return Q / (q0 * b)

function stagnation_x(Q, q0, b):
    return -Q / (2 * pi * q0 * b)

function npv(capital, annual_om, years, rate):
    pvaf = (1 - (1 + rate)**(-years)) / rate
    return capital + annual_om * pvaf

function isco_mass(contaminant_mass_kg, stoic_ratio, NOD_g_kg,
                   V_treatment_m3, rho_b_kg_m3, safety=2):
    theoretical = stoic_ratio * contaminant_mass_kg
    nod_demand = NOD_g_kg/1000 * rho_b_kg_m3 * V_treatment_m3
    return (theoretical + nod_demand) * safety</code></pre>
<pre class="{pyodide}"><code>import numpy as np
from scipy.special import exp1

def well_function(u):
    return exp1(u)  # -Ei(-u) = E1(u)

def theis(r, t, Q, T, S):
    u = r**2 * S / (4*T*t)
    return Q / (4*np.pi*T) * well_function(u)

def cooper_jacob(r, t, Q, T, S):
    u = r**2 * S / (4*T*t)
    if u &gt; 0.05: return np.nan  # approximation invalid
    return Q/(4*np.pi*T) * np.log(2.25*T*t/(r**2*S))

def capture_analysis(Q, K, b, i):
    q0 = K * i
    width = Q / (q0 * b)
    xs = -Q / (2*np.pi*q0*b)
    return q0, width, xs

def npv_cost(capital, annual_om, years, r=0.05):
    pvaf = (1-(1+r)**(-years))/r
    return capital + annual_om * pvaf

# Calgary TCE site
K, b, i = 5e-4, 12.0, 0.003
T = K * b
W_plume = 35.0
Q_min = W_plume * K * i * b
print(f"Minimum pumping rate: {Q_min*86400:.1f} m³/day = {Q_min*1000:.2f} L/s")

q0, cap_w, xs = capture_analysis(Q_min, K, b, i)
print(f"Capture zone width: {cap_w:.1f} m")
print(f"Stagnation point: {xs:.1f} m upgradient")

# Theis drawdown at various distances after 7 days
S = 0.0002
t7 = 7*86400
print(f"\nTheis drawdown after 7 days (Q={Q_min:.2e} m³/s, T={T:.3e} m²/s):")
for r in [1, 5, 10, 25, 50, 100]:
    s = theis(r, t7, Q_min, T, S)
    print(f"  r={r:4d}m: s={s:.3f} m")

# NPV comparison
print("\nNPV comparison (5% discount rate, r in million $):")
for name, cap, om, yrs in [
    ("Pump-and-treat", 2.0, 0.40, 30),
    ("ISCO",           1.5, 0.05,  5),
    ("MNA + monitoring",0.1, 0.08, 30)]:
    nv = npv_cost(cap, om, yrs)
    print(f"  {name:25s}: NPV = ${nv:.2f}M")</code></pre>
<hr>
<h2 id="visualization" class="anchored">6. Visualization</h2>
<div data-viz="echarts" style="height:420px" data-options="{
  &quot;title&quot;: {&quot;text&quot;: &quot;Capture Zone Width vs Pumping Rate — Various Aquifer Conditions&quot;, &quot;textStyle&quot;: {&quot;fontSize&quot;: 14}},
  &quot;tooltip&quot;: {&quot;trigger&quot;: &quot;axis&quot;},
  &quot;legend&quot;: {&quot;data&quot;: [&quot;q₀b = 0.002 m²/day (slow)&quot;, &quot;q₀b = 0.01 m²/day (medium)&quot;, &quot;q₀b = 0.05 m²/day (fast)&quot;], &quot;bottom&quot;: 0},
  &quot;xAxis&quot;: {&quot;name&quot;: &quot;Pumping rate Q (m³/day)&quot;, &quot;nameLocation&quot;: &quot;middle&quot;, &quot;nameGap&quot;: 30,
    &quot;data&quot;: [10,25,50,75,100,150,200,300,400,500]},
  &quot;yAxis&quot;: {&quot;name&quot;: &quot;Maximum capture zone width (m)&quot;, &quot;nameLocation&quot;: &quot;middle&quot;, &quot;nameGap&quot;: 60},
  &quot;series&quot;: [
    {&quot;name&quot;: &quot;q₀b = 0.002 m²/day (slow)&quot;, &quot;type&quot;: &quot;line&quot;, &quot;smooth&quot;: false,
     &quot;data&quot;: [5000,12500,25000,37500,50000,75000,100000,150000,200000,250000]},
    {&quot;name&quot;: &quot;q₀b = 0.01 m²/day (medium)&quot;, &quot;type&quot;: &quot;line&quot;, &quot;smooth&quot;: false,
     &quot;data&quot;: [1000,2500,5000,7500,10000,15000,20000,30000,40000,50000]},
    {&quot;name&quot;: &quot;q₀b = 0.05 m²/day (fast)&quot;, &quot;type&quot;: &quot;line&quot;, &quot;smooth&quot;: false,
     &quot;data&quot;: [200,500,1000,1500,2000,3000,4000,6000,8000,10000]}
  ]
}">

</div>
<p>Capture zone width scales linearly with pumping rate and inversely with the product <span class="math inline">q_0 b</span> (natural groundwater flux × saturated thickness). A fast aquifer (high <span class="math inline">q_0 b</span>) requires much higher pumping to capture the same plume width. This explains why pump-and-treat is economically challenging in high-transmissivity aquifers: the energy cost of pumping against a large regional flux is prohibitive, and the required pumping rate may exceed practical limits.</p>
<hr>
<h2 id="interpretation" class="anchored">7. Interpretation</h2>
<p>The capture zone analysis reveals a fundamental constraint on pump-and-treat: the pumping rate must exceed the natural groundwater flux through the entire plume cross-section. In a transmissive aquifer with a 50 m wide plume and <span class="math inline">q_0 b = 0.05</span> m²/day: <span class="math inline">Q_{\min} = 50 \times 0.05 = 2.5</span> m³/day. This is achievable at modest cost. But in a highly transmissive alluvial aquifer with <span class="math inline">q_0 b = 0.5</span> m²/day: <span class="math inline">Q_{\min} = 25</span> m³/day — still manageable. The challenge becomes acute when the plume is large (hundreds of metres wide) in a fast aquifer.</p>
<p>The NPV comparison shows that pump-and-treat is economically justified primarily when containment is legally required (imminent receptor risk) or when the site generates ongoing income that offsets remediation cost. For sites where receptor risk is manageable and MNA criteria are met, monitored natural attenuation is typically 5–10× less expensive in present value terms. The regulatory decision between these alternatives is therefore not purely technical — it involves risk tolerance, timeline commitments, and institutional trust in models that predict future concentrations.</p>
<hr>
<h2 id="what-could-go-wrong" class="anchored">8. What Could Go Wrong?</h2>
<p><strong>Pump-and-treat asymptotically approaches but never achieves the cleanup goal.</strong> Aquifer heterogeneity creates high-concentration residuals in low-permeability zones that slowly diffuse back into the pumped water. The characteristic <strong>“tail” behaviour</strong> — rapid initial concentration decline, followed by extremely slow decline toward the cleanup standard — has been observed at virtually every long-running P&amp;T site. Cost projections based on initial concentration decline rates consistently underestimate the total project cost.</p>
<p><strong>ISCO can mobilise contaminants.</strong> Injecting oxidant into a NAPL source zone can increase contaminant concentrations downgradient during and after treatment by: (1) temporarily increasing NAPL dissolution rate (the oxidant creates a concentration gradient that drives faster dissolution), and (2) oxidant propagation beyond the target zone destroying monitored natural attenuation capacity (e.g., eliminating electron donor supply needed by reductive dechlorinators). ISCO should not be applied without careful assessment of downgradient receptor risk during the treatment period.</p>
<p><strong>MNA requires long-term institutional memory.</strong> A 30-year MNA programme requires maintaining monitoring wells, records, and institutional knowledge across multiple ownership and regulatory transitions. Sites that were accepted for MNA in the 1990s have in some cases lost their monitoring programmes, been redeveloped without proper assessment, and created new exposure pathways. MNA is not a “walk away” strategy — it requires sustained commitment that many organisations and regulatory agencies are poorly equipped to maintain.</p>
<p><strong>Discount rates systematically underweight future costs.</strong> A 5% discount rate reduces a $1M cost in year 30 to $231K present value — an 77% reduction. This means long-duration remediation (pump-and-treat for 50 years) appears less expensive in NPV terms than it actually is in undiscounted terms. The choice of discount rate is not politically neutral: lower rates favour long-duration approaches; higher rates favour front-loaded capital investment (like ISCO). For projects with environmental and public health consequences, zero or near-zero discount rates for benefit and harm are defensible in principle, even if unconventional in practice.</p>
<hr>
<h2 id="summary" class="anchored">9. Summary</h2>
<p>Pump-and-treat hydraulic containment requires a minimum pumping rate <span class="math inline">Q_{\min} = W_{\text{plume}} \cdot q_0 \cdot b</span> to capture a plume of width <span class="math inline">W_{\text{plume}}</span> in an aquifer with Darcy flux <span class="math inline">q_0</span> and saturated thickness <span class="math inline">b</span>. The Theis equation <span class="math inline">s = QW(u)/(4\pi T)</span> describes transient drawdown around a pumping well; the Cooper-Jacob approximation simplifies this for <span class="math inline">u &lt; 0.05</span>.</p>
<p>ISCO stoichiometry determines oxidant reagent mass from balanced chemical equations, adjusted upward for natural oxidant demand and safety factors. MNA is accepted when spatial concentration decline demonstrates active biodegradation and plume stability. NPV cost comparison discounts all future cash flows: <span class="math inline">\text{NPV} = C_0 + C_{\text{OM}} \cdot [(1-(1+r)^{-T})/r]</span>. Over 30-year horizons, pump-and-treat typically costs 5–10× more than MNA in NPV terms.</p>
<p><strong>Key equations:</strong></p>
<p><span class="math display">Q_{\min} = W_{\text{plume}} \cdot q_0 \cdot b</span></p>
<p><span class="math display">y_{\max} = Q/(q_0 b), \quad x_s = -Q/(2\pi q_0 b)</span></p>
<p><span class="math display">s(r,t) = \frac{Q}{4\pi T}W(u), \quad u = \frac{r^2 S}{4Tt}</span></p>
<p><span class="math display">\text{NPV} = C_0 + C_{\text{OM}}\cdot\frac{1-(1+r)^{-T}}{r}</span></p>
<hr>
<h2 id="math-refresher" class="anchored">Math Refresher</h2>
<p><strong>The well function <span class="math inline">W(u)</span>.</strong> The Theis well function is <span class="math inline">W(u) = \int_u^\infty e^{-t}/t\,dt</span> — the exponential integral <span class="math inline">E_1(u)</span>. For small <span class="math inline">u</span> (<span class="math inline">u &lt; 0.05</span>), the approximation <span class="math inline">W(u) \approx -\gamma - \ln u \approx -0.5772 - \ln u</span> works well (the Cooper-Jacob simplification). Plotted against <span class="math inline">\log u</span>, <span class="math inline">W(u)</span> decreases from large values at small <span class="math inline">u</span> to near zero at large <span class="math inline">u</span> — large <span class="math inline">u</span> corresponds to short times or large distances where drawdown has not yet propagated. The Theis type curve is used in aquifer pump tests to estimate <span class="math inline">T</span> and <span class="math inline">S</span> by matching observed drawdown data to the theoretical <span class="math inline">W(u)</span> curve.</p>
<p><strong>Present value and the annuity factor.</strong> The present value of a stream of equal annual payments <span class="math inline">C</span> for <span class="math inline">T</span> years at discount rate <span class="math inline">r</span> is <span class="math inline">C \times [(1-(1+r)^{-T})/r]</span>. This annuity factor equals the number of years <span class="math inline">T</span> when <span class="math inline">r = 0</span> (no discounting); it is less than <span class="math inline">T</span> for <span class="math inline">r &gt; 0</span> because future payments are worth less. For <span class="math inline">r = 5\%</span> and <span class="math inline">T = 30</span>, the factor is 15.37 — equivalent to 15.4 years of payments in present value terms, even though 30 actual payments will be made. This compression of future costs into a smaller present value is the fundamental reason why long-duration liabilities appear more manageable in economic analyses than they do to communities that must actually live with them for 30 years.</p>


<footer class="wayward-footer">
  <div class="wayward-footer__inner">
    <div class="wayward-footer__brand">
      <div class="wayward-footer__logo">WaywardHouse<span>.</span></div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wayward-footer__group" aria-labelledby="footer-reading">
      <h2 id="footer-reading" class="anchored">Reading</h2>
      <a href="../articles/">Articles</a>
      <a href="../learn/">Learn</a>
      <a href="../archive.html">Archive</a>
      <a href="../start-here.html">Start Here</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-site">
      <h2 id="footer-site" class="anchored">Site</h2>
      <a href="../start-here.html">Start Here</a>
      <a href="../about.html">About</a>
      <a href="../contact.html">Contact</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-resources">
      <h2 id="footer-resources" class="anchored">Resources</h2>
      <a href="../topics/">All Topics</a>
      <a href="../privacy.html">Privacy Policy</a>
      <a href="../terms.html">Terms of Use</a>
    </nav>
  </div>
</footer>

<script type="module" src="../assets/dist/main.js"></script>
<script type="module" src="../assets/js/core.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>