<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-05">
<meta name="description" content="Every year, roughly 35 billion tonnes of soil are stripped from agricultural land worldwide. The Revised Universal Soil Loss Equation distils decades of erosion plot data into five measurable factors — rainfall, soil, slope, cover, and management. This essay derives each factor from first principles, shows how they combine, and demonstrates how to use the equation to design conservation practices.">

<title>Soil Erosion and the RUSLE – Computational Geography</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-734cb40618f438257b19a1e532635a32.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script>
  (function () {
    document.documentElement.dataset.theme = 'light';
    document.documentElement.dataset.brand = 'wayward';
    try {
      localStorage.removeItem('theme');
    } catch (err) {
      void err;
    }
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-math tag-hash-viz">


<header id="title-block-header">
<h1 class="title"><span class="chapter-title">Soil Erosion and the RUSLE</span></h1>
<p class="subtitle">Decomposing a landscape’s vulnerability into factors you can measure, map, and modify</p>

<p class="date">2026-03-05</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-question" id="toc-the-question">1. The Question</a></li>
  <li><a href="#the-conceptual-model" id="toc-the-conceptual-model">2. The Conceptual Model</a></li>
  <li><a href="#building-the-mathematical-model" id="toc-building-the-mathematical-model">3. Building the Mathematical Model</a>
  <ul>
  <li><a href="#rainfall-erosivity-the-r-factor" id="toc-rainfall-erosivity-the-r-factor">3.1 Rainfall Erosivity: The R Factor</a></li>
  <li><a href="#soil-erodibility-the-k-factor" id="toc-soil-erodibility-the-k-factor">3.2 Soil Erodibility: The K Factor</a></li>
  <li><a href="#slope-length-and-steepness-the-ls-factor" id="toc-slope-length-and-steepness-the-ls-factor">3.3 Slope Length and Steepness: The LS Factor</a></li>
  <li><a href="#cover-and-management-the-c-factor" id="toc-cover-and-management-the-c-factor">3.4 Cover and Management: The C Factor</a></li>
  <li><a href="#support-practice-the-p-factor" id="toc-support-practice-the-p-factor">3.5 Support Practice: The P Factor</a></li>
  <li><a href="#the-sediment-delivery-ratio" id="toc-the-sediment-delivery-ratio">3.6 The Sediment Delivery Ratio</a></li>
  </ul></li>
  <li><a href="#worked-example-by-hand" id="toc-worked-example-by-hand">4. Worked Example by Hand</a></li>
  <li><a href="#computational-implementation" id="toc-computational-implementation">5. Computational Implementation</a></li>
  <li><a href="#visualization" id="toc-visualization">6. Visualization</a></li>
  <li><a href="#interpretation" id="toc-interpretation">7. Interpretation</a></li>
  <li><a href="#what-could-go-wrong" id="toc-what-could-go-wrong">8. What Could Go Wrong?</a></li>
  <li><a href="#summary" id="toc-summary">9. Summary</a></li>
  <li><a href="#math-refresher" id="toc-math-refresher">Math Refresher</a></li>
  </ul>
</nav>
<p>Soil erosion is a slow catastrophe. Unlike a flood or a landslide, it rarely makes headlines — it removes a fraction of a millimetre per year, invisible in any single rainstorm, catastrophic over decades. In Alberta, a province where topsoil depths average 15–30 cm and can take thousands of years to form, losing even 2–3 mm per year represents a permanent capital loss from the agricultural system.</p>
<p>The Revised Universal Soil Loss Equation (RUSLE) is arguably the most widely used quantitative model in applied geomorphology. It is empirical — built from regression on thousands of erosion plot measurements rather than derived from physical first principles — but it is structured in a way that allows each factor to be understood, measured, and manipulated independently. That structure is worth understanding carefully.</p>
<hr>
<h2 id="the-question" class="anchored">1. The Question</h2>
<p>How can we predict annual soil loss from a hillslope, and which factors dominate? More practically: given a proposed land use change or a proposed conservation practice, by how much will it change erosion?</p>
<hr>
<h2 id="the-conceptual-model" class="anchored">2. The Conceptual Model</h2>
<p>RUSLE models the average annual soil loss <span class="math inline">A</span> [t ha⁻¹ yr⁻¹] as the product of five independent factors:</p>
<p><span class="math display">A = R \cdot K \cdot LS \cdot C \cdot P</span></p>
<p>Each factor represents one class of control on erosion:</p>
<ul>
<li><strong>R</strong> — rainfall erosivity: how energetically aggressive is the precipitation?</li>
<li><strong>K</strong> — soil erodibility: how resistant is the soil to detachment and transport?</li>
<li><strong>LS</strong> — slope length and steepness: how much does topography amplify transport?</li>
<li><strong>C</strong> — cover and management: how much does vegetation and residue protect the surface?</li>
<li><strong>P</strong> — support practice: how much do conservation practices reduce delivery?</li>
</ul>
<p>The product structure assumes the factors are multiplicative and independent. This is an approximation — in reality, slope and rainfall interact — but it is a powerful one because it means we can assess each factor separately and identify which is the leverage point for a given landscape.</p>
<hr>
<h2 id="building-the-mathematical-model" class="anchored">3. Building the Mathematical Model</h2>
<h3 id="rainfall-erosivity-the-r-factor" class="anchored">3.1 Rainfall Erosivity: The R Factor</h3>
<p>Not all rainfall is equally erosive. A gentle drizzle delivers water but almost no kinetic energy. A high-intensity convective storm drives raindrops at terminal velocity into bare soil with enough energy to splash particles tens of centimetres and seal the soil surface with a thin crust.</p>
<p>The <strong>rainfall erosivity index</strong> <span class="math inline">EI_{30}</span> for a single storm is:</p>
<p><span class="math display">EI_{30} = E \cdot I_{30}</span></p>
<p>where <span class="math inline">E</span> [MJ ha⁻¹] is the total kinetic energy of the storm and <span class="math inline">I_{30}</span> [mm h⁻¹] is the maximum 30-minute rainfall intensity. The kinetic energy per unit depth of rainfall is:</p>
<p><span class="math display">e = 0.29 \left[1 - 0.72 \exp(-0.05 \, i)\right]</span></p>
<p>where <span class="math inline">e</span> [MJ ha⁻¹ mm⁻¹] is the unit energy and <span class="math inline">i</span> [mm h⁻¹] is the instantaneous rainfall intensity.</p>
<p>The annual R factor is the sum of <span class="math inline">EI_{30}</span> values over all erosive events in a year, averaged across years:</p>
<p><span class="math display">R = \overline{\sum_{\text{storms}} EI_{30}}</span></p>
<p>For Alberta’s agricultural region, <span class="math inline">R</span> ranges from approximately 80 MJ mm ha⁻¹ h⁻¹ yr⁻¹ in the dry south to 150 in the more convective east. For comparison, the US Corn Belt reaches 200–300.</p>
<h3 id="soil-erodibility-the-k-factor" class="anchored">3.2 Soil Erodibility: The K Factor</h3>
<p>The K factor [t ha h ha⁻¹ MJ⁻¹ mm⁻¹] measures how easily a standard unit of rainfall erosivity detaches and transports a standard unit of soil. It is determined empirically from plots of bare, tilled soil under natural rainfall over many years.</p>
<p>The dominant controls on K are soil texture (particularly silt content, which is easily detached), organic matter content (which binds particles and increases infiltration), and structure (aggregation resists detachment; crusting promotes runoff).</p>
<p>An empirical equation due to Wischmeier (1971) estimates K from measurable soil properties:</p>
<p><span class="math display">K = \frac{2.1 \times 10^{-4}(12-\text{OM})M^{1.14} + 3.25(s-2) + 2.5(p-3)}{100}</span></p>
<p>where OM is organic matter percentage [%], <span class="math inline">M = (\text{\% silt} + \text{\% very fine sand}) \times (100 - \text{\% clay})</span>, <span class="math inline">s</span> is a soil structure code (1–4), and <span class="math inline">p</span> is a permeability class (1–6).</p>
<p>Typical K values: fine sandy loam 0.025–0.035; silt loam 0.035–0.055; silty clay loam 0.025–0.045 t ha h ha⁻¹ MJ⁻¹ mm⁻¹.</p>
<h3 id="slope-length-and-steepness-the-ls-factor" class="anchored">3.3 Slope Length and Steepness: The LS Factor</h3>
<p>Topography amplifies erosion in two ways: longer slopes accumulate more runoff from upslope (increasing transport capacity), and steeper slopes increase flow velocity (increasing both detachment and transport).</p>
<p>The LS factor combines both effects. For a slope of length <span class="math inline">\lambda</span> [m] and steepness <span class="math inline">\theta</span> [degrees]:</p>
<p><span class="math display">L = \left(\frac{\lambda}{22.13}\right)^m</span></p>
<p>where the exponent <span class="math inline">m</span> depends on slope steepness: - <span class="math inline">m = 0.2</span> for <span class="math inline">\theta &lt; 1°</span> - <span class="math inline">m = 0.3</span> for $1° &lt; 3°$ - <span class="math inline">m = 0.4</span> for $3° &lt; 5°$ - <span class="math inline">m = 0.5</span> for <span class="math inline">\theta \geq 5°</span></p>
<p>The steepness factor <span class="math inline">S</span> uses different equations below and above 9% gradient (about 5.1°):</p>
<p>For <span class="math inline">s &lt; 9\%</span> (where <span class="math inline">s = 100 \tan\theta</span>):</p>
<p><span class="math display">S = 10.8 \sin\theta + 0.03</span></p>
<p>For <span class="math inline">s \geq 9\%</span>:</p>
<p><span class="math display">S = 16.8 \sin\theta - 0.50</span></p>
<p>The divisor 22.13 in the <span class="math inline">L</span> formula is the slope length of the standard RUSLE plot. An <span class="math inline">LS</span> value of 1.0 therefore represents exactly that reference condition.</p>
<p>For raster GIS applications, <span class="math inline">\lambda</span> is estimated from the upslope contributing area <span class="math inline">A_s</span> [m²] per unit contour width <span class="math inline">b</span> [m]:</p>
<p><span class="math display">\lambda \approx \frac{A_s}{b}</span></p>
<p>This allows LS to be computed from a DEM without having to delineate individual slope profiles.</p>
<h3 id="cover-and-management-the-c-factor" class="anchored">3.4 Cover and Management: The C Factor</h3>
<p>The C factor is dimensionless, ranging from near 0 (completely protected surface) to 1.0 (continuously fallow, tilled bare soil — the standard reference condition). It integrates the protective effect of:</p>
<ul>
<li>Canopy cover (intercepts raindrops before impact)</li>
<li>Ground cover (residue, mulch, living stems at the surface)</li>
<li>Soil surface roughness (temporary detention storage)</li>
<li>Soil moisture (antecedent conditions affecting infiltration)</li>
</ul>
<p>C values for common agricultural land covers (approximate, Saskatchewan conditions): | Land cover | C | |—|—| | Continuously fallow | 1.00 | | Spring wheat, conventional till | 0.20–0.35 | | Spring wheat, no-till | 0.05–0.12 | | Permanent pasture (good condition) | 0.003–0.01 | | Native grassland | 0.001–0.003 | | Dense forest | 0.0001–0.001 |</p>
<p>The contrast between conventional tillage and native grassland spans three orders of magnitude in C. This is why agricultural conversion is such a powerful driver of erosion rates.</p>
<h3 id="support-practice-the-p-factor" class="anchored">3.5 Support Practice: The P Factor</h3>
<p>The P factor [dimensionless, 0–1] captures the effect of deliberate conservation practices that reduce erosion relative to farming straight up-and-down slope. Like C, P = 1.0 is the reference (no conservation practice).</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Practice</th>
<th>P (typical)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up-and-down slope tillage</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>Contour farming, 3–8% slopes</td>
<td>0.50</td>
</tr>
<tr class="odd">
<td>Contour farming, 8–12% slopes</td>
<td>0.60</td>
</tr>
<tr class="even">
<td>Strip cropping, contour</td>
<td>0.25–0.40</td>
</tr>
<tr class="odd">
<td>Terracing</td>
<td>0.10–0.15</td>
</tr>
</tbody>
</table>
<h3 id="the-sediment-delivery-ratio" class="anchored">3.6 The Sediment Delivery Ratio</h3>
<p>RUSLE predicts gross soil detachment from a slope. Not all detached sediment leaves the catchment — some is redeposited in footslope positions, floodplains, or behind conservation structures. The <strong>sediment delivery ratio</strong> SDR [dimensionless] is the fraction of detached sediment that reaches the catchment outlet:</p>
<p><span class="math display">\text{Sediment yield} = A \cdot \text{Area} \cdot \text{SDR}</span></p>
<p>SDR scales empirically with catchment area <span class="math inline">A_c</span> [km²]:</p>
<p><span class="math display">\text{SDR} = 0.627 \cdot A_c^{-0.403}</span></p>
<p>This is a rough approximation — SDR varies considerably with channel connectivity, slope length, and vegetation — but it provides a first-order estimate useful for conservation planning.</p>
<hr>
<h2 id="worked-example-by-hand" class="anchored">4. Worked Example by Hand</h2>
<p><strong>Setting:</strong> A cultivated field on the Alberta plains. We want to estimate current annual soil loss and the reduction achievable by switching to no-till with contour farming.</p>
<p><strong>Given:</strong> - R = 120 MJ mm ha⁻¹ h⁻¹ yr⁻¹ (central Alberta) - K = 0.038 t ha h ha⁻¹ MJ⁻¹ mm⁻¹ (silty loam) - Slope length λ = 120 m, slope angle θ = 4° (so <span class="math inline">s = 7\%</span>, <span class="math inline">m = 0.4</span>) - Current: spring wheat, conventional till (C = 0.28), no practice (P = 1.00) - Proposed: no-till + contour farming (C = 0.08, P = 0.50)</p>
<p><strong>Step 1: L factor</strong></p>
<p><span class="math display">L = \left(\frac{120}{22.13}\right)^{0.4} = (5.42)^{0.4}</span></p>
<p><span class="math display">\ln(5.42) = 1.690 \quad\Rightarrow\quad 0.4 \times 1.690 = 0.676 \quad\Rightarrow\quad L = e^{0.676} = 1.966</span></p>
<p><strong>Step 2: S factor</strong> (slope 7%, below 9% threshold)</p>
<p><span class="math display">\sin(4°) = 0.0698</span></p>
<p><span class="math display">S = 10.8 \times 0.0698 + 0.03 = 0.754 + 0.03 = 0.784</span></p>
<p><strong>Step 3: LS factor</strong></p>
<p><span class="math display">LS = L \times S = 1.966 \times 0.784 = 1.541</span></p>
<p><strong>Step 4: Current soil loss</strong></p>
<p><span class="math display">A_{\text{current}} = 120 \times 0.038 \times 1.541 \times 0.28 \times 1.00</span></p>
<p><span class="math display">= 120 \times 0.038 \times 1.541 \times 0.28 = \mathbf{1.97} \text{ t ha}^{-1} \text{ yr}^{-1}</span></p>
<p><strong>Step 5: Proposed soil loss</strong></p>
<p><span class="math display">A_{\text{proposed}} = 120 \times 0.038 \times 1.541 \times 0.08 \times 0.50</span></p>
<p><span class="math display">= 120 \times 0.038 \times 1.541 \times 0.04 = \mathbf{0.28} \text{ t ha}^{-1} \text{ yr}^{-1}</span></p>
<p><strong>Reduction:</strong> <span class="math inline">(1.97 - 0.28) / 1.97 = 85.7\%</span> reduction in annual soil loss from a change in management alone, with no modification to the landscape itself. The topography and soil are unchanged; only C and P change.</p>
<p>This illustrates the fundamental leverage of conservation practice: because RUSLE is multiplicative, reducing C and P together produces compounding gains. Cutting C by $0.08/0.28 = 0.286$ and P by $0.50$ gives a combined factor of $0.286 = 0.143$ — the product of independent improvements.</p>
<hr>
<h2 id="computational-implementation" class="anchored">5. Computational Implementation</h2>
<pre><code>function RUSLE(R, K, lambda_m, theta_deg, C, P):
    # Slope steepness s (percent)
    s = 100 * tan(radians(theta_deg))
    # m exponent
    if s &lt; 1:   m = 0.2
    elif s &lt; 3: m = 0.3
    elif s &lt; 5: m = 0.4
    else:       m = 0.5
    # L factor
    L = (lambda_m / 22.13) ^ m
    # S factor
    sin_theta = sin(radians(theta_deg))
    if s &lt; 9:
        S = 10.8 * sin_theta + 0.03
    else:
        S = 16.8 * sin_theta - 0.50
    # Annual soil loss
    A = R * K * L * S * C * P
    return A</code></pre>
<pre class="{pyodide}"><code>import numpy as np

def rusle(R, K, lam, theta_deg, C, P):
    s = 100 * np.tan(np.radians(theta_deg))
    m = 0.2 if s &lt; 1 else (0.3 if s &lt; 3 else (0.4 if s &lt; 5 else 0.5))
    L = (lam / 22.13) ** m
    sin_t = np.sin(np.radians(theta_deg))
    S = (10.8 * sin_t + 0.03) if s &lt; 9 else (16.8 * sin_t - 0.50)
    return R * K * L * S * C * P

R, K, lam, theta = 120, 0.038, 120, 4.0

current  = rusle(R, K, lam, theta, C=0.28, P=1.00)
proposed = rusle(R, K, lam, theta, C=0.08, P=0.50)
print(f"Current (conv. till):   {current:.2f} t ha⁻¹ yr⁻¹")
print(f"Proposed (no-till+contour): {proposed:.2f} t ha⁻¹ yr⁻¹")
print(f"Reduction: {(current-proposed)/current*100:.1f}%")</code></pre>
<hr>
<h2 id="visualization" class="anchored">6. Visualization</h2>
<div data-viz="echarts" style="height:420px" data-options="{
&quot;title&quot;: {&quot;text&quot;: &quot;Annual Soil Loss by Slope Angle and Management Practice&quot;, &quot;textStyle&quot;: {&quot;fontSize&quot;: 14}},
&quot;tooltip&quot;: {&quot;trigger&quot;: &quot;axis&quot;, &quot;formatter&quot;: &quot;{b}°: {c} t ha⁻¹ yr⁻¹&quot;},
&quot;legend&quot;: {&quot;data&quot;: [&quot;Conventional till (C=0.28, P=1.0)&quot;, &quot;No-till + contour (C=0.08, P=0.5)&quot;, &quot;Native grassland (C=0.002, P=1.0)&quot;], &quot;bottom&quot;: 0},
&quot;xAxis&quot;: {&quot;name&quot;: &quot;Slope Angle (degrees)&quot;, &quot;nameLocation&quot;: &quot;middle&quot;, &quot;nameGap&quot;: 30,
&quot;data&quot;: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
&quot;yAxis&quot;: {&quot;name&quot;: &quot;A (t ha⁻¹ yr⁻¹)&quot;, &quot;nameLocation&quot;: &quot;middle&quot;, &quot;nameGap&quot;: 45},
&quot;series&quot;: [
{&quot;name&quot;: &quot;Conventional till (C=0.28, P=1.0)&quot;, &quot;type&quot;: &quot;line&quot;, &quot;smooth&quot;: true,
&quot;data&quot;: [0.52, 0.90, 1.27, 1.97, 2.71, 3.54, 4.43, 5.41, 7.05, 8.87]},
{&quot;name&quot;: &quot;No-till + contour (C=0.08, P=0.5)&quot;, &quot;type&quot;: &quot;line&quot;, &quot;smooth&quot;: true,
&quot;data&quot;: [0.07, 0.13, 0.18, 0.28, 0.39, 0.51, 0.63, 0.77, 1.01, 1.27]},
{&quot;name&quot;: &quot;Native grassland (C=0.002, P=1.0)&quot;, &quot;type&quot;: &quot;line&quot;, &quot;smooth&quot;: true,
&quot;data&quot;: [0.0037, 0.0064, 0.0091, 0.014, 0.019, 0.025, 0.032, 0.039, 0.050, 0.063]}
]
}"></div>
<p>The three curves share identical R, K, and LS inputs; they differ only in C and P. The vertical distance between conventional tillage and native grassland — roughly two orders of magnitude — quantifies the erosion penalty of agricultural conversion across every slope angle.</p>
<hr>
<h2 id="interpretation" class="anchored">7. Interpretation</h2>
<p>Several results from the worked example deserve emphasis.</p>
<p><strong>The C factor dominates on gentle terrain.</strong> On slopes below about 5°, the LS factor is close to 1 and the soil loss is almost entirely determined by C and P. Conservation practice choices matter most where slopes are gentle — not because erosion is worst there, but because that is where leverage is highest and the slope itself cannot be changed.</p>
<p><strong>Steeper terrain shifts the balance toward LS.</strong> Above 8–10°, the LS factor begins to grow rapidly, and the benefit of conservation practice in relative terms remains the same but absolute losses become large regardless. On slopes above 15°, erosion control requires either terracing (which changes the effective slope length) or permanent vegetation.</p>
<p><strong>Tolerance thresholds.</strong> Soil loss tolerance T [t ha⁻¹ yr⁻¹] is the maximum rate at which erosion can occur while still maintaining long-term soil productivity. For Alberta soils, T is typically 6–11 t ha⁻¹ yr⁻¹ for deep soils and 3–5 for shallow soils. The conventional tillage scenario in our example (1.97 t ha⁻¹ yr⁻¹) falls within tolerance — but only because the slope is gentle. Steeper versions of the same field would not.</p>
<hr>
<h2 id="what-could-go-wrong" class="anchored">8. What Could Go Wrong?</h2>
<p><strong>RUSLE was calibrated on small plots, not catchments.</strong> The standard RUSLE dataset comes from erosion plots 22 m long and 1.8 m wide. Extrapolating to 500-metre slopes or entire fields introduces errors from flow concentration, gullying, and deposition that the equation does not represent.</p>
<p><strong>The independence assumption fails for extreme events.</strong> A single extreme storm (high R) on saturated soil (high effective K) on a freshly tilled field (high C) can produce annual-average erosion in a single afternoon. RUSLE’s annualised factors average over these events and underpredict peak transport rates and gully initiation.</p>
<p><strong>SDR estimation is very uncertain.</strong> The empirical SDR formula has high scatter — a single area estimate might have a factor-of-2 uncertainty. For regional sediment budgets, this matters. For field-scale conservation design, SDR is less critical because we are targeting the hillslope source, not the outlet flux.</p>
<p><strong>C factor temporal dynamics.</strong> RUSLE uses an annual average C, but erosion risk changes dramatically through the year: bare soil in early spring (post-tillage, pre-germination) is far more vulnerable than the same field in July under a full crop canopy. Sub-annual RUSLE applications (using monthly or bi-weekly C subfactors) give much better estimates of seasonal erosion patterns.</p>
<hr>
<h2 id="summary" class="anchored">9. Summary</h2>
<p>The RUSLE decomposes the complex process of soil erosion into five independently measurable factors whose product gives annual average soil loss per unit area. The multiplicative structure means that conservation practice works by reducing the value of one or more factors — and that combined practices (C and P together) produce compounding benefits.</p>
<p>The key insight from the factor analysis: on most agricultural landscapes, the C factor is the single highest-leverage intervention point. Changing land cover or management from conventional tillage to no-till with residue cover can reduce erosion by 70–90% with no change to the physical landscape. This is why soil conservation programmes focus on agronomic practice first, engineering works second.</p>
<p><strong>Key equation:</strong></p>
<p><span class="math display">A = R \cdot K \cdot L \cdot S \cdot C \cdot P \quad \text{[t ha}^{-1}\text{ yr}^{-1}\text{]}</span></p>
<p><span class="math display">L = \left(\frac{\lambda}{22.13}\right)^m, \quad S = 10.8 \sin\theta + 0.03 \;(\theta &lt; 5.1°)</span></p>
<hr>
<h2 id="math-refresher" class="anchored">Math Refresher</h2>
<p><strong>Why multiplication?</strong> The RUSLE product structure implies that if any factor is zero, the total is zero — no rainfall means no erosion regardless of slope, no matter how erodible the soil. This is physically correct. It also implies that the factors are statistically independent controls, which is an approximation but a useful one.</p>
<p><strong>Percent slope and degrees.</strong> Slope steepness <span class="math inline">s</span> in percent is $100 $. For small angles, <span class="math inline">\tan\theta \approx \sin\theta \approx \theta</span> (in radians), so percent slope is approximately <span class="math inline">\theta \times (180/\pi) \times (1/0.573) \approx \theta^\circ \times 1.75</span>. A 10% slope is approximately 5.7°.</p>
<p><strong>Power functions and exponents.</strong> The L factor uses <span class="math inline">(\lambda/22.13)^m</span>. When <span class="math inline">m = 0.5</span>, this is a square root — doubling the slope length increases L by <span class="math inline">\sqrt{2} \approx 1.41</span>, not 2. Erosion is sublinear in slope length: long slopes produce more erosion per unit area than short ones, but the relationship tapers off. This reflects the fact that sediment transport capacity grows with flow depth, which grows slower than linearly with contributing length.</p>


<footer class="wayward-footer">
  <div class="wayward-footer__inner">
    <div class="wayward-footer__brand">
      <div class="wayward-footer__logo">WaywardHouse<span>.</span></div>
      <p>Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
    </div>

    <nav class="wayward-footer__group" aria-labelledby="footer-reading">
      <h2 id="footer-reading" class="anchored">Reading</h2>
      <a href="https://wayward.house/articles/">Articles</a>
      <a href="https://wayward.house/learn/">Library</a>
      <a href="https://wayward.house/archive.html">Archive</a>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-site">
      <h2 id="footer-site" class="anchored">Site</h2>
      <a href="https://wayward.house/start-here.html">Choose Your Path</a>
      <a href="https://wayward.house/about.html">About</a>
      <a href="https://wayward.house/contact.html">Contact</a>
    </nav>

    <nav class="wayward-footer__group" aria-labelledby="footer-resources">
      <h2 id="footer-resources" class="anchored">Resources</h2>
      <a href="https://wayward.house/topics/">All Topics</a>
      <a href="https://wayward.house/privacy.html">Privacy Policy</a>
      <a href="https://wayward.house/terms.html">Terms of Use</a>
    </nav>
  </div>
</footer>

<script type="module" src="../assets/dist/main.js"></script>
<script type="module" src="../assets/js/core.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>