<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-02-17">
<meta name="description" content="A detailed data foundation for understanding Alberta’s role in Confederation — grounding policy debate in measurable economic reality, with particular attention to interprovincial trade flows and fiscal transfers.">

<title>A Trade Reality Check – WaywardHouse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<link href="../assets/images/logo.webp" rel="icon">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-640605f58ae58ee79329c070719e555b.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<style>html{ scroll-behavior: smooth; }</style>
<script>
  (function () {
    document.documentElement.dataset.theme = 'light';
    document.documentElement.dataset.brand = 'wayward';
    document.documentElement.dataset.newsletterApi = "https://wayward.house/api/subscribe";
    window.MAPBOX_TOKEN = "pk.eyJ1IjoiYnJlYWRlZGNvZCIsImEiOiJjbW0xa25qc2EwMmtwMnJwejJlNndqdnoxIn0._7I9PwXuFLrOQINVZ84y1w";
    window.NEWSLETTER_API_URL = "https://wayward.house/api/subscribe";
    try {
      localStorage.removeItem('theme');
    } catch (err) {
      void err;
    }
  })();
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,700;1,800&amp;family=Barlow:wght@300;400;500;600&amp;family=IBM+Plex+Mono:ital,wght@0,300;0,400;0,500;1,300&amp;family=Literata:ital,opsz,wght@0,7..72,300;0,7..72,400;0,7..72,500;1,7..72,300;1,7..72,400&amp;display=swap" rel="stylesheet">
<!-- Cloudflare Web Analytics -->
<script defer="" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;token&quot;: &quot;62c47d78bf9d4c80972d4e6242d79ff8&quot;}"></script>
<!-- End Cloudflare Web Analytics -->


<link rel="stylesheet" href="../assets/css/quarto-wayward.css">
</head>

<body class="reading-body tag-hash-viz">

<script>
  (function () {
    // Avoid layout jump: the fixed header relies on body padding.
    document.body.classList.add('wayward-shell');
  })();
</script>

<header class="wayward-header" id="wayward-header">
  <div class="wayward-header__inner">
    <a class="wayward-brand" href="../">
      <span class="wayward-brand__mark">Wayward</span><span class="wayward-brand__dot">·</span><span class="wayward-brand__mark">House</span>
    </a>

    <nav class="wayward-nav" aria-label="Primary">
      <a href="../articles/">Essays</a>
      <a href="../articles/system-signals/">System Signals</a>
      <a href="../learn/">Learn</a>
      <a href="../topics/">Topics</a>
      <a href="../about.html">About</a>
    </nav>

    <div class="wayward-header__actions">
      <a href="../subscribe.html" class="wayward-subscribe-btn">Subscribe</a>
    </div>
  </div>
</header>

<script>
(function () {
  var header = document.getElementById('wayward-header');
  if (!header) return;
  function onScroll() {
    header.classList.toggle('is-scrolled', window.scrollY > 48);
  }
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();
})();
</script>

<header id="title-block-header">
<h1 class="title">A Trade Reality Check</h1>
<p class="subtitle">What the Province Produces, What It Exports, and What It Needs From Everyone Else</p>

<p class="date">2026-02-17</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#albertas-economic-scale" id="toc-albertas-economic-scale">1. Alberta’s Economic Scale</a></li>
  <li><a href="#what-alberta-actually-produces" id="toc-what-alberta-actually-produces">2. What Alberta Actually Produces</a>
  <ul>
  <li><a href="#energy-the-foundation" id="toc-energy-the-foundation">2.1 Energy: The Foundation</a></li>
  <li><a href="#agriculture-the-underappreciated-pillar" id="toc-agriculture-the-underappreciated-pillar">2.2 Agriculture: The Underappreciated Pillar</a></li>
  </ul></li>
  <li><a href="#international-trade-where-albertas-exports-go" id="toc-international-trade-where-albertas-exports-go">3. International Trade: Where Alberta’s Exports Go</a>
  <ul>
  <li><a href="#the-export-numbers" id="toc-the-export-numbers">3.1 The Export Numbers</a></li>
  <li><a href="#the-tmx-pipeline-effect" id="toc-the-tmx-pipeline-effect">3.2 The TMX Pipeline Effect</a></li>
  <li><a href="#the-import-side" id="toc-the-import-side">3.3 The Import Side</a></li>
  </ul></li>
  <li><a href="#interprovincial-trade-alberta-within-canada" id="toc-interprovincial-trade-alberta-within-canada">4. Interprovincial Trade: Alberta Within Canada</a>
  <ul>
  <li><a href="#albertas-interprovincial-exports" id="toc-albertas-interprovincial-exports">4.1 Alberta’s Interprovincial Exports</a></li>
  <li><a href="#what-alberta-buys-from-other-provinces" id="toc-what-alberta-buys-from-other-provinces">4.2 What Alberta Buys from Other Provinces</a></li>
  <li><a href="#the-interprovincial-dependency-map" id="toc-the-interprovincial-dependency-map">4.3 The Interprovincial Dependency Map</a></li>
  </ul></li>
  <li><a href="#albertas-fiscal-position-the-federal-transfer-reality" id="toc-albertas-fiscal-position-the-federal-transfer-reality">5. Alberta’s Fiscal Position: The Federal Transfer Reality</a>
  <ul>
  <li><a href="#albertas-net-contribution-to-federal-finances" id="toc-albertas-net-contribution-to-federal-finances">5.1 Alberta’s Net Contribution to Federal Finances</a></li>
  <li><a href="#the-equalization-controversy" id="toc-the-equalization-controversy">5.2 The Equalization Controversy</a></li>
  </ul></li>
  <li><a href="#the-dependency-map-reading-the-full-picture" id="toc-the-dependency-map-reading-the-full-picture">6. The Dependency Map: Reading the Full Picture</a>
  <ul>
  <li><a href="#how-alberta-depends-on-the-rest-of-canada" id="toc-how-alberta-depends-on-the-rest-of-canada">6.1 How Alberta Depends on the Rest of Canada</a></li>
  <li><a href="#how-canada-depends-on-alberta" id="toc-how-canada-depends-on-alberta">6.2 How Canada Depends on Alberta</a></li>
  </ul></li>
  <li><a href="#five-facts-that-should-ground-every-policy-debate" id="toc-five-facts-that-should-ground-every-policy-debate">7. Five Facts That Should Ground Every Policy Debate</a></li>
  <li><a href="#data-notes-and-sources" id="toc-data-notes-and-sources">Data Notes and Sources</a></li>
  <li><a href="#references" id="toc-references">References</a></li>
  <li><a href="#feedback" id="toc-feedback">Feedback</a></li>
  </ul>
</nav>
<figure class="wayward-article-hero"><img src="../assets/images/alberta.webp" alt="A Trade Reality Check — What the Province Produces, What It Exports, and What It Needs From Everyone Else" loading="eager" decoding="async"></figure>
<h2 id="albertas-economic-scale">1. Alberta’s Economic Scale</h2>
<p>Before examining trade flows, it helps to understand Alberta’s sheer economic weight. With just 4.9 million people — about 12% of Canada’s population — Alberta punches far above its demographic weight in virtually every economic measure that matters.</p>
<div data-viz="echarts" style="height:340px" data-options="{
  &quot;title&quot;: {&quot;text&quot;: &quot;Alberta vs. Canada: Key Ratios&quot;, &quot;left&quot;: &quot;center&quot;},
  &quot;tooltip&quot;: {&quot;trigger&quot;: &quot;axis&quot;},
  &quot;legend&quot;: {&quot;bottom&quot;: 0, &quot;data&quot;: [&quot;Alberta share (%)&quot;, &quot;Population share (12.4%)&quot;]},
  &quot;xAxis&quot;: {&quot;type&quot;: &quot;category&quot;, &quot;data&quot;: [&quot;GDP&quot;, &quot;Exports&quot;, &quot;Federal Taxes\nPaid&quot;, &quot;Exports per\nCapita (x avg)&quot;]},
  &quot;yAxis&quot;: {&quot;type&quot;: &quot;value&quot;, &quot;max&quot;: 35},
  &quot;series&quot;: [
    {&quot;name&quot;: &quot;Alberta share (%)&quot;, &quot;type&quot;: &quot;bar&quot;, &quot;data&quot;: [12.2, 32.2, 17, 26], &quot;label&quot;: {&quot;show&quot;: true, &quot;position&quot;: &quot;top&quot;, &quot;formatter&quot;: &quot;{c}%&quot;}},
    {&quot;name&quot;: &quot;Population share (12.4%)&quot;, &quot;type&quot;: &quot;line&quot;, &quot;data&quot;: [12.4, 12.4, 12.4, 12.4], &quot;lineStyle&quot;: {&quot;type&quot;: &quot;dashed&quot;}, &quot;symbol&quot;: &quot;none&quot;}
  ]
}">

</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Indicator</th>
<th style="text-align: right;">Alberta</th>
<th style="text-align: right;">Canada</th>
<th style="text-align: left;">AB Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GDP (2024)</td>
<td style="text-align: right;">$344.7B</td>
<td style="text-align: right;">~$2,830B</td>
<td style="text-align: left;">12.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">International exports (2024)</td>
<td style="text-align: right;">$183.2B</td>
<td style="text-align: right;">$568.8B</td>
<td style="text-align: left;">32.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Exports per capita</td>
<td style="text-align: right;">$37,500</td>
<td style="text-align: right;">$14,300</td>
<td style="text-align: left;">2.6× average</td>
</tr>
<tr class="even">
<td style="text-align: left;">Provincial fiscal burden (tax/GDP)</td>
<td style="text-align: right;">9.9%</td>
<td style="text-align: right;">~16%</td>
<td style="text-align: left;">Lowest in Canada</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Net debt/GDP</td>
<td style="text-align: right;">2.1%</td>
<td style="text-align: right;">—</td>
<td style="text-align: left;">Lowest in Canada</td>
</tr>
<tr class="even">
<td style="text-align: left;">Population share</td>
<td style="text-align: right;">12.4%</td>
<td style="text-align: right;">100%</td>
<td style="text-align: left;">Pays 16–17% of federal taxes</td>
</tr>
</tbody>
</table>
<p><em>Sources: Statistics Canada Provincial Economic Accounts 2024; Library of Parliament Trade Profile 2024; Statistics Canada Government Finance 2024.</em></p>
<blockquote>
<p><strong>The central tension:</strong> Alberta has 12% of the population but generates 32% of Canadian exports. That gap is the engine of national wealth — and the source of enduring political friction. {:.callout}</p>
</blockquote>
<hr>
<h2 id="what-alberta-actually-produces">2. What Alberta Actually Produces</h2>
<p>Alberta’s economy rests on a remarkably concentrated production base. Energy dominates, but agriculture and services play significant supporting roles.</p>
<h3 id="energy-the-foundation">2.1 Energy: The Foundation</h3>
<p>Alberta sits atop one of the world’s largest proven oil reserves — the oil sands of the Athabasca, Cold Lake, and Peace River regions.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Product</th>
<th style="text-align: right;">Export Value (2024)</th>
<th style="text-align: right;">% of AB Exports</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Crude petroleum oils</td>
<td style="text-align: right;">$124.2B</td>
<td style="text-align: right;">67.8%</td>
<td style="text-align: left;">Primarily oil sands bitumen/SCO</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hydrocarbon gases (nat. gas, LPG)</td>
<td style="text-align: right;">$8.7B</td>
<td style="text-align: right;">4.7%</td>
<td style="text-align: left;">Gaseous + liquefied propane</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total energy products</strong></td>
<td style="text-align: right;"><strong>$132.5B</strong></td>
<td style="text-align: right;"><strong>72.5%</strong></td>
<td style="text-align: left;"><strong>Down from ~80% a decade ago</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Light petroleum products (imports)</td>
<td style="text-align: right;">($8.2B)</td>
<td style="text-align: right;">—</td>
<td style="text-align: left;">Alberta imports refined products</td>
</tr>
</tbody>
</table>
<h3 id="agriculture-the-underappreciated-pillar">2.2 Agriculture: The Underappreciated Pillar</h3>
<p>Alberta’s agricultural sector is the second major production story — one that rarely receives adequate attention.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Commodity</th>
<th style="text-align: right;">Value / Scale</th>
<th style="text-align: left;">National Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total agri-food exports (2024)</td>
<td style="text-align: right;">$17.5B</td>
<td style="text-align: left;">~20% of all Canadian agri-food exports</td>
</tr>
<tr class="even">
<td style="text-align: left;">Primary products</td>
<td style="text-align: right;">$7.8B</td>
<td style="text-align: left;">Grains, oilseeds, livestock</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Value-added products</td>
<td style="text-align: right;">$9.7B</td>
<td style="text-align: left;">Processed meats, canola oil, whiskey</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beef exports</td>
<td style="text-align: right;">$3.6B</td>
<td style="text-align: left;">43% of Canada’s cattle on AB farms</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Potatoes</td>
<td style="text-align: right;">Leading province</td>
<td style="text-align: left;">23.7% of Canadian potato production</td>
</tr>
<tr class="even">
<td style="text-align: left;">Honey &amp; hemp</td>
<td style="text-align: right;">Largest producer</td>
<td style="text-align: left;">#1 in Canada for both</td>
</tr>
</tbody>
</table>
<p>Alberta’s beef processing capacity is nationally dominant. Over three-quarters of all Canadian beef processing occurs in Western Canada, with the majority concentrated in Alberta. This creates supply chain interdependencies that flow both ways.</p>
<hr>
<h2 id="international-trade-where-albertas-exports-go">3. International Trade: Where Alberta’s Exports Go</h2>
<h3 id="the-export-numbers">3.1 The Export Numbers</h3>
<p>In 2024, Alberta exported $183.2 billion in goods internationally — a 98% increase from 2020’s $92.5 billion, driven by rising oil prices and increased production volumes.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div data-viz="echarts" style="height:320px" data-options="{
  &quot;title&quot;: {&quot;text&quot;: &quot;Alberta Export Destinations (2024)&quot;, &quot;left&quot;: &quot;center&quot;},
  &quot;tooltip&quot;: {&quot;trigger&quot;: &quot;axis&quot;, &quot;axisPointer&quot;: {&quot;type&quot;: &quot;shadow&quot;}},
  &quot;grid&quot;: {&quot;left&quot;: &quot;20%&quot;, &quot;right&quot;: &quot;15%&quot;},
  &quot;xAxis&quot;: {&quot;type&quot;: &quot;value&quot;},
  &quot;yAxis&quot;: {&quot;type&quot;: &quot;category&quot;, &quot;data&quot;: [&quot;Rest of World&quot;, &quot;South Korea&quot;, &quot;Japan&quot;, &quot;China&quot;, &quot;United States&quot;]},
  &quot;series&quot;: [{&quot;type&quot;: &quot;bar&quot;, &quot;data&quot;: [12, 1.5, 2.5, 5.5, 162.1], &quot;label&quot;: {&quot;show&quot;: true, &quot;position&quot;: &quot;right&quot;, &quot;formatter&quot;: &quot;${c}B&quot;}}]
}">

</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Destination</th>
<th style="text-align: right;">Value (2024)</th>
<th style="text-align: right;">% of AB Exports</th>
<th style="text-align: left;">Trend</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">United States</td>
<td style="text-align: right;">$162.1B</td>
<td style="text-align: right;">88.5%</td>
<td style="text-align: left;">+3.7% year-over-year</td>
</tr>
<tr class="even">
<td style="text-align: left;">China</td>
<td style="text-align: right;">~$5–6B</td>
<td style="text-align: right;">~3%</td>
<td style="text-align: left;">Rising post-TMX pipeline</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Japan</td>
<td style="text-align: right;">~$2–3B</td>
<td style="text-align: right;">~1.5%</td>
<td style="text-align: left;">Stable, LNG focus</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Korea</td>
<td style="text-align: right;">~$1.5B</td>
<td style="text-align: right;">~0.8%</td>
<td style="text-align: left;">Growing</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rest of World</td>
<td style="text-align: right;">~$12B</td>
<td style="text-align: right;">~6.5%</td>
<td style="text-align: left;">Fragmented</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>$183.2B</strong></td>
<td style="text-align: right;"><strong>100%</strong></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>88.5% of Alberta’s exports go to one country.</strong> This is the defining structural fact of Alberta’s trade position, and the central vulnerability in any scenario involving a break with Canada or serious trade disruption with the U.S. {:.callout}</p>
</blockquote>
<h3 id="the-tmx-pipeline-effect">3.2 The TMX Pipeline Effect</h3>
<p>The Trans Mountain Expansion pipeline entered commercial operation in May 2024, nearly tripling capacity for moving Alberta crude to the Pacific coast at Burnaby, B.C. The numbers remain modest.</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Period</th>
<th style="text-align: left;">AB Crude to Asia</th>
<th style="text-align: left;">Context</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pre-TMX (before May 2024)</td>
<td style="text-align: left;">~0%</td>
<td style="text-align: left;">Virtually no direct Asian market access</td>
</tr>
<tr class="even">
<td style="text-align: left;">Post-TMX (late 2024)</td>
<td style="text-align: left;">~4.1% of crude exports</td>
<td style="text-align: left;">Early-stage ramp-up</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Theoretical TMX capacity</td>
<td style="text-align: left;">~590,000 bbl/day</td>
<td style="text-align: left;">Vs. AB production of ~3.7M bbl/day</td>
</tr>
</tbody>
</table>
<p>TMX represents a genuine diversification opportunity, but it is currently marginal relative to total production. The U.S. market dependency will persist for years regardless of pipeline infrastructure.</p>
<h3 id="the-import-side">3.3 The Import Side</h3>
<p>Alberta’s international trade balance is massively positive — $183.2B in exports versus approximately $40B in imports, yielding a $143 billion surplus in 2024.</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Import Category</th>
<th style="text-align: right;">Value (2024)</th>
<th style="text-align: left;">Why Alberta Buys This</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Light petroleum products</td>
<td style="text-align: right;">$8.2B (20% of imports)</td>
<td style="text-align: left;">Refinery gap — AB produces heavy crude, needs refined</td>
</tr>
<tr class="even">
<td style="text-align: left;">Machinery &amp; equipment</td>
<td style="text-align: right;">Significant</td>
<td style="text-align: left;">Oil patch capital equipment</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chemical inputs</td>
<td style="text-align: right;">Moderate</td>
<td style="text-align: left;">Industrial feedstocks</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufactured goods</td>
<td style="text-align: right;">Varied</td>
<td style="text-align: left;">Consumer and industrial goods</td>
</tr>
</tbody>
</table>
<hr>
<h2 id="interprovincial-trade-alberta-within-canada">4. Interprovincial Trade: Alberta Within Canada</h2>
<p>International trade numbers — dramatic as they are — tell only part of the story. Alberta is deeply embedded in the Canadian internal market in ways that are less visible but profoundly important.</p>
<h3 id="albertas-interprovincial-exports">4.1 Alberta’s Interprovincial Exports</h3>
<p>In 2019 (the most recent detailed pre-COVID data), Alberta exported approximately $68 billion in goods and services to other Canadian provinces.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div data-viz="echarts" style="height:340px" data-options="{
  &quot;title&quot;: {&quot;text&quot;: &quot;Alberta Interprovincial Export Composition&quot;, &quot;left&quot;: &quot;center&quot;},
  &quot;tooltip&quot;: {&quot;trigger&quot;: &quot;item&quot;, &quot;formatter&quot;: &quot;{b}: {d}%&quot;},
  &quot;series&quot;: [{
    &quot;type&quot;: &quot;pie&quot;,
    &quot;radius&quot;: [&quot;40%&quot;, &quot;70%&quot;],
    &quot;data&quot;: [
      {&quot;value&quot;: 46, &quot;name&quot;: &quot;Services&quot;},
      {&quot;value&quot;: 32, &quot;name&quot;: &quot;Energy Products&quot;},
      {&quot;value&quot;: 11, &quot;name&quot;: &quot;Agricultural Products&quot;},
      {&quot;value&quot;: 11, &quot;name&quot;: &quot;Other Goods&quot;}
    ],
    &quot;label&quot;: {&quot;formatter&quot;: &quot;{b}\n{d}%&quot;},
    &quot;itemStyle&quot;: {&quot;borderRadius&quot;: 6, &quot;borderWidth&quot;: 2}
  }]
}">

</div>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Category</th>
<th style="text-align: right;">Share of Interprovincial Exports</th>
<th style="text-align: left;">Key Destinations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Services</td>
<td style="text-align: right;">~46%</td>
<td style="text-align: left;">B.C., Ontario (professional, financial, energy services)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Energy products (petroleum wholesale)</td>
<td style="text-align: right;">~30–35%</td>
<td style="text-align: left;">Ontario, B.C., Saskatchewan, Quebec</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Agricultural products</td>
<td style="text-align: right;">~10–12%</td>
<td style="text-align: left;">National distribution</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other goods</td>
<td style="text-align: right;">~7–12%</td>
<td style="text-align: left;">All provinces</td>
</tr>
</tbody>
</table>
<p>The services-heavy nature of interprovincial trade is notable: Alberta exports professional expertise, financial services, and energy sector knowledge to the rest of Canada — transactions that do not appear in goods trade statistics but represent real economic value.</p>
<h3 id="what-alberta-buys-from-other-provinces">4.2 What Alberta Buys from Other Provinces</h3>
<p>This is the part of the trade picture most often absent from political discussions of Alberta’s self-sufficiency.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">What Alberta Buys</th>
<th style="text-align: right;">Approximate Value (2016 data)</th>
<th style="text-align: left;">Primary Suppliers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total interprovincial imports</td>
<td style="text-align: right;">~$67B (2016)</td>
<td style="text-align: left;">Ontario, B.C., Quebec (top 3)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manufacturing &amp; machinery</td>
<td style="text-align: right;">Large share</td>
<td style="text-align: left;">Ontario, Quebec</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Transportation services</td>
<td style="text-align: right;">~$15–20B range</td>
<td style="text-align: left;">National carriers, B.C. ports</td>
</tr>
<tr class="even">
<td style="text-align: left;">Processed foods &amp; beverages</td>
<td style="text-align: right;">~$6.2B</td>
<td style="text-align: left;">Ontario, B.C., Quebec, Prairies</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Professional &amp; financial services</td>
<td style="text-align: right;">Significant</td>
<td style="text-align: left;">Ontario, B.C.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Construction materials &amp; inputs</td>
<td style="text-align: right;">Substantial</td>
<td style="text-align: left;">B.C., Ontario</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>In 2016, Alberta’s interprovincial imports ($67B) actually exceeded its interprovincial exports ($63B).</strong> Alberta runs a trade surplus with the world but was, in that period, a net importer from the rest of Canada — a wealthy consumer province buying manufactured goods, services, and processed products it does not produce domestically. {:.callout}</p>
</blockquote>
<h3 id="the-interprovincial-dependency-map">4.3 The Interprovincial Dependency Map</h3>
<p>The B.C. relationship deserves special emphasis: TMX terminates at Burnaby, B.C. All of Alberta’s Asian crude export ambitions run through British Columbia’s port infrastructure, regulatory environment, and Indigenous consultation processes. Alberta’s market diversification strategy is not independent of the rest of Canada — it is entirely dependent on B.C.’s cooperation.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Alberta Needs From…</th>
<th style="text-align: left;">What It Gets</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ontario &amp; Quebec</td>
<td style="text-align: left;">Manufactured goods, vehicles, pharmaceuticals, processed food, financial services</td>
</tr>
<tr class="even">
<td style="text-align: left;">British Columbia</td>
<td style="text-align: left;">Port access (critical for any Asian export), forestry products, Pacific trade gateway</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saskatchewan &amp; Manitoba</td>
<td style="text-align: left;">Agricultural inputs, grain transport networks, regional complementarity</td>
</tr>
<tr class="even">
<td style="text-align: left;">Atlantic Canada</td>
<td style="text-align: left;">Limited direct trade, but national market access through national distributors</td>
</tr>
</tbody>
</table>
<hr>
<h2 id="albertas-fiscal-position-the-federal-transfer-reality">5. Alberta’s Fiscal Position: The Federal Transfer Reality</h2>
<p>The trade data tells one story. The fiscal data tells another — and together they explain much of the political tension surrounding Alberta’s place in Confederation.</p>
<h3 id="albertas-net-contribution-to-federal-finances">5.1 Alberta’s Net Contribution to Federal Finances</h3>
<p>Alberta does not receive equalization payments — it has not since 1964–65. Because Albertans have higher average incomes, they pay proportionally more federal tax and receive proportionally less federal spending.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<div data-viz="echarts" style="height:320px" data-options="{
  &quot;title&quot;: {&quot;text&quot;: &quot;Alberta Net Fiscal Contributions&quot;, &quot;left&quot;: &quot;center&quot;},
  &quot;tooltip&quot;: {&quot;trigger&quot;: &quot;axis&quot;},
  &quot;xAxis&quot;: {&quot;type&quot;: &quot;category&quot;, &quot;data&quot;: [&quot;Net to Ottawa\n(annual)&quot;, &quot;CPP net\n(1981-2022)&quot;, &quot;EI net\n(1981-2023)&quot;, &quot;Cumulative net\n(2007-2023)&quot;]},
  &quot;yAxis&quot;: {&quot;type&quot;: &quot;value&quot;, &quot;name&quot;: &quot;$B CAD&quot;},
  &quot;series&quot;: [{&quot;type&quot;: &quot;bar&quot;, &quot;data&quot;: [17, 53.6, 23.9, 267.4], &quot;label&quot;: {&quot;show&quot;: true, &quot;position&quot;: &quot;top&quot;, &quot;formatter&quot;: &quot;${c}B&quot;}}]
}">

</div>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Fiscal Measure</th>
<th style="text-align: right;">Alberta Data</th>
<th style="text-align: left;">Context</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Net transfer to Ottawa (2007–2023)</td>
<td style="text-align: right;">$267.4B total</td>
<td style="text-align: left;">~$16–17B/year average</td>
</tr>
<tr class="even">
<td style="text-align: left;">Annual net transfer (recent years)</td>
<td style="text-align: right;">$15–27B/year</td>
<td style="text-align: left;">Varies with commodity prices</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AB share of federal taxes paid</td>
<td style="text-align: right;">~16–17%</td>
<td style="text-align: left;">AB has only 12.4% of population</td>
</tr>
<tr class="even">
<td style="text-align: left;">Federal spending received per capita (2024)</td>
<td style="text-align: right;">$2,547/person</td>
<td style="text-align: left;">2nd lowest nationally; PEI gets $6,845</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CPP net contribution (1981–2022)</td>
<td style="text-align: right;">$53.6B net paid in</td>
<td style="text-align: left;">6× greater than B.C.’s net contribution</td>
</tr>
<tr class="even">
<td style="text-align: left;">EI net contribution (1981–2023)</td>
<td style="text-align: right;">$23.9B net paid in</td>
<td style="text-align: left;">Only Ontario paid in more</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Projections estimate Alberta will contribute $252.5 billion more to Ottawa than it receives back from 2025 to 2039 — approximately $17 billion per year on average.</strong> The imbalance is structural, not accidental. {:.callout}</p>
</blockquote>
<p><em>Source: The Clarion, Alberta fiscal projections 2025–2039.</em></p>
<h3 id="the-equalization-controversy">5.2 The Equalization Controversy</h3>
<p>Equalization is the most politically charged transfer program. The program exists to ensure provinces can provide “reasonably comparable levels of public services at reasonably comparable levels of taxation” — a constitutional commitment under s. 36(2) of the <em>Constitution Act, 1982</em>.</p>
<p>Alberta’s grievances with the formula are substantive. The formula includes a hypothetical Alberta PST in calculating fiscal capacity — penalizing Alberta for not having a sales tax — while simultaneously excluding Quebec’s below-market hydroelectricity rates. Critics argue this asymmetry penalizes resource-based revenue systems while protecting politically sensitive hydro policies.</p>
<p>The non-binding 2021 referendum, in which 61.7% of Albertans voted to remove equalization from the Constitution, reflects deep frustration with these asymmetries — even as constitutional scholars note Alberta alone cannot change the formula.</p>
<hr>
<h2 id="the-dependency-map-reading-the-full-picture">6. The Dependency Map: Reading the Full Picture</h2>
<h3 id="how-alberta-depends-on-the-rest-of-canada">6.1 How Alberta Depends on the Rest of Canada</h3>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dependency</th>
<th style="text-align: left;">Mechanism</th>
<th style="text-align: left;">Severity if Lost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Internal trade market</td>
<td style="text-align: left;">~$67B+ in annual interprovincial imports</td>
<td style="text-align: left;">Major — disrupts supply chains</td>
</tr>
<tr class="even">
<td style="text-align: left;">Port access (TMX/Pacific)</td>
<td style="text-align: left;">All Asian export routes go through B.C.</td>
<td style="text-align: left;">Critical for diversification</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pipeline right-of-way</td>
<td style="text-align: left;">Trans Mountain crosses B.C.; federal approval required</td>
<td style="text-align: left;">Existential for current exports</td>
</tr>
<tr class="even">
<td style="text-align: left;">Currency union</td>
<td style="text-align: left;">Canadian dollar pricing for global commodity sales</td>
<td style="text-align: left;">Complex to replicate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Financial system</td>
<td style="text-align: left;">Bay Street capital, Canadian banking regulation</td>
<td style="text-align: left;">Significant transition costs</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trade agreements</td>
<td style="text-align: left;">CUSMA negotiated as Canada, not Alberta</td>
<td style="text-align: left;">Would need renegotiation from scratch</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Regulatory frameworks</td>
<td style="text-align: left;">National food safety, transportation, securities</td>
<td style="text-align: left;">Expensive to duplicate</td>
</tr>
</tbody>
</table>
<h3 id="how-canada-depends-on-alberta">6.2 How Canada Depends on Alberta</h3>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dependency</th>
<th style="text-align: left;">Mechanism</th>
<th style="text-align: left;">Scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Export revenues</td>
<td style="text-align: left;">32.2% of all Canadian international exports</td>
<td style="text-align: left;">Existential for national trade balance</td>
</tr>
<tr class="even">
<td style="text-align: left;">Federal tax base</td>
<td style="text-align: left;">$68.8B federal revenue from AB (2025 est.)</td>
<td style="text-align: left;">~16–17% of federal revenues</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CPP sustainability</td>
<td style="text-align: left;">$53.6B net contribution (1981–2022)</td>
<td style="text-align: left;">Program would need restructuring</td>
</tr>
<tr class="even">
<td style="text-align: left;">EI sustainability</td>
<td style="text-align: left;">$23.9B net contribution (1981–2023)</td>
<td style="text-align: left;">Program would need restructuring</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Energy supply</td>
<td style="text-align: left;">Most Canadian provinces buy AB energy</td>
<td style="text-align: left;">Some would face supply disruption</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agricultural exports</td>
<td style="text-align: left;">~20% of all Canadian agri-food exports</td>
<td style="text-align: left;">National food export capacity</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>The interdependence is real and runs in both directions.</strong> The question is not whether Alberta needs Canada or Canada needs Alberta — both are demonstrably true. The question is whether the terms of that interdependence are fair, and whether the political relationship reflects the economic reality. {:.callout}</p>
</blockquote>
<hr>
<h2 id="five-facts-that-should-ground-every-policy-debate">7. Five Facts That Should Ground Every Policy Debate</h2>
<p><strong>First: Alberta’s exports are 88.5% U.S.-bound.</strong> The primary dependency risk is the U.S. relationship, not the Ottawa relationship. TMX has opened Asian markets, but they represent roughly 4% of crude exports today.</p>
<p><strong>Second: Alberta runs a trade surplus with the world but is a major net buyer from other Canadian provinces.</strong> The “we don’t need them” narrative collides with a ~$67B annual flow of manufactured goods and services moving into Alberta.</p>
<p><strong>Third: Alberta’s fiscal contribution to Confederation is historically large and structurally significant.</strong> $267.4 billion transferred to Ottawa above what Alberta received back (2007–2023) is documented Statistics Canada data. The frustration has a legitimate empirical foundation, even where proposed remedies are contested.</p>
<p><strong>Fourth: Alberta’s market diversification goals depend on infrastructure that crosses other provinces.</strong> TMX terminates in Burnaby. Alberta’s Pacific export strategy requires B.C.’s ports and continued national support for pipeline infrastructure.</p>
<p><strong>Fifth: The energy economy is an extraordinary asset — and an extraordinary concentration risk.</strong> Crude oil and gas are 72.5% of Alberta’s exports. This concentration created the wealth that funds the fiscal transfers — and the vulnerability that makes Alberta dependent on national frameworks, stable U.S. relations, and pipeline access.</p>
<hr>
<h2 id="data-notes-and-sources">Data Notes and Sources</h2>
<p>All figures in Canadian dollars unless otherwise noted. International trade data uses Statistics Canada’s Trade Data Online; interprovincial trade data uses Supply and Use tables. Fiscal balance data uses Statistics Canada’s Fiscal Reference Tables and the published work of Trevor Tombe (University of Calgary), the Fraser Institute, and Fairness Alberta.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Data Used</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Statistics Canada — Provincial Economic Accounts 2024</td>
<td style="text-align: left;">GDP, provincial shares, export growth</td>
</tr>
<tr class="even">
<td style="text-align: left;">Library of Parliament — Trade &amp; Investment Profile: Alberta 2024</td>
<td style="text-align: left;">Export categories, trade partners, import data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">World’s Top Exports (worldstopexports.com)</td>
<td style="text-align: left;">Detailed 2024 export commodity breakdown</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alberta.ca — Agricultural Trade Services 2024</td>
<td style="text-align: left;">Agri-food export detail</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Export Alberta (export.alberta.ca)</td>
<td style="text-align: left;">U.S. trade relationship data</td>
</tr>
<tr class="even">
<td style="text-align: left;">ATB Financial — Alberta’s Exports to Other Provinces</td>
<td style="text-align: left;">Interprovincial export composition</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alberta Government — Economic Commentary on Interprovincial Imports</td>
<td style="text-align: left;">Interprovincial import detail (2014–2016)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Statistics Canada — Government Finance Statistics 2024</td>
<td style="text-align: left;">Federal transfers per capita, fiscal burden</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fraser Institute — Alberta Fiscal Fairness commentary</td>
<td style="text-align: left;">Net fiscal contribution analysis</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fairness Alberta (fairnessalberta.ca)</td>
<td style="text-align: left;">CPP, EI, equalization contribution data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The Clarion — Alberta fiscal projections 2025–2039</td>
<td style="text-align: left;">Forward-looking fiscal contribution estimates</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Note on data limitations:</strong> Detailed interprovincial import data by province is available from Statistics Canada only to 2016. The 2016 figures cited are the most granular publicly available; the directional patterns are confirmed by subsequent aggregate data. {:.callout}</p>
</blockquote>
<hr>
<h2 id="references">References</h2>
<p>Alberta Agriculture and Irrigation. 2024. <em>Agri-Food Trade Statistics</em>. Edmonton: Government of Alberta. <a href="https://www.alberta.ca/agri-food-trade-statistics" class="uri">https://www.alberta.ca/agri-food-trade-statistics</a></p>
<p>Alberta Agriculture and Irrigation. 2024. <em>Alberta Agri-Food Exports</em>. Open Government Portal. Edmonton: Government of Alberta. <a href="https://open.alberta.ca/publications/alberta-agri-food-exports" class="uri">https://open.alberta.ca/publications/alberta-agri-food-exports</a></p>
<p>ATB Financial. 2024. “Beyond Our Borders: Alberta International Exports to December 2024.” <em>The Twenty-Four</em>. Edmonton: ATB Financial. <a href="https://www.atb.com/company/insights/the-twenty-four/alberta-international-exports-to-december-2024/" class="uri">https://www.atb.com/company/insights/the-twenty-four/alberta-international-exports-to-december-2024/</a></p>
<p>Canada. <em>Constitution Act, 1982</em>, s. 36(2). Ottawa: Government of Canada. <a href="https://laws-lois.justice.gc.ca/eng/const/page-16.html" class="uri">https://laws-lois.justice.gc.ca/eng/const/page-16.html</a></p>
<p>Canada Energy Regulator (CER). 2025. “Market Snapshot: Trans Mountain Expansion Eases Pipeline Constraints and Increases Exports to Overseas Markets.” Calgary: CER. <a href="https://www.cer-rec.gc.ca/en/data-analysis/energy-markets/market-snapshots/2025/market-snapshot-trans-mountain-expansion-eases-pipeline-constraints-and-increases-exports-to-overseas-markets.html" class="uri">https://www.cer-rec.gc.ca/en/data-analysis/energy-markets/market-snapshots/2025/market-snapshot-trans-mountain-expansion-eases-pipeline-constraints-and-increases-exports-to-overseas-markets.html</a></p>
<p>Canadian Association of Petroleum Producers (CAPP). 2024. <em>Crude Oil Forecast, Markets and Transportation</em>. Calgary: CAPP. <a href="https://www.capp.ca/resources/crude-oil-forecast/" class="uri">https://www.capp.ca/resources/crude-oil-forecast/</a></p>
<p>Elections Alberta. 2021. <em>Official Results: 2021 Referendum on Equalization</em>. Edmonton: Elections Alberta. <a href="https://www.elections.ab.ca/elections/referendum/" class="uri">https://www.elections.ab.ca/elections/referendum/</a></p>
<p>Fairness Alberta. 2024. <em>Alberta’s Fiscal Contributions to Canada: CPP, EI, and Federal Transfers</em>. Edmonton: Fairness Alberta. <a href="https://fairnessalberta.ca/fiscal-fairness/" class="uri">https://fairnessalberta.ca/fiscal-fairness/</a></p>
<p>Fraser Institute. 2025. “Understanding Alberta’s Role in National Programs, Including the Canada Pension Plan.” Vancouver: Fraser Institute. <a href="https://www.fraserinstitute.org/studies/understanding-albertas-role-national-programs-including-canada-pension-plan" class="uri">https://www.fraserinstitute.org/studies/understanding-albertas-role-national-programs-including-canada-pension-plan</a></p>
<p>Government of Alberta. 2025. <em>Alberta Economic Dashboard: International Merchandise Exports</em>. Edmonton: Treasury Board and Finance. <a href="https://economicdashboard.alberta.ca/dashboard/international-merchandise-exports/" class="uri">https://economicdashboard.alberta.ca/dashboard/international-merchandise-exports/</a></p>
<p>Library of Parliament. 2024. <em>Alberta’s Merchandise Trade with the World</em>. Publication No.&nbsp;2024-501-E. Ottawa: Library of Parliament. <a href="https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/TradeAndInvestment/2024501E" class="uri">https://lop.parl.ca/sites/PublicWebsite/default/en_CA/ResearchPublications/TradeAndInvestment/2024501E</a></p>
<p>Statistics Canada. 2024. <em>Canadian International Merchandise Trade Database (Trade Data Online)</em>. Ottawa: Statistics Canada. <a href="https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2018011-eng.htm" class="uri">https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2018011-eng.htm</a></p>
<p>Statistics Canada. 2024. <em>Consolidated Canadian Government Finance Statistics, 2024</em>. Ottawa: Statistics Canada. <a href="https://www150.statcan.gc.ca/n1/daily-quotidien/251121/dq251121b-eng.htm" class="uri">https://www150.statcan.gc.ca/n1/daily-quotidien/251121/dq251121b-eng.htm</a></p>
<p>Statistics Canada. 2025. <em>Provincial and Territorial Economic Accounts, 2024</em>. Ottawa: Statistics Canada. <a href="https://www150.statcan.gc.ca/n1/daily-quotidien/251106/dq251106a-eng.htm" class="uri">https://www150.statcan.gc.ca/n1/daily-quotidien/251106/dq251106a-eng.htm</a></p>
<p>Statistics Canada. 2025. <em>Interprovincial and International Trade Flows, Basic Prices, Summary Level</em>. Table 12-10-0088-01. Ottawa: Statistics Canada. <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210008801" class="uri">https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210008801</a></p>
<p>Trans Mountain Corporation. 2024. <em>Trans Mountain Announces Milestones of Commercial Service for Expanded System</em>. Burnaby: Trans Mountain Corporation. <a href="https://www.transmountain.com/news/trans-mountain-announces-milestones-of-commercial-service-for-expanded-system" class="uri">https://www.transmountain.com/news/trans-mountain-announces-milestones-of-commercial-service-for-expanded-system</a></p>
<p>Tombe, Trevor. 2018. “Alberta’s Fiscal Future.” <em>School of Public Policy Research Papers</em> 11 (23). Calgary: University of Calgary. <a href="https://doi.org/10.11575/sppp.v11i0.43007" class="uri">https://doi.org/10.11575/sppp.v11i0.43007</a></p>
<p>World’s Top Exports. 2024. “Alberta’s Top Exports 2024.” <a href="https://www.worldstopexports.com/albertas-top-exports/" class="uri">https://www.worldstopexports.com/albertas-top-exports/</a></p>
<hr>
<p><em>· Next in the Series: <a href="../texas-of-the-north/">The Texas of the North</a></em></p>
<h2 class="section-title" id="feedback">Feedback</h2>
<div class="section-copy">
<p>Articles work better with structured feedback than open comment threads. If something is wrong, unclear, or worth discussing, use the route that fits best.</p>
</div>
<div class="feedback-grid">
  <div class="feedback-card">
    <h3>Report An Error</h3>
    <p>Use this when a number, source, or factual claim needs correction.</p>
    <a href="../pages/contact.html">Send a correction →</a>
  </div>
  <div class="feedback-card">
    <h3>Send A Note</h3>
    <p>Use this for responses, nuance, or follow-up questions about the article.</p>
    <a href="../pages/contact.html">Send a note →</a>
  </div>
  <div class="feedback-card">
    <h3>Keep Reading</h3>
    <p>This article is part of the Alberta in Context sequence.</p>
    <a href="./texas-of-the-north.html">Read the next article →</a>
  </div>
</div>

<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Library of Parliament, Trade and Investment Profile: Alberta, 2024.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Alberta.ca, Agricultural Trade Services, 2024.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>World’s Top Exports analysis of Statistics Canada data; Export Alberta 2024.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>ATB Financial, “Alberta’s Exports to Other Provinces,” 2019 data.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Alberta Government, Economic Commentary on Interprovincial Imports, 2014–2016 data.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Statistics Canada Fiscal Balances; Fraser Institute; Fairness Alberta; Library of Parliament.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

<style>
/* ── Newsletter inline CTA ──────────────────────────────────────────────── */
.newsletter-inline {
  margin: 3rem 0 1rem;
  padding: 1.75rem 2rem;
  border: 1px solid var(--border);
  border-left: 3px solid var(--accent);
  background: var(--bg2);
}

.newsletter-inline__kicker {
  margin: 0 0 0.35rem;
  font-family: var(--font-mono);
  font-size: 0.6rem;
  letter-spacing: 0.22em;
  text-transform: uppercase;
  color: var(--accent);
}

.newsletter-inline h2 {
  margin: 0;
  font-family: var(--font-display);
  font-weight: 800;
  font-size: clamp(1.375rem, 2.2vw, 1.75rem);
  line-height: 1.0;
  text-transform: uppercase;
  letter-spacing: 0.02em;
}

.newsletter-inline__body {
  margin: 0.6rem 0 0;
  color: var(--text-2);
  font-size: 0.9rem;
  line-height: 1.6;
  max-width: 46rem;
}

.newsletter-inline__form {
  display: grid;
  gap: 0.75rem;
  margin-top: 1.25rem;
}

.newsletter-inline__row {
  display: grid;
  gap: 0;
  grid-template-columns: minmax(0, 1fr) auto;
  align-items: stretch;
}

.newsletter-inline__field {
  display: grid;
  gap: 0.3rem;
}

.newsletter-inline__field label {
  font-family: var(--font-mono);
  font-size: 0.55rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--text-3);
}

.newsletter-inline__field input {
  width: 100%;
  box-sizing: border-box;
  padding: 0.75rem 1rem;
  border: 1px solid var(--border);
  border-right: none;
  background: var(--bg);
  color: var(--text);
  font: inherit;
  font-size: 0.9rem;
  border-radius: 0;
  outline: none;
}

.newsletter-inline__field input:focus {
  border-color: var(--accent);
  box-shadow: none;
}

.newsletter-inline__submit {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0 1.5rem;
  border: 1px solid var(--accent);
  background: var(--accent);
  color: #fff;
  font-family: var(--font-mono);
  font-size: 0.6rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  cursor: pointer;
  white-space: nowrap;
  border-radius: 0;
  transition: background 0.15s;
}

.newsletter-inline__submit:hover {
  background: #b81818;
  border-color: #b81818;
}

.newsletter-inline__status {
  min-height: 1.2rem;
  margin: 0;
  color: var(--text-2);
  font-size: 0.875rem;
}

.newsletter-inline__status[data-tone="success"] { color: #18633a; }
.newsletter-inline__status[data-tone="error"]   { color: #a12727; }

.newsletter-inline__note {
  margin: 0;
  color: var(--text-3);
  font-family: var(--font-mono);
  font-size: 0.55rem;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

@media (max-width: 720px) {
  .newsletter-inline__row { grid-template-columns: 1fr; }
  .newsletter-inline__field input { border-right: 1px solid var(--border); }
  .newsletter-inline__submit { padding: 0.75rem 1rem; }
}

/* Show newsletter CTA only on article/reading pages */
.newsletter-page-cta {
  display: none;
  max-width: 760px;
  margin: 0 auto;
  padding: 0 1.5rem;
}
body.reading-body .newsletter-page-cta { display: block; }
body.subscribe-page .newsletter-page-cta { display: none !important; }
</style>

<div class="newsletter-page-cta" aria-label="Newsletter subscription">
  <aside class="newsletter-inline">
    <p class="newsletter-inline__kicker">Stay in the loop</p>
    <h2>System Signals &amp; new essays</h2>
    <p class="newsletter-inline__body">
      A weekly digest of the signals worth watching — Alberta economics, energy transition,
      trade geography — plus new essays as they publish. No noise.
    </p>
    <form class="newsletter-inline__form" id="newsletter-cta-form" novalidate="">
      <input type="hidden" name="source" value="article-cta">
      <div class="newsletter-inline__row">
        <div class="newsletter-inline__field">
          <label for="newsletter-cta-email">Email address</label>
          <input type="email" id="newsletter-cta-email" name="email" placeholder="you@example.com" autocomplete="email" required="">
        </div>
        <button type="submit" class="newsletter-inline__submit">Subscribe</button>
      </div>
      <p class="newsletter-inline__status" id="newsletter-cta-status" role="status" aria-live="polite"></p>
      <p class="newsletter-inline__note">One-click confirmation. Unsubscribe anytime.</p>
    </form>
  </aside>
</div>

<!-- ── Footer ──────────────────────────────────────────────────────────────── -->
<footer class="site-footer">
    <div class="wrap">
      <div class="footer-inner">
        <div class="footer-brand">
          <div class="footer-brand__name">Wayward<span>·</span>House</div>
          <p class="footer-brand__desc">Understanding how place, economy, and environment interact through analysis, modelling, and open tools.</p>
          <div class="footer-brand__coords">53°32′N · 113°29′W · wayward.house</div>
        </div>
        <div class="footer-col">
          <div class="footer-col__title">Read</div>
          <ul class="footer-col__links">
            <li><a href="../articles/">Essays</a></li>
            <li><a href="../articles/system-signals/">System Signals</a></li>
            <li><a href="../archive.html">Archive</a></li>
            <li><a href="../topics/">Topics</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <div class="footer-col__title">Learn</div>
          <ul class="footer-col__links">
            <li><a href="../learn/">Library</a></li>
            <li><a href="../learn/computational-geography/core/">Computational Geography</a></li>
            <li><a href="../start-here.html">Start here</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <div class="footer-col__title">Site</div>
          <ul class="footer-col__links">
            <li><a href="../about.html">About</a></li>
            <li><a href="../subscribe.html">Subscribe</a></li>
            <li><a href="../contact.html">Contact</a></li>
            <li><a href="../privacy.html">Privacy</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-base">
        <span class="footer-copy">© 2026 Wayward House · Paul Hobson</span>
        <div class="footer-base-links">
          <a href="../privacy.html">Privacy</a>
          <a href="../terms.html">Terms</a>
          <a href="../contact.html">Contact</a>
        </div>
      </div>
    </div>
  </footer>

<script type="module" src="../assets/dist/main.js"></script>
<script type="module" src="../assets/js/core.js"></script>

<script>
(function () {
  const form   = document.getElementById('newsletter-cta-form');
  if (!form) return;

  const status = document.getElementById('newsletter-cta-status');
  const submit = form.querySelector('.newsletter-inline__submit');
  const api    = window.NEWSLETTER_API_URL || '/api/subscribe';

  form.addEventListener('submit', async function (e) {
    e.preventDefault();

    const email = (form.querySelector('input[name="email"]').value || '').trim();
    if (!email) return;

    const orig = submit.textContent;
    submit.disabled    = true;
    submit.textContent = 'Subscribing…';
    status.textContent = '';
    delete status.dataset.tone;

    try {
      const res  = await fetch(api, {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ email, source: 'article-cta' }),
      });
      const data = await res.json().catch(() => ({}));

      if (res.ok) {
        if (data.message === 'already_subscribed') {
          status.textContent  = 'You\'re already subscribed — check your inbox!';
          status.dataset.tone = 'success';
        } else {
          status.textContent  = 'Check your inbox — confirmation email on its way.';
          status.dataset.tone = 'success';
          form.querySelector('input[name="email"]').value = '';
        }
      } else {
        status.textContent  = data.error || 'Something went wrong. Please try again.';
        status.dataset.tone = 'error';
      }
    } catch {
      status.textContent  = 'Network error. Please try again.';
      status.dataset.tone = 'error';
    }

    submit.disabled    = false;
    submit.textContent = orig;
  });
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wayward\.house");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>